### PR TITLE
Microsoft Outlook Draft Email

### LINKED ISSUE #4493: [BUG] CR not working for microsoft outlook draft email
**Describe the bug**
When creating a draft email with multiple lines in the `content`, the CR are not taken in account in the email.

**To Reproduce**
1. Create a draft email step in a workflow
2. Fill the `content` field with multiple lines:
```
Line 1
Line 2
Line 3
```
4. Run the step
5. Check the draft email

**Expected behavior**
The content of the email must be
```
Line 1
Line 2
Line 3
```

**Current behavior**
The content of the email is:
```
Line 1 Line 2 Line 3
```

**Additional context**
When sending an email, the same behavior happends when the field `content_type` is left to default (`HTML`).
[Pipedream support can acces the test workflow I've made](https://pipedream.com/@LucBerge/test-multiple-lines-p_q6CnmyB/inspect). 

**Conclusion**
Because the field `content_type` is not visible when creating a draft email, the value is left to default (`HTML`) and the CR are not taken in account.

**You must add the field `content_type` when creating a draft email.**

Also:
- It makes no sence to set the default `content_type` value to `HTML` since most people will just write some text. They will not understand why CR is not working....
- It makes no sence to make it a string input since [only `text` and `html` values are possible](https://learn.microsoft.com/en-us/graph/api/resources/itembody?view=graph-rest-1.0). Use a dropdown list instead so the user know all the possible values.

### PR DESCRIPTION
**Pull request by LucBerge**
This PR fixes #4493

- Add field `content_type` for the component `microsoft_outlook-create-draft-email`
- Default value for field `content_type` set to `text`
- Now use dropdown list for field `content_type`

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4496"></a>

### CODE REVIEW

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
Hi @LucBerge, Can you also update the description of the 'Content' field since it can have either 'text' or 'html' content. 
image

**Comment by DilanAthukorala** [comment]
Verification completed and ready for release!

**Review by lcaresia — APPROVED** [review]

**Comment by LucBerge** [comment]
Fixed with #4534

**Pull request closed without merging**
