### PR TITLE
803 sources and actions textlocal

### PR DESCRIPTION
**Pull request by luancazarine**
Sources
 - New Contact: Refactored
 - New Inbox Mesage: Created
 - New Sent API Message: Refactored

Action
    - Create Contact: Created
    - Send SMS: Created

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by lcaresia — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Just minor changes!

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
> Hello @DilanAthukorala @Hassan-Abbas-SQA, could you handle this PR instead? TextLocal is not supported in my country :( image

@vunguyenhung Same in my country. But I will give it a try with VPN

**Comment by luancazarine** [comment]
> @luancazarine Following issues are observed;
> 
> for **create_contact** action
> 
> 1. Unable to send request with group id (if it's required then need to make it a required param)
> 
> image
> 
> 2. Group ID field issue observed
> 
> image
> 
> for **send_sms** action
> 
> 1. default value has not been set to param `Test`
> 
> image
> 
> 2. unable to send request with number (if it's required need to make it a required param)
> 
> image
> 
> 3. Group ID field issue
>    image
> 4. please check whether the following params should be given boolean input options the UX
> 
> image

image

**Pull request closed without merging**
