### PR TITLE
Add support for Llama2, Palm, Cohere, Replicate Models - using litellm 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## WHAT
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### <samp>🤖 Generated by Copilot at 2564da1</samp>

The pull request updates the `component_code_gen` package to use the `litellm` library for code generation tasks. This library is a wrapper around the OpenAI API that simplifies and enhances the code documentation and transformation features.

### <samp>🤖 Generated by Copilot at 2564da1</samp>

> _To transform code with more ease_
> _We switched to the `litellm` library_
> _It wraps the OpenAI API_
> _And makes code generation snappy_
> _We hope you like this change, pretty please_

### <samp>🤖 Generated by Copilot at 2564da1</samp>

*  Replace `openai` library with `litellm` library for code generation tasks ([link](https://github.com/PipedreamHQ/pipedream/pull/7577/files?diff=unified&w=0#diff-27675f9b63c3bc04dc6debb87feda8639f849a79cf11f8a55b31a3ae33c204a0L6-R11), [link](https://github.com/PipedreamHQ/pipedream/pull/7577/files?diff=unified&w=0#diff-53a92d1cb5d0f3bd57b82e0c495cc9c1966d4a5493ab88134930f6dbd93e0059R11), [link](https://github.com/PipedreamHQ/pipedream/pull/7577/files?diff=unified&w=0#diff-53a92d1cb5d0f3bd57b82e0c495cc9c1966d4a5493ab88134930f6dbd93e0059L71-R72))

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@dylburger @dannyroosevelt can you please take a look at this PR? Happy to add more tests/docs if this looks good 😊

**Comment by dylburger** [comment]
@ishaan-jaff yes, thanks! We just put this on our backlog for PR review and someone from our team will get back to you ASAP.

**Review by vellames — APPROVED** [review]
@dylburger I am not a python expert. But looks good to me

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by ishaan-jaff** [comment]
@vunguyenhung I looked at the notion and could not see any test report.

This is all I see
Screenshot 2023-08-14 at 8 02 32 AM

How can I see the test report ?

**Comment by ishaan-jaff** [comment]
@vunguyenhung updated! let me know if you have any feedback on this

**Comment by ishaan-jaff** [comment]
@vunguyenhung litellm accepts api_key as a param here: https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py#L8 

it's used / set here: https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L720 


> If you want, would you replace litellm with your own abstraction over open ai/palm/cohere and others?

I'm the maintainer of litellm so it is my own abstraction over open ai/palm/cohere 😊

planning on adding the `litellm.api_key` to docs by EOD

**Comment by dannyroosevelt** [comment]
@andrewjschuang tagging you on this -- have you already reviewed the PR?

**Review by lcaresia — APPROVED** [review]

**Comment by andrewjschuang** [comment]
This is very interesting, thanks @ishaan-jaff! Currently we are only using GPT-4 but in the future we may support different models. Closing this for now

**Pull request closed without merging**
