### PR TITLE
refactor: Use Query API for Qdrant

### PR DESCRIPTION
**Pull request by Anush008**
## WHY

Updates the Qdrant component to use the new [Query API](https://qdrant.tech/blog/qdrant-1.10.x/#one-endpoint-for-all-queries) that superseded the search API.

## Summary by CodeRabbit

- **New Features**
	- The `search` method has been renamed to `query`, enhancing clarity in data querying.
	- The `vector` parameter is now labeled as `query`, reflecting a semantic update in data processing.

- **Improvements**
	- The response now returns only relevant data points, improving response handling efficiency.

- **Dependency Updates**
	- Updated the `@qdrant/js-client-rest` library to a newer version, which may include new features and improvements.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by GTFalcao — COMMENTED** [review]
Hi @Anush008 , thanks for your contribution!

One question - does this change what is expected in the `vector` prop? Adding to that, would it be useful for that prop to have a documentation link as some others do?

**Comment by Anush008** [comment]
Hey @GTFalcao. No changes there. A list of floats continues to work.

**Comment by Anush008** [comment]
> ## WHY
> 
> Updates the Qdrant component to use the new [Query API](https://qdrant.tech/blog/qdrant-1.10.x/#one-endpoint-for-all-queries) that superseded the search API.
> 
> 
> 
> ## Summary by CodeRabbit
> 
> 
> - **New Features**
> 	- The `search` method has been renamed to `query`, enhancing clarity in data querying.
> 	- The `vector` parameter is now labeled as `query`, reflecting a semantic update in data processing.
> 
> - **Improvements**
> 	- The response now returns only relevant data points, improving response handling efficiency.
> 
> - **Dependency Updates**
> 	- Updated the `@qdrant/js-client-rest` library to a newer version, which may include new features and improvements.
> 
>

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
