### PR TITLE
[Components] Piggy #8188

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖 Generated by Copilot at ac4628c</samp>

This pull request adds and modifies several files for the Piggy components, which are integrations with the Piggy CRM platform. It adds four new actions for creating and updating contacts and contact attributes, and one new source for emitting events when a new contact is created. It also fixes a bug in the `package.json` file and updates the dependencies in `pnpm-lock.yaml`. It deletes two unnecessary files and adds a new file for the app definition and configuration.

### <samp>🤖 Generated by Copilot at ac4628c</samp>

> _This pull request adds some new features_
> _For the Piggy app and its creatures_
> _You can create and update_
> _Contacts and attributes_
> _And trigger workflows with `new-contact-created` events_

### <samp>🤖 Generated by Copilot at ac4628c</samp>

*  Add app definition and authentication for Piggy ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-405589f6c78c72b9e66a0f22b19f9a558382186ce7679c5c8ae0edbdde0a290dR1-R72))
*  Add actions for creating, finding, updating, and deleting contacts and contact attributes using the Piggy API ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-7551288cc813d0016d48c362c3339ee7e507885637c3347e2327d197902c979dR1-R51), [link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-e3c7a8fb9b0f7f4a09dfa069b350ff4e735f1962946e853625a180df91d010b0R1-R31), [link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-d2df303f4a1517201d9259315a816973015da5636ddefcbb5b54545bdc20eadfR1-R52), [link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-6694d9332911b04653c3ec9554b5a1000ade3ce32209b3569a6e3d0b720a42ceR1-R88))
*  Add source for emitting events when a new contact is created in Piggy ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-5436121f8e1fb686c479b814f07755e6c12f11b6e5af9ca4adc7b842a402e675R1-R76))
*  Fix `main` property in `package.json` to point to `piggy.app.mjs` ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-beb89c38b78c2692009c4ad4c7ee6c02b96addee2c951e43ff53c0325a1140abL5-R18))
*  Add and update dependencies for Piggy components in `pnpm-lock.yaml` ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL4053-R4056), [link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL13593-R13596))
*  Delete unused files `components/piggy/app/piggy.app.ts` and `components/piggy/.gitignore` ([link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-2545527534b42429ef0942a095ab2e9faac57084e1a71935fa1e48149f429f06), [link](https://github.com/PipedreamHQ/pipedream/pull/8413/files?diff=unified&w=0#diff-84a460215d15c6aa9358e8ecb7f5f204792f35358b4451690483d7d9f3a95220))

### CODE REVIEW

**Review by alysonturing — DISMISSED** [review]
LGTM!

**Comment by lcaresia** [comment]
@vunguyenhung Hey, I tried many ways to fix `Update Contact`, but without success. I think it's a bug on Piggy API.

Cc: @malexanderlim

**Comment by malexanderlim** [comment]
@lcaresia can we just exclude Update Contact for now and ship the other components?

**Review by alysonturing — APPROVED** [review]
LGTM!

**Pull request merged**
