### PR TITLE
Ghost new actions

### PR DESCRIPTION
**Pull request by jcortes**

### CODE REVIEW

**Review by vellames-turing — DISMISSED** [review]

**Comment by vunguyenhung** [comment]
Hello @jcortes, I see there're some conflicts on this PR, could you check and resolve it? As I see we have spent some effort on this, so it would be a waste for our user if the code got out-dated

**Comment by DilanAthukorala** [comment]
@jcortes I'm still observing the above mentioned issue, was there any fix done for this?

**Comment by vunguyenhung** [comment]
Hello @jcortes, I'm just checking in since this has been hanging for a while, do you have bandwidth to work on this next 🙏 ?

**Review by feyzullah — APPROVED** [review]

**Comment by DilanAthukorala** [comment]
Verification completed, This is ready for release.

**Pull request merged**
