### PR TITLE
feat: Ecwid get order and update order status actions added

### PR DESCRIPTION
**Pull request by trendoscope-algorithms**
image

image

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4359"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by vellames — APPROVED** [review]

**Comment by Hassan-Abbas-SQA** [comment]
@vellames account selection prop should be on the top
image
i can’t integrate with Ecwid store
image

**Comment by trendoscope-algorithms** [comment]
I think you need paid account for integration. We had those issue last time as well.

**Comment by trendoscope-algorithms** [comment]
@Hassan-Abbas-SQA Updated following:

* Ecwid account information moved to top for both actions.
* Description updated for get order

I think you need paid account to test integration. Can we proceed with test from my side?

image

image

**Comment by dannyroosevelt** [comment]
@trendoscope-algorithms are we able to use `[async options()](https://pipedream.com/docs/components/api/#async-options-example)` to fetch the set of orders so users can select from a list instead of manually entering an ID?

**Comment by trendoscope-algorithms** [comment]
@dannyroosevelt - there can be thousands of orders. Do you think it is still advisable to select from list?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt - there can be thousands of orders. Do you think it is still advisable to select from list?

Oh, got it. Maybe not in that case. Do you anticipate users typically referencing that order ID from a previous step? If so then skipping async options probably makes sense.

**Comment by trendoscope-algorithms** [comment]
> 

@dannyroosevelt  - Yes thats right. In my present workflow, I have a webhook registration on ecwid which sends me events whenever there is new order - All my further actions are based on the event which contains just order id. I can use these actions in further steps to get complete order and after fulfilment - update status etc.

**Comment by dannyroosevelt** [comment]
Got it, makes sense! I think one of the missing items is just a component description for each action, then let's ship it!

**Comment by Hassan-Abbas-SQA** [comment]
@trendoscope-algorithms please add the descriptions for each action and move the ticket to ready for QA so i can test it and ship it to ready for release

**Comment by trendoscope-algorithms** [comment]
@dannyroosevelt - updated component descriptions.

Not sure I have the right to move the ticket @Hassan-Abbas-SQA 
Will leave it with you guys.

**Comment by dannyroosevelt** [comment]
@trendoscope-algorithms I just merged and published this -- your actions should be live on the Pipedream registry now! Let us know if you run into any issues and thank you for the contribution!

**Pull request merged**
