### PR TITLE
[ACTION] Github - Create branch #4917

### PR DESCRIPTION
**Pull request by lcaresia**

### CODE REVIEW

**Review by alysonturing — DISMISSED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
@lcaresia Please check the following,

1. The description typo should be corrected
image


2. Only one branch is listed in source branch prop, other branches are not listed. 
image

**Comment by lcaresia** [comment]
@DilanAthukorala Here show more than one branch, can you confirm if you really have more than one branch active?
image

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!

**Review by alysonturing — APPROVED** [review]

**Pull request merged**
