### PR TITLE
#3737 - PractiTest

### LINKED ISSUE #3737: PractiTest
### App
PractiTest

### Triggers
* New Issue
* New Test Event

### Actions
* Create Requirement
* Create a Run

### PR DESCRIPTION
**Pull request by GTFalcao**
# New Actions
- **Create Requirement**
- **Create Run**

# New Sources
- **Issue Created**
- **Test Created**

Closes #3737

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
@GTFalcao Can we have descriptions for all the props in both implemented actions so it will be consistent?

**Comment by GTFalcao** [comment]
@DilanAthukorala sure, we can add them - the ones that are empty have no description in the API Docs either, and it seems redundant to add a description that is the same as the label.

If you have any suggestions let me know, otherwise I'll look into it ASAP and let you know when they've been added.

**Comment by GTFalcao** [comment]
Thanks a lot @DilanAthukorala , I've added the descriptions.

I've also noted this as a point of attention, as @luancazarine had already pointed out to me that some props were missing descriptions - will make sure to double check those moving forward.

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!

**Review by luancazarine — APPROVED** [review]

**Pull request merged**
