### PR TITLE
Vision6 - new sources and actions

### LINKED ISSUE #3829: Vision6
### App
Vision6

### Triggers
* Contact Was Reactivated
* Contact Was Deactivated
* Contact Has Subscribed
* Contact Was Unsubscribed
* Contact Was Added
* Contact Was Updated

### Actions
* Add a Contact
* Subscribe a Contact
* Unsubscribe a Contact
* Update a Contact
* Deactivate a Contact
* Delete a Contact
* Reactivate a Contact

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3829 

**Sources**

- Contact Activated
- Contact Deactivated
- Contact Subscribed
- Contact Unsubscribed
- New Contact
- Contact Updated

**Actions**

- Create Contact
- Subscribe Contact
- Unsubscribe Contact
- Update Contact
- Deactivate Contact
- Delete Contact
- Reactivate Contact

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by luancazarine — APPROVED** [review]
Hi @michelle0927. LGTM! Ready for QA!

**Comment by DilanAthukorala** [comment]
@michelle0927 following issues are found, 

1. Typo in the description
image

2. **update_contact**  - description needs to be corrected
image


3. **contact_deactivated** source not emitting event - following error observed
image


4. contact_unsubscribed source not emitting events - following error observed
image

**Comment by DilanAthukorala** [comment]
Verification completed, Ready for release.

**Review by luancazarine — APPROVED** [review]

**Pull request merged**
