### PR TITLE
5998 trigger dear new triggers

### PR DESCRIPTION
**Pull request by luancazarine**
Sources:
  - New Authorized Purchase Order
  - New Authorized Sale Quote
  - New Available Stock Level Changed
  - New Customer Updated
  - New Purchase Credit Note Authorized
  - New Purchase Invoice Authorized
  - New Purchase Stock Received Authorized
  - New Sale Backordered
  - New Sale Credit Note Authorized
  - New Sale Full Payment Received
  - New Sale Invoice Authorized
  - New Sale Pack Authorized
  - New Sale Partial Payment Received
  - New Sale Pick Authorized
  - New Sale Shipment Authorized
  - New Sale Shipment Tracking Number Change
  - New Sale Undo
  - New Sale Voided
  - New Supplier Updated
  
### <samp>🤖 Generated by Copilot at d944f36</samp>

This pull request adds 18 new source components for the DEAR inventory app that emit events for various types of transactions and changes in the app. It also updates the metadata format of an existing source component and fixes a typo in a constant name. The new components share some common constants and base methods from the `components/dear/common` folder. The components are named after the webhook types they handle and the metadata they provide.

### <samp>🤖 Generated by Copilot at d944f36</samp>

> _We are the `components/dear/common` legion_
> _We unleash the webhooks of destruction_
> _We emit the events of the inventory_
> _We are the `components/dear/common` legion_

### <samp>🤖 Generated by Copilot at d944f36</samp>

*  Fix typo in constant name `SALE_INVOICEA_UTHORISED` to `SALE_INVOICE_AUTHORISED` ([link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-301fdabb8b3d65006c04190b66f323eec524827cc4e260c37e1a257762d12529L20-R20))
*  Add new source components for various DEAR inventory app events, importing common constants and base methods from `components/dear/common` folder and defining specific webhook type and metadata for each event ([link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-93f6f8cb2db26f4f94106008788814560e40fc1c6b81ae9e00d9c1ad2c87eefbR1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-af9876b8492801a7c80c6db9d64835b9e3cc4252633d4f0b51816833b95b30d0R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-979737869f20e66ea7a5593f569528d7c1c375701d108e3b04c2ab3f3ad3be09R1-R32), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-aaed610b782508710d56a5b7a404ebf58c2ba268f1b4550b962e00e237a36e0eR1-R34), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-8fc40d543fe49a4168c11b3d9dbbde4541b0aa96faa1b345cba721afee7f59d1R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-2b194a5b9067da71fb117a764f2c4f0b60b2eb8902a3056841fc4a52a4a9297cR1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-50452927fefc599486799db11a86c39cbffbdccc1150e4524834f0f81d09a622R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-6155ff0e8534e1200dbed233b18a81f6b6579f6d8fc18ca99a1d94dd9ca12602R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-7b264c6fbe0241166d4b17825981170db6f6c86e88b848239e7ee3e17103ea52R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-c8b1d8df79d97b1e2accba6887c5365d5e2fb6faa37063621c0f556a53ff05a3R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-c4734a7198f3314156c7f0b673d7527728b21c5c765c933bd6fb9cef278d9aedR1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-e53f25748c30b71f1debe6b035617fe98c726fa3ec67bf71ce2e58c2e89d74d3R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-a6a823b7d8a6ea41c1a28879a1094ff40e6d9bfe7a1a0d3af672a9f2dab8bcffR1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-601a0d3fa648505397ccee228b2062360f647bd3cedabb970ed0348a7868c2c0R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-431ae26c25dd783887f22ca6861c6695940eb685e9a3dcffcd768a505288a1f1R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-416b21deab9592f5daa5811b8e904da256d906c324b889e63d4a1122df8e7ce5R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-ed70ce6a9f3af4604f40209b8ce7d2ec488b0d3a08f762661be4c850d1f804f9R1-R33), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-8b573c0f37862347ac3204bad071a6d8d89f152e77ca218bfbf53312fe0915baR1-R33))
*  Update version and metadata format of existing source component for new authorized sale order event, replacing JSON string of payload with summary that includes sale order number ([link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-d4b374ef68518d80bfe9c392405fa67dafbf949d3ec37dc7be48158c0a5346e3L10-R10), [link](https://github.com/PipedreamHQ/pipedream/pull/6190/files?diff=unified&w=0#diff-d4b374ef68518d80bfe9c392405fa67dafbf949d3ec37dc7be48158c0a5346e3L20-R28))

### CODE REVIEW

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by andrewjschuang** [comment]
Related to: #6219

**Comment by andrewjschuang** [comment]
Hey @michelle0927, since you've recently QA'ed some triggers for Dear can you also please QA this one?

**Comment by michelle0927** [comment]
Some test cases did not pass or need improvement

1. The following sources already exist, so can be removed from this PR:
New Available Stock Level Changed,
New Customer Updated,
New Sale Shipment Tracking Number Changed,
New Supplier Updated

2. New Sale Voided - no events emitted

3. New Product - needs improvement
Improvements needed: Limit historical events to 25 events. Improve prop names by changing “Starting With SKU” and “Starting With Name” to “SKU” Starts With” and “Name Starts With”. 

4. All other components passed.

Test report
[Dear_6190.pdf](https://github.com/PipedreamHQ/pipedream/files/11423245/Dear_6190.pdf)

**Comment by dannyroosevelt** [comment]
@luancazarine what's the status of this? 

And can you give context on why we created so many sources?

**Comment by vunguyenhung** [comment]
Hi @michelle0927, as you have previously QA this ticket, could you verify it again? If it is not possible, could you share the account with me privately so I can QA it? My trial ended

**Comment by michelle0927** [comment]
@luancazarine Thanks for making those changes. Everything looks good except that I'm still not seeing any events for the New Sale Voided trigger. I tried voiding multiple sales, but don't see any events being received. Is it working successfully for you?

Screenshot 2023-05-12 at 11 48 47 AM
Screenshot 2023-05-12 at 11 49 01 AM
Screenshot 2023-05-12 at 11 49 13 AM
Screenshot 2023-05-12 at 11 49 23 AM

**Comment by luancazarine** [comment]
> @luancazarine Thanks for making those changes. Everything looks good except that I'm still not seeing any events for the New Sale Voided trigger. I tried voiding multiple sales, but don't see any events being received. Is it working successfully for you?
> 
> Screenshot 2023-05-12 at 11 48 47 AM Screenshot 2023-05-12 at 11 49 01 AM Screenshot 2023-05-12 at 11 49 13 AM Screenshot 2023-05-12 at 11 49 23 AM

Hi @michelle0927. If you go to Dear website and go to Settings->Automation->Notifications, you can see all webhooks. If you click in it, you can see their log and, I don't know why, but they aren't sending any for the sale voided.

**Comment by michelle0927** [comment]
I think it's safe to remove the New Sale Voided trigger for now.
Ready for release!

**Comment by luancazarine** [comment]
Hi @michelle0927, I've removed The

> I think it's safe to remove the New Sale Voided trigger for now. Ready for release!

Hi @michelle0927, It's done. Could you approve it?

**Pull request merged**
