### PR TITLE
FixZerotierNodeStatusLogic

### PR DESCRIPTION
**Pull request by chrisdrumz**
### <samp>🤖 Generated by Copilot at 71cfe85</samp>

Fix `zerotier` source bug with node status. Use node last seen timestamp from database instead of API response.

### <samp>🤖 Generated by Copilot at 71cfe85</samp>

> _Sing, O Muse, of the valiant coder who fixed the `zerotier` bug_
> _That plagued the network of many a peer, and made their status vague_
> _He wisely stored the last seen time of each node in the `db`_
> _And thus he showed their true online or offline state with accuracy_

## WHY

Existing logic doesnt work, status is stored as boolean but compared as if it was milliseconds since epoch

### <samp>🤖 Generated by Copilot at 71cfe85</samp>

* Fix online/offline status of nodes by storing and using last seen timestamp ([link](https://github.com/PipedreamHQ/pipedream/pull/7295/files?diff=unified&w=0#diff-fae016a9ac10811352dc439cc2f5fa04046d6f71321fecf2fc13ce49d4e1edc9L25-R35), [link](https://github.com/PipedreamHQ/pipedream/pull/7295/files?diff=unified&w=0#diff-fae016a9ac10811352dc439cc2f5fa04046d6f71321fecf2fc13ce49d4e1edc9L45-R60))

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by michelle0927 — COMMENTED** [review]
Thank you for your contribution! My only comment is that you'll need to update the versions of the files that import `common.mjs` as well as the `package.json` version.

`new-node-join.mjs` - 0.0.6 -> 0.0.7
`new-node-left.mjs` - 0.0.6 -> 0.0.7
`new-node-offline.mjs` - 0.0.7 -> 0.0.8
`new-node-online.mjs` - 0.0.7 -> 0.0.8
`package.json` - 0.0.6 -> 0.0.7

As this doesn't affect functionality, I'm moving along to QA.

**Review by michelle0927 — APPROVED** [review]

**Comment by chrisdrumz** [comment]
1. Node status is null on first poll
2. New node offline will not fire until node has been offline for 3 minutes or more, after previously being online.
    - To test: Put node online, initiate check for events, put node offline, wait 3 minutes, initiate check for events
3. New node online will fire if node has checked in with Zerotire in last 3 minutes, after previously being offline.
    - To test: Put node offline, wait 3 minutes, initiate check for events, put node online, initiate check for events again

**Comment by chrisdrumz** [comment]
This seems to be working great now

**Comment by michelle0927** [comment]
Hi @vunguyenhung, I think there have been some changes since this was last tested.

**Review by michelle0927 — APPROVED** [review]

**Pull request merged**
