### PR TITLE
Twitter OAuth 1.0a auth implementation

### PR DESCRIPTION
**Pull request by GTFalcao**
### <samp>🤖 Generated by Copilot at b1bb465</samp>

This pull request updates the Twitter component package to use OAuth 1.0a for authentication and the latest platform dependency for improved actions and app logic. It also increments the versions of all the actions and sources in the component to reflect the changes. The main file affected is `components/twitter/app/twitter.app.ts`, where the authentication logic is implemented. The other files are mostly version updates in the `package.json` and the individual action and source files.

### <samp>🤖 Generated by Copilot at b1bb465</samp>

> _Sing, O Muse, of the mighty deeds of the Pipedreamers,_
> _Who craft swift and cunning actions for the Twitter app,_
> _And update the platform dependency with skill and care,_
> _Like Hephaestus forging the thunderbolts of Zeus._

## WHY

We're moving the OAuth 1.0a authentication code to the Twitter component itself. This is why we made updates to the platform axios package on #6034 and #6077 : to export the function that transforms the request config (for OAuth) and be able to import it in the Twitter component (or any component that needs to do this in the future).

### <samp>🤖 Generated by Copilot at b1bb465</samp>

*  Incremented the version of the `@pipedream/twitter` package and the `@pipedream/platform` dependency to use the latest features and bug fixes ([link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-0de416850a5239717126154b4d43f050131fd0d81f67ff253a7e0f6b60d024ceL3-R3), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-0de416850a5239717126154b4d43f050131fd0d81f67ff253a7e0f6b60d024ceL19-R19))
*  Updated the authentication logic in the `twitter.app.ts` file to use the correct consumer and token keys and secrets for the OAuth 1.0a signature, and to use the `transformConfigForOauth` function from the `@pipedream/platform` module ([link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edL4-R7), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edL102-R112), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edL124-R133), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edL139-R150))
*  Incremented the version of all the actions and the source to align with the updated version of the `@pipedream/platform` dependency ([link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-a1373002f650102c864faeb7867284cd8b901a8cf865ed6e7b654958df53aa16L13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-72dac938c50aed338983c96a539e0386942f91f51ef47097936ac37bb7e47bfdL12-R12), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-7543f426e5e255aa709eb2c6599f0ee89c136e66626adba0a6e9a57a024e295cL12-R12), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-5b44f84f0867bd6cb1f0d76ab64caec5f4daaee80423bef35e8c359da76a8249L13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-22ad073362230c6ef936a13dc199cf4b4b88e720994d5421d354db7867eec448L16-R16), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-b22431a2983f4381d8c29acdcd07c1fe6f16c1799d98c1e0b5cabd15954ca138L18-R18), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-61d66d6c6e6f0a5a272264dd566294458192dbb80d351b0638c2999956f9390cL12-R12), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-7d029cc64219e684390458a835af83104668013ff3cc7cfcf8dce99eeef31ef0L21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-caa82d0d011e6f177dc09c4c5cc69c182722e4929c0e8de3618583e5142ec8a1L21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-84c8ea84740ba6e8d1ad13fd0cdb10115427653dcf4a2b045182601f2392042bL21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-ca7ec28532456081821322789d07de1c870604446bec4c221ad85819e729dfe2L23-R23), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-78a92d41eefa32c18e6e80c03f9380e469724ff41be87df2f4a1fff02e011ae1L21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-5012fedc91f1e75b5af995fa1ac982521179a0d66446987b7944ae4088b27f39L12-R12), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-71cca0daeb5bf93f2be0877800f84dbcd1b6b0884c12b271e9ad9815f2b694afL21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-dff93efe266cb2dd1487da3887ea4d60c2418a23e962630709f758f457f7a76eL21-R21), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-ad0d3ba8c281113c8c09357e87eb3d597fcc05840e50465389cb81453ee62d35L13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-be62489d0d1799a066d819c74bc784f5367fc76cdc00cd34c925ea804f5a8b0dL12-R12), [link](https://github.com/PipedreamHQ/pipedream/pull/6094/files?diff=unified&w=0#diff-300f188390bf4b184af3cd53ecd0f9ffa933660b9ebf49e40d35026e53e7f46bL18-R18))

### CODE REVIEW

**Review by feyzullah — DISMISSED** [review]

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Twitter_4567_0953.pdf](https://github.com/PipedreamHQ/pipedream/files/11305958/Twitter_4567_0953.pdf)

**Comment by dannyroosevelt** [comment]
@GTFalcao are you still working on this?

**Comment by GTFalcao** [comment]
@dannyroosevelt sorry, I got caught up in other things and forgot to check the status on this. I asked @vunguyenhung if the validation could include the (currently) live Twitter components as well to help isolate the issue, since I'm unable to validate almost all of these components myself.

In any case, I'll check back on this after clearing my current task (and PRs to review) to investigate what could be causing the 401 responses, besides API tier limitations.

**Comment by dannyroosevelt** [comment]
@GTFalcao can you remind me if Twitter responds w/ a consistent error message when it's an API tier limitation? It'd be great to catch those and present a more user friendly message when possible.

**Comment by GTFalcao** [comment]
Yes @dannyroosevelt, I would always get the same error when attempting to use an endpoint not available in the free plan, I believe it was 403 with a message that, although not accurate (saying my app was not tied to a project, when it was), was consistent.

Right now I'm not able to re-log into the Twitter app, receiving this error on the auth popup (after being redirected back from Twitter):
image

**Comment by GTFalcao** [comment]
Hey @vunguyenhung , were you able to confirm if the errors you obtained when testing this only occur in this branch and not in the live Twitter components?

As I mentioned before, I'm unable to test most of these components myself due to the free tier limitations - I can only use "Get User" (for 'me'), "Create Tweet" and "Delete Tweet".

From the code alone, there don't seem to be any inconsistencies, as all components use the auth fields in the same way, and the ones I am able to use all work fine consistently - not being able to debug the others myself makes it much harder to find what may be causing the potential issue.

**Comment by vunguyenhung** [comment]
Hi @GTFalcao, I reconnected my Twitter account with your credentials you sent me, though it is showing the error in the OAuth Popup constantly
Screenshot 2023-05-17 at 10 57 20
image

I've also tried with Danny's credentials and it's failed with the same error. 

Would you mind checking if you can reproduce my issue?

**Comment by vunguyenhung** [comment]
Hi @GTFalcao @dannyroosevelt. I have tested all sources and actions. 

I observed that for Free Tiers, there're only 3 actions available:
- Create Tweet
- Delete Tweet
- Get User

Other actions/sources are either not available for Free Tier, or require Twitter API V2 Authentication. I have documented them all in the report here, please take a look:
[Twitter_6094_1933.pdf](https://github.com/PipedreamHQ/pipedream/files/11507768/Twitter_6094_1933.pdf)

For the actions/sources that require Twitter API V2 Authentication, I would suggest us to create a new Twitter v2 API app and move the sources/ actions there. Then rename this app to Twitter v1.1. What do you think?

**Comment by vunguyenhung** [comment]
Hi @GTFalcao, okay I understand. Then I think I will move this back to Doing right?

**Comment by GTFalcao** [comment]
Hey @vunguyenhung , I added this error message to all the Twitter actions and sources:
```
Check if your app is properly configured on the Twitter Developer Portal, and if your plan has access to the endpoint used by this component.
```
Sources should also include the JSON-stringified error in the message, though I'm unable to test this right now as I cannot successfully deploy any sources (none of them are available on the free plan).

Actions will export the error in the step, as is typically already done for most requests by the Pipedream axios wrapper.

Let me know if there's anything else I can do to improve upon this.

**Pull request merged**
