### PR TITLE
Filter Update Actions

### LINKED ISSUE #2643: [Refactor] Filter actions
We should make a couple changes to the current Filter action:

1. Add an optional "Reason" prop, and set the `default` to `Condition met for exiting [or continuing] workflow`
2. Break out the current Filter action into 3 different actions and get rid of the `continue` prop:
- "Continue workflow based on a condition" (`filter-continue-workflow-condition`)
- "End workflow based on a condition" (`filter-end-workflow-condition`)
- "End workflow" (`filter-end-workflow`)

### PR DESCRIPTION
**Pull request by andrewjschuang**
Splits Filter into 3 actions:

1. Continue Workflow on Condition
2. End Workflow on Condition
3. End Workflow on Custom Condition

Resolves #2643

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by vellames-turing — APPROVED** [review]

**Comment by dannyroosevelt** [comment]
@andrewjschuang I think for the binary conditions, the logic disappeared that did not render the `Value to compare against` field, right? 
image

**Comment by andrewjschuang** [comment]
> @andrewjschuang I think for the binary conditions, the logic disappeared that did not render the `Value to compare against` field, right?

In your case it should be:
Value to evaluate: `url`,
Value to compare against: `{{steps.search_issues.$return_value[0]}}`

Or it can be:
Screen Shot 2022-04-25 at 12 53 08 PM

**Comment by dannyroosevelt** [comment]
> > > > @andrewjschuang I think for the binary conditions, the logic disappeared that did not render the `Value to compare against` field, right?
> > > 
> > > 
> > > @dannyroosevelt, in your case it should be: Value to evaluate: `url`, Value to compare against: `{{steps.search_issues.$return_value[0]}}`
> > 
> > 
> > In the case of the `url` key not being found, I get an error in both configurations, instead of calling `$.flow.exit()`
> 
> @dannyroosevelt what is the value of `steps.search_issues.$return_value`?

In this case it's `[]`

**Comment by andrewjschuang** [comment]
> In this case it's `[]`

@dannyroosevelt oh so the error occurs because `steps.search_issues.$return_value[0]` is `undefined`. It is necessary to check if `steps.search_issues.$return_value[0] !== null && steps.search_issues.$return_value[0].url !== null` as two consecutive steps

**Comment by dannyroosevelt** [comment]
Shouldn't this get evaluated as `null`? 
image

**Comment by andrewjschuang** [comment]
> Shouldn't this get evaluated as `null`?

It should. Just pushed a fix

**Review by dannyroosevelt — APPROVED** [review]

**Pull request merged**
