### PR TITLE
[BUG] DM Received Slack Trigger emits on every DM *sent* as well as received #5560

### PR DESCRIPTION
**Pull request by lcaresia**
Is working as expect on tests, so I think the problem is with the version in production.
I just will increase the version to publish again to production.

Cc: @dannyroosevelt

### CODE REVIEW

**Comment by vunguyenhung** [comment]
Hello @lcaresia, I tested with my test account but and still see there're still events when I send a message to a user
image
image
image

Could you check again?

**Comment by lcaresia** [comment]
You set to not received `myselfs` messages?

**Comment by dannyroosevelt** [comment]
> @vunguyenhung Do you set to not received `myselfs` messages?

Oh, I see that is indeed the issue... but that's strange and I still think is not intentional for this trigger. We should remove that prop and not emit on DMs I **send**, only receive.

**Comment by vunguyenhung** [comment]
Hi @lcaresia @dannyroosevelt

> Do you set to not received myselfs messages?

Oh I actually set the `Ignore Myself: FALSE`. I think the prop `Ignore Myself` is indeed quite confusing, @lcaresia I think we could have the source only emit the events for receiving message and remove that prop?

**Comment by lcaresia** [comment]
@vunguyenhung Can you test again?

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Slack_5560_1012.pdf](https://github.com/PipedreamHQ/pipedream/files/10835745/Slack_5560_1012.pdf)

**Review by alysonturing — APPROVED** [review]

**Pull request merged**
