### PR TITLE
[SOURCE] Slack - New Star Added

### LINKED ISSUE #3460: [TRIGGER] Slack New Saved Message
Describe the event source. What app is this for, and what event does the trigger correspond to?
Triggers when you save a message.

Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.
https://api.slack.com/events/star_added

In https://github.com/PipedreamHQ/pipedream/issues/3299. was asked to create a Source that triggers just when you save a message. I created a new source with this behavior named 'New Star Added Message', but talking with @dannyroosevelt it was decided that is better delete this one and just add a filter with a string[] prop in the 'New Start Added' Source

### PR DESCRIPTION
**Pull request by vellames-turing**
Closes #3460 

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/3526"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by jcortes — COMMENTED** [review]
Hi @vellames-turing LGTM! Ready for QA!

**Comment by DilanAthukorala** [comment]
@vellames-turing Adding stars to 'Users' does not emit events. 
image

**Comment by vunguyenhung** [comment]
Hello @vellames-turing, I'm just checking in, do you have bandwidth to resolve the test case failed 🙏

**Comment by vellames-turing** [comment]
Hey @vunguyenhung , I am having some medical problems right now, I am off today, probably I will be able to finish it on Monday, but if you have some urgency closing this ticket, maybe @luancazarine could take a look

**Comment by vunguyenhung** [comment]
Sorry I forgot @vellames-turing! Please take care of your health! No rush, you can continue on this ticket when you comeback! 

Get well soon boss!

**Review by michelle0927 — APPROVED** [review]
Looks good!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Slack_New_Star_Added_3526.pdf](https://github.com/PipedreamHQ/pipedream/files/9252155/Slack_New_Star_Added_3526.pdf)

**Pull request merged**
