### PR TITLE
Linear 5683

### LINKED ISSUE #5683: Linear -- new triggers and bug fix
### New trigger to add:
- Issue Status Updated (include optional `string[]` props for Team and Project)

### Bug:
I cannot configure the `projectId` prop from the Issue Updated trigger
Screenshot by Dropbox Capture

https://developers.linear.app/docs/graphql/working-with-the-graphql-api

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #5683 

The issue appears to be related to a breaking change in the Linear API/sdk. Using axios to retrieve the list of projectIds fixes the issue.

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
Hi @michelle0927 
Thank you for your contribution, LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Linear_5683_0841.pdf](https://github.com/PipedreamHQ/pipedream/files/10963389/Linear_5683_0841.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Linear_5683_0020.pdf](https://github.com/PipedreamHQ/pipedream/files/10971846/Linear_5683_0020.pdf)

**Review by luancazarine — APPROVED** [review]
LGTM!

**Pull request merged**
