### PR TITLE
GoDial #3639

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖 Generated by Copilot at 6e12a9f</samp>

This pull request adds new action and source components to the godial app, as well as a new app component that handles the authentication and API methods. It also modifies the `package.json` file to fix a bug and deletes some unused files. The new components allow users to add and manage lists, contacts, and members in the godial service, and to trigger events when a contact is updated.

### <samp>🤖 Generated by Copilot at 6e12a9f</samp>

> _Sing, O Muse, of the godial app, the wondrous work of code_
> _That lets the mortal users add and manage their contacts and lists_
> _With action components, swift and bold, that call the API_
> _And source components, wise and skilled, that emit events with ease_

### <samp>🤖 Generated by Copilot at 6e12a9f</samp>

*  Add new app component for godial API authentication and methods (`godial.app.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-39ee45600f1191175bd1a500abae2177dda864e7d90eae80f3a2c55eee3996a9R1-R95))
*  Add new action components for adding list, contact, and member to godial app (`add-list.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-7b792153da045353a39ccebac567690d6df44699ee0dcfe2e46bdab2a320c100R1-R47); `add-contact.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-b865a010cb0357169ab567343c4f2a1abd5ec226be0feb9c35a1fde01822b727R1-R52); `add-member.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-86d91f37341f3772f25d2b2f66bd467769e518f33013b3c3ac6619094432f510R1-R77))
*  Add new source component for emitting updated contacts in a list (`new-updated-contact.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-f2628cf3ec8ab54fc647ae1adca4c5b2ce78881c0751a97602da5a99e63da6b5R1-R47))
*  Add new module for exporting member roles constants (`constants.mjs`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-b401688b8caa54d5d667c78dd1692e5d02a24b04c691934ca7877784b9265e22R1-R7))
*  Update package.json file to change version and main entry point (`package.json`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-886d8eddd91ed0fae58809ea7bde07c46b91ac2d0f296462628395f2661542f5L3-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-886d8eddd91ed0fae58809ea7bde07c46b91ac2d0f296462628395f2661542f5L18-L17))
*  Delete unused files (`.gitignore`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-72ca938d88d23b6da77ca63cea33588754c09631d6daa75219fd9bc802cf5d97); `godial.app.ts`, [link](https://github.com/PipedreamHQ/pipedream/pull/5996/files?diff=unified&w=0#diff-3b31fba15cf997289f2578f57a9a3cf76ed6f5a2c4cb31587a0061fdc5dd3242))

### CODE REVIEW

**Review by vellames — APPROVED** [review]

**Comment by vunguyenhung** [comment]
Hi @lcaresia, I see that the actions directory is named `action` but not `actions`. Will this affect anything in the publish process?

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[GoDial_3639_1118.pdf](https://github.com/PipedreamHQ/pipedream/files/11218093/GoDial_3639_1118.pdf)

**Comment by lcaresia** [comment]
@vunguyenhung GoDial API to add lists are some bug, so I removed this action from list.

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[GoDial_3639_2214.pdf](https://github.com/PipedreamHQ/pipedream/files/11223642/GoDial_3639_2214.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[GoDial_3639_1001.pdf](https://github.com/PipedreamHQ/pipedream/files/11228420/GoDial_3639_1001.pdf)

**Review by vellames — APPROVED** [review]

**Pull request merged**
