### PR TITLE
Add delighted action "sending to people"

### PR DESCRIPTION
**Pull request by nauxliu**

### CODE REVIEW

**Comment by dylburger** [comment]
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by jcortes — CHANGES_REQUESTED** [review]
@nauxliu Thanks for this contribution! I've just added a few request changes and it will be good to go. You can modify the file `delighted.app.mjs` to this:
```javascript
import delightedLib from "delighted";

export default {
  type: "app",
  app: "delighted",
  label: "Delighted",
  description: "The Delighted app that will be used to send the survey.",
  propDefinitions: {},
  methods: {
    lib() {
      return delightedLib(this.$auth.api_key);
    },
    async sendingToPeople(params) {
      return this.lib().sendingToPeople(params);
    },
  },
};

```

Then you can make the modifications I suggested in the rest of the review. Thanks!

**Comment by dannyroosevelt** [comment]
> @nauxliu Thanks for this contribution! I've just added a few request changes and it will be good to go. You can modify the file `delighted.app.mjs` to this:
> 
> ```js
> import delightedLib from "delighted";
> 
> export default {
>   type: "app",
>   app: "delighted",
>   label: "Delighted",
>   description: "The Delighted app that will be used to send the survey.",
>   propDefinitions: {},
>   methods: {
>     lib() {
>       return delightedLib(this.$auth.api_key);
>     },
>     async sendingToPeople(params) {
>       return this.lib().sendingToPeople(params);
>     },
>   },
> };
> ```
> 
> Then you can make the modifications I suggested in the rest of the review. Thanks!

@jcortes feel free to apply your suggested changes so we can get this one done

**Review by jcortes — APPROVED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
could you please check this Issue.

image

**Comment by DilanAthukorala** [comment]
> could you please check this Issue.
> 
> image

@nauxliu @jcortes Please let me know if you have an update on this issue.

**Comment by dannyroosevelt** [comment]
@jcortes I moved this back to Doing

**Comment by michelle0927** [comment]
Closing this PR, as https://github.com/PipedreamHQ/pipedream/pull/2817 takes over for this one.

**Pull request closed without merging**
