### PR TITLE
Whatsapp - Send Text Using Template with support for dynamic URL in buttons

### LINKED ISSUE #5899: [ACTION] Send Whatsapp Text Using Template with support for dynamic URL in buttons
**Is there a specific app this action is for?**

Send Whatsapp Text Using Template with support for dynamic URL in buttons

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates

I currently have this error message when I am try to use the current "Send Text Using Template" action with a template that requires a dynamic url

`Error - Request failed with status code 400
{"error":{"message":"(#131008) Required parameter is missing","type":"OAuthException","code":131008,"error_data":{"messaging_product":"whatsapp","details":"buttons: Button at index 0 of type Url requires a parameter"},"fbtrace_id":"AEPaERTvMqsfcyJDi_VKjTO"}}`

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #5899 

Note to QA: I haven't fully tested this because I haven't been able to get Meta to approve any test templates with dynamic URL buttons in my WhatsApp Business account.

### CODE REVIEW

**Review by feyzullah — APPROVED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hi, I'm unable to test this either. I'll have this merged for the customer to test

**Comment by rapidmarket** [comment]
We can test it. Let us know once it is merged !

**Comment by michelle0927** [comment]
> We can test it. Let us know once it is merged !

@rapidmarket This has been merged! Let us know what you find.

**Comment by rapidmarket** [comment]
I have this error:

`{"error":{"message":"(#132000) Number of parameters does not match the expected number of params","type":"OAuthException","code":132000,"error_data":{"messaging_product":"whatsapp","details":"body: number of localizable_params (2) does not match the expected number of params (1)"},"fbtrace_id":"AWEdqoNazWdC-QDZfywosJo"}}`

I think the button params shouldn't be added to the body. I have also attached an example of payload. There is quite a lot that can be done for whatsapp messaging, maybe you should add a call to action inside the component for someone to request a feature if they need it.

The payload: 

`		"components": [{
			"type": "button",
			"sub_type": "url",
			"index": 0,
			"parameters": [{
				"type": "text",
				"text": "here"
			}]
		}, {
			"type": "body",
			"parameters": [{
				"type": "text",
				"text": "jhon"
			}, {
				"type": "text",
				"text": "here"
			}]
		}]`


` "components": [
        {
          "type": "header",
          "parameters": [
            {
              "type": "image",
              "image": {
                "link": "'$HEADER_IMAGE_URL'"
              }
            }
          ]
        },
        {
          "type": "body",
          "parameters": [
            {
              "type": "text",
              "text": "Anand"
            },
            {
              "type": "text",
              "text": "Quest"
            },
            {
              "type": "text",
              "text": "113-0921387"
            },
            {
              "type": "text",
              "text": "23rd Nov 2019"
            }
          ]
        },
        {
          "type": "button",
          "index": "0",
          "sub_type": "url",
          "parameters": [
            {
              "type": "text",
              "text": "1Z999AA10123456784"
            }
          ]
        }
      ]`

**Pull request merged**
