### PR TITLE
Auto-generated documentation for apps

### PR DESCRIPTION
**Pull request by jverce**
* PropelAuth (`propelauth`)
* Propeller (`propeller`)
* ProWorkflow (`proworkflow`)
* Pushbullet (`pushbullet`)
* Pusher (`pusher`)
* Pushover (`pushover`)
* Pushsafer (`pushsafer`)
* Pushshift Reddit Search (`pushshift_reddit_search`)
* Python (`python`)
* QStash (`qstash`)
* Qualaroo (`qualaroo`)
* quentn (`quentn`)
* Quickbase (`quickbase`)
* Quickbooks (`quickbooks`)
* Quickbooks Sandbox (`quickbooks_sandbox`)
* QuickEmailVerification (`quickemailverification`)
* Quipu (`quipu`)
* Qwilr (`qwilr`)
* Radar (`radar`)
* Raindrop (`raindrop`)
* Ramp (`ramp`)
* Range (`range`)
* RapidAPI (`rapidapi`)
* Rasa (`rasa`)
* Rat Genome Database (`rat_genome_database`)
* Raven Tools (`raven_tools`)
* RAWG Video Games Database (`rawg_video_games_database`)
* Razorpay (`razorpay`)
* RD Station CRM (`rd_station_crm`)
* Re:amaze (`re_amaze`)
* Readwise (`readwise`)
* RealPhoneValidation (`realphonevalidation`)
* Rebrandly (`rebrandly`)
* ReCharge (`recharge`)

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by GTFalcao** [comment]
Hey @jverce since this and #5063  are labeled as drafts and were added to the component board automatically as notes, I'm removing them from there for the time being, to keep it clean - let me know if any other action is needed regarding those PRs

**Comment by jverce** [comment]
Thanks @GTFalcao. 
Indeed these PRs are not related to the "components" work and so feel free to ignore/exclude them from your reviews.

**Review by dannyroosevelt — APPROVED** [review]

**Pull request merged**
