### PR TITLE
Shopify: Add new sources for fulfillment orders (request accepted/rejected)

### PR DESCRIPTION
**Pull request by colinmollenhour**
## WHAT

This adds constants for the many new webhook event topics that were added in Shopify with the Fulfillment Order update. It also adds two new sources for when a fulfillment order is rejected or accepted.

## WHY

The event topics are useful in cases where a user wants to perform an action when a fulfillment request is rejected (an error condition prevents the order from being accepted) or accepted (in which case take another follow-up action like update the status or send an email).

## HOW

1. Set up a fulfillment service
2. Request fulfillment for an order
3. Query new pending fulfillment requests
4. Accept or reject the fulfillment request using the Shopify REST API
5. Shopify will then fire this webohook. The event topics are documented [here](https://shopify.dev/docs/api/admin-rest/2023-07/resources/webhook#event-topics-fulfillment-orders-fulfillment-request-accepted)

Example payload:
```
{
  "fulfillment_order": {
    "id": "gid://shopify/FulfillmentOrder/1",
    "status": "in_progress",
    "request_status": "accepted"
  },
  "message": "We will ship the item tomorrow."
}
```

I don't know how to test this code exactly.. Looks very straightofrward so will test after it is merged unless there is another way to test sources but there is a lot of setup involved.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by luancazarine — APPROVED** [review]
Hi @colinmollenhour. Thanks for your contribution! LGTM!

**Review by luancazarine — APPROVED** [review]
Hi @colinmollenhour. Thanks for your contribution! LGTM!

**Comment by colinmollenhour** [comment]
@vunguyenhung These topics were added in API version 2023-01 but based on [here](https://github.com/PipedreamHQ/pipedream/blob/master/components/shopify/common/constants.mjs#L3C28-L3C28) it appears Pipedream is using 2023-04 already so that shouldn't be a problem.

The docs indicate that you need certain scopes, perhaps your app or API key is lacking these?
image

I tested adding a webhook for that topic to my own test store with an HTTP client and it worked without issue:

```
POST https://colin-tests.myshopify.com/admin/api/2023-04/webhooks.json
Content-Type: application/json
...

{"webhook":{"address":"****","topic":"fulfillment_orders/fulfillment_request_accepted","format":"json"}}

HTTP/1.1 201 Created
Date: Thu, 06 Jul 2023 22:18:45 GMT
Content-Type: application/json; charset=utf-8
X-Shopify-API-Version: 2023-04
...

{
  "webhook": {
    "id": 1236492583062,
    "address": "****",
    "topic": "fulfillment_orders\/fulfillment_request_accepted",
    "created_at": "2023-07-06T18:18:45-04:00",
    "updated_at": "2023-07-06T18:18:45-04:00",
    "format": "json",
    "fields": [],
    "metafield_namespaces": [],
    "api_version": "2021-04",
    "private_metafield_namespaces": []
  }
}
```

**Comment by colinmollenhour** [comment]
I've not tried the code in this PR, not sure how to run it myself?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by colinmollenhour** [comment]
I did some debuggiong, it appears this is due to the node library used for Shopify is missing a lot of webhook topics in it's enum. I opened a PR here: https://github.com/MONEI/Shopify-api-node/pull/621

Can you re-open and once it is updated I will continue testing?

**Comment by colinmollenhour** [comment]
The node library was updated but I still get the same error.. Not able to look into it further at this time...

**Pull request closed without merging**
