### PR TITLE
[Feature] speed up async options for Google Drive app integrations #1801

### LINKED ISSUE #1801: [FEATURE] speed up async options for Google Drive app integrations
The async option for selecting "My Drive" or "Shared Drive" is slow when configuring Actions and Sources for Google Sheets or Google Drive. Since most users are typically selecting "My Drive", can we set that as the default Drive, while still allowing users to change to "Shared Drive" if needed?

### PR DESCRIPTION
**Pull request by js07**
Sets "My Drive" as the default Drive for Google Drive and Google Sheets actions and sources. Users can still select a shared drive by enabling [structured mode](https://pipedream.com/docs/workflows/steps/params/#structured-params).

Resolves #1801

### CODE REVIEW

**Review by vellames-turing — CHANGES_REQUESTED** [review]
@js07 Looks like we have some conflicts here. Can you please resolve it? Thank you!

**Comment by vellames-turing** [comment]
Btw, it would be nice if you could:

- [ ] Convert files to to `mjs`
- [ ] Add missing API Docs to actions description
- [ ] Add `summary` to actions

Thank you :)

**Comment by js07** [comment]
@vellames-turing  [Changes](https://github.com/PipedreamHQ/pipedream/pull/1808#issuecomment-982380133) to [Convert files to to `mjs`](https://github.com/PipedreamHQ/pipedream/pull/1718/commits/93c4e189c118a06156c1b143e533db1502b76c4c), [Add missing API Docs to actions description](https://github.com/PipedreamHQ/pipedream/pull/1718/commits/5ea79f09d959529420bc3005bdaefffb8782f226), and [Add `summary` to actions](https://github.com/PipedreamHQ/pipedream/pull/1718/commits/0537ab82c8e6656b4daaa29888c4c1ea5bf6098a) are made in commits to [the PR branch for Google Drive new actions](https://github.com/PipedreamHQ/pipedream/pull/1718/commits/0537ab82c8e6656b4daaa29888c4c1ea5bf6098a). Do you think we should duplicate those commits in this PR (using `git cherry-pick`), or approach this issue another way?

**Comment by vellames-turing** [comment]
@js07 I think so, I guess that the best idea is to cherry-pick one of these PRs into a single one. This way the merge process would be easier. Please let me know which PR will be the main one after the cherry-pick. Thank you :)

**Comment by js07** [comment]
@vellames-turing I added the commits from this PR to #1718 in this commit: https://github.com/PipedreamHQ/pipedream/pull/1718/commits/bc5aa50090f97d06f61e1afb757f9b666ab7696c

So https://github.com/PipedreamHQ/pipedream/pull/1718 will be the main PR.

**Comment by vellames-turing** [comment]
@js07 Since I approved the #1718 . I guess you can abandon this one

**Comment by js07** [comment]
Closing this PR because changes from this PR were added to #1718.

**Pull request closed without merging**
