### PR TITLE
7663 event id optional

### PR DESCRIPTION
**Pull request by bhavanichandra**
### <samp>🤖 Generated by Copilot at bf26cf8</samp>

This pull request improves the functionality of the `upcoming-event-alert` source for `google_calendar`.

### <samp>🤖 Generated by Copilot at bf26cf8</samp>

> _Oh we are the Pipedream crew and we code with skill and pride_
> _We add new components every day to make our users satisfied_
> _We make the `eventId` prop optional for the `upcoming-event-alert`_
> _And we heave away and haul away with `nationbuilder` and `talend`_

## WHY

To fetch all the upcoming events from a google calendar, event Id should optional.

Following changes done:
- Made event Id optional
- Updated the logic to adhere to the change.
- Tested with `pd dev` command in my personal account, it retrieved all the events in my calendar.

### <samp>🤖 Generated by Copilot at bf26cf8</samp>

*  Make `eventId` prop optional for `upcoming-event-alert` source ([link](https://github.com/PipedreamHQ/pipedream/pull/7700/files?diff=unified&w=0#diff-990352624b434d2ec7b65255699b766f361ff1191b65a72dad3a21cc53a558fcR25))
*  Handle both cases of having or not having `eventId` prop in `processEvent` method of `upcoming-event-alert` source ([link](https://github.com/PipedreamHQ/pipedream/pull/7700/files?diff=unified&w=0#diff-990352624b434d2ec7b65255699b766f361ff1191b65a72dad3a21cc53a558fcL96-R118))

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by lcaresia — APPROVED** [review]
LGTM!

**Comment by bhavanichandra** [comment]
Hi everyone, I'm trying to fix it, my daily credit limit is exhausted. I will check it tomorrow. Thanks

**Review by alysonturing — APPROVED** [review]
LGTM

**Comment by michelle0927** [comment]
Resolved by #7663

**Pull request closed without merging**
