### PR TITLE
Bannerbear: Added new actions and minor refactor

### PR DESCRIPTION
**Pull request by jcortes**
# Actions
- [x] Create Collection - Generates multiple Images based on a Template Set
- [x] Create Image - Generates a new Image
- [x] Create Video - Creates a Video
- [x] Approve a Video - Approve a video to proceed with rendering
- [x] Create Animated Gif - Creates an Animated Gif
- [x] Edit a Video - Update a video auto-transcription

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by feyzullah — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello @jcortes, I have tested this PR and there're some test cases needed improvement. 

Please check the test report below for more information
[Bannerbear_753.pdf](https://github.com/PipedreamHQ/pipedream/files/8928570/Bannerbear_753.pdf)

**Comment by jcortes** [comment]
Hi @vunguyenhung plese test again acording to latest changes I pushed, thanks!

**Comment by vunguyenhung** [comment]
Hello @jcortes, your improvements seem good! 

Though I would suggest the last improvement is that in the "Create Animated GIF" action, the Media Input URL is actually optional
Screen Shot 2022-06-21 at 20 25 44
I will move the issue to ready for release, you can change the code and then merge without re-test! Thanks!

**Pull request merged**
