### PR TITLE
5424 components mailbluster

### PR DESCRIPTION
**Pull request by luancazarine**
Triggers
  - New order created
  - New product created
  - 
Actions
  - Create a product
  - Create a lead
  - Get a product
  - Get a lead

### CODE REVIEW

**Review by vellames — DISMISSED** [review]

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Mailbluster_5424_1446.pdf](https://github.com/PipedreamHQ/pipedream/files/10729972/Mailbluster_5424_1446.pdf)

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Mailbluster_5424_1128.pdf](https://github.com/PipedreamHQ/pipedream/files/10752183/Mailbluster_5424_1128.pdf)

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information [Mailbluster_5424_1128.pdf](https://github.com/PipedreamHQ/pipedream/files/10752183/Mailbluster_5424_1128.pdf)

@vunguyenhung I was unable to reproduce these errors, the sources are working fine for me.

Source - New Order Created
image

Source - New Product Created
image
image

**Comment by vunguyenhung** [comment]
Hello @luancazarine, for some reason I just faced the same error as in the test report. For this I think I will have this release for now and track for any issue raised! Thanks 🙏

**Review by feyzullah — APPROVED** [review]

**Pull request merged**
