### PR TITLE
Shopify - New Components

### LINKED ISSUE #5448: [TRIGGER] Shopify: Product added to custom collection
Shopify. Triggers when a product is added to a custom collection.

https://shopify.dev/docs/api/admin-rest/2023-01/resources/collect

I think this is the correct resource, but I'm not 100% sure. I can investigate further if you think it's the wrong way to do it.

### LINKED ISSUE #5449: [ACTION] Shopify: Add product to a custom collection
Shopify

https://shopify.dev/docs/api/admin-rest/2023-01/resources/collect#post-collects
(add product to a custom collection)

https://shopify.dev/docs/api/admin-rest/2023-01/resources/customcollection#post-custom-collections
(create a custom collection)

I'm not sure if these should be separate actions or part of the same action.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #5448 

**Trigger**
- Product Added to Custom Collection

Resolves #5449 

**Actions**
- Create Custom Collection
- Add Product to Custom Collection

### CODE REVIEW

**Review by alysonturing — APPROVED** [review]
LGTM, Approved!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Shopify_5575_2326.pdf](https://github.com/PipedreamHQ/pipedream/files/10852550/Shopify_5575_2326.pdf)

**Comment by zecul** [comment]
Thanks Michelle, using this right now. Is there any way to enter an array in the product description?

ie a single product ID is added to multiple collections at once?

**Comment by michelle0927** [comment]
> Thanks Michelle, using this right now. Is there any way to enter an array in the custom collection title?
> 
> ie a single product ID is added to multiple collections at once?

@zecul It looks like the Shopify API only allows for adding one product to one collection at a time, but we could update the component to loop through an array of product ids. Do you mind creating a new issue to request that the action "Add Product to Custom Collection" be updated to allow for multiple products?

We also have an open issue for creating [loops in Pipedream workflows](https://github.com/PipedreamHQ/pipedream/issues/193). It's not completed yet, but the issue describes a workaround using two different workflows. If you're comfortable implementing that workaround, that would be another way to loop through an array of product IDs.

**Comment by zecul** [comment]
Hi @michelle0927 

Thanks so much. I have been using the dual workflow method which works fine, but as I understand it it means calling the shopify API 15,000 times with a single product ID when we could call it once with 15,000 product IDs (I think?).

#5595 
#5596

**Pull request merged**
