### PR TITLE
[Components] Certifier: Add `create-group` action

### PR DESCRIPTION
**Pull request by mariczne**
## WHY

This PR adds a new action for Certifier integration.
It uses a public endpoint detailed here: https://developers.certifier.io/reference/create-a-group

## Summary by CodeRabbit

- **New Features**
	- Introduced a new action for creating groups within the Certifier application.
	- Added methods for searching designs and creating groups.
	- New properties for group creation and design options have been added.

- **Bug Fixes**
	- Alert added to ensure at least one design field is filled during group creation.

- **Version Updates**
	- Updated version for "Issue Credential" component and the `@pipedream/certifier` package.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by mariczne** [comment]
I wasn't sure whether to bump `issue-credential` action's version, since it did not change at all, but I did so `Components Checks / Ensure component commits modify component versions` check passes. Let me know if this was intended

**Comment by michelle0927** [comment]
> I wasn't sure whether to bump `issue-credential` action's version, since it did not change at all, but I did so `Components Checks / Ensure component commits modify component versions` check passes. Let me know if this was intended

Yes, the version for `issue-credential` has to be bumped because `certifier.app.mjs` was updated, and `issue-credential` imports it. Thanks for making that change!

**Review by michelle0927 — APPROVED** [review]
This looks great! Thank you so much for your contribution, ready for QA!

**Pull request merged**
