### PR TITLE
[IMPROVEMENT] ClickUp - New Update Task: add prop for selecting fields that have been updated #5690

### PR DESCRIPTION
**Pull request by lcaresia**

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
Hi @lcaresia, thanks for your contribution! LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[ClickUp_5690_1403.pdf](https://github.com/PipedreamHQ/pipedream/files/10976854/ClickUp_5690_1403.pdf)

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[clickup_5721_0953.pdf](https://github.com/PipedreamHQ/pipedream/files/10986143/clickup_5721_0953.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[clickup_5690.pdf](https://github.com/PipedreamHQ/pipedream/files/11008092/clickup_5690.pdf)

**Review by luancazarine — APPROVED** [review]

**Pull request merged**
