### PR TITLE
#6717 - Migrate Twitter developer app components

### LINKED ISSUE #6717: [Components] Update twitter_developer_app components
**Action:**
- Send DM

**Triggers:**
- New Message
- New Tweet Metrics

Since the Twitter API now requires users to create their own developer app, these components (which currently exist in the `twitter_developer_app` app) should be integrated into the `twitter` app and updated to use the V2 API.

An user reported issues with the message-related components, so these should be priority, as tweet metrics might not be readily available to implement in the V2 API yet (they often run into permission/access problems).

### PR DESCRIPTION
**Pull request by GTFalcao**
### <samp>🤖 Generated by Copilot at 0718161</samp>

Added new features and updated versions for several Twitter actions. The new features include working with direct messages, adding media attachments, using IDs or usernames, and including metrics fields. The updated versions reflect the changes in the `components/twitter/actions` and `components/twitter/app` modules. The `dataFields.ts` module was also modified to support the new features.

### <samp>🤖 Generated by Copilot at 0718161</samp>

> _The `twitter.app` got a big update_
> _With new features that users will rate_
> _You can search, like, and list_
> _Send a DM with a twist_
> _And add metrics to tweets that you create_

## WHY

Closes #6717 

### <samp>🤖 Generated by Copilot at 0718161</samp>

*  Added a new action to send direct messages to users by their ID or username ([link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-60acdc25c55da72f168282cdb4dc45c913e3a95387eab159979cc506207479b5R1-R61), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edL30-R34), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edR419-R428))
*  Added a new feature to get direct messages for the authenticated user or a specified user ([link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-f2fe2648f68d08d6125d3972795e6d4835041e50e5ce39922aaf9dad75b874edR310-R317))
*  Added a new feature to include metrics fields in the output of actions that deal with tweets and users ([link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-22ad073362230c6ef936a13dc199cf4b4b88e720994d5421d354db7867eec448L17-R17), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-b22431a2983f4381d8c29acdcd07c1fe6f16c1799d98c1e0b5cabd15954ca138L19-R19), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-7d029cc64219e684390458a835af83104668013ff3cc7cfcf8dce99eeef31ef0L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-caa82d0d011e6f177dc09c4c5cc69c182722e4929c0e8de3618583e5142ec8a1L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-84c8ea84740ba6e8d1ad13fd0cdb10115427653dcf4a2b045182601f2392042bL25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-ca7ec28532456081821322789d07de1c870604446bec4c221ad85819e729dfe2L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-78a92d41eefa32c18e6e80c03f9380e469724ff41be87df2f4a1fff02e011ae1L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-71cca0daeb5bf93f2be0877800f84dbcd1b6b0884c12b271e9ad9815f2b694afL23-R23), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-dff93efe266cb2dd1487da3887ea4d60c2418a23e962630709f758f457f7a76eL23-R23), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-af034d1608f2c8693a723edceb1bd11b4bd5be35c6194d0ce293889d24dcf4ffR26-R44))
*  Added a new feature to add, delete, follow, unfollow, like, and unlike users and tweets by their ID or URL, instead of only by their ID ([link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-a1373002f650102c864faeb7867284cd8b901a8cf865ed6e7b654958df53aa16L14-R14), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-7543f426e5e255aa709eb2c6599f0ee89c136e66626adba0a6e9a57a024e295cL13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-5b44f84f0867bd6cb1f0d76ab64caec5f4daaee80423bef35e8c359da76a8249L14-R14), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-61d66d6c6e6f0a5a272264dd566294458192dbb80d351b0638c2999956f9390cL13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-5012fedc91f1e75b5af995fa1ac982521179a0d66446987b7944ae4088b27f39L13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-ad0d3ba8c281113c8c09357e87eb3d597fcc05840e50465389cb81453ee62d35L14-R14), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-be62489d0d1799a066d819c74bc784f5367fc76cdc00cd34c925ea804f5a8b0dL13-R13))
*  Updated the versions of the existing actions to reflect the new features ([link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-72dac938c50aed338983c96a539e0386942f91f51ef47097936ac37bb7e47bfdL13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-22ad073362230c6ef936a13dc199cf4b4b88e720994d5421d354db7867eec448L17-R17), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-b22431a2983f4381d8c29acdcd07c1fe6f16c1799d98c1e0b5cabd15954ca138L19-R19), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-7d029cc64219e684390458a835af83104668013ff3cc7cfcf8dce99eeef31ef0L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-caa82d0d011e6f177dc09c4c5cc69c182722e4929c0e8de3618583e5142ec8a1L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-84c8ea84740ba6e8d1ad13fd0cdb10115427653dcf4a2b045182601f2392042bL25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-ca7ec28532456081821322789d07de1c870604446bec4c221ad85819e729dfe2L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-78a92d41eefa32c18e6e80c03f9380e469724ff41be87df2f4a1fff02e011ae1L25-R25), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-5012fedc91f1e75b5af995fa1ac982521179a0d66446987b7944ae4088b27f39L13-R13), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-71cca0daeb5bf93f2be0877800f84dbcd1b6b0884c12b271e9ad9815f2b694afL23-R23), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-dff93efe266cb2dd1487da3887ea4d60c2418a23e962630709f758f457f7a76eL23-R23), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-ad0d3ba8c281113c8c09357e87eb3d597fcc05840e50465389cb81453ee62d35L14-R14), [link](https://github.com/PipedreamHQ/pipedream/pull/6754/files?diff=unified&w=0#diff-be62489d0d1799a066d819c74bc784f5367fc76cdc00cd34c925ea804f5a8b0dL13-R13))

### CODE REVIEW

**Review by vellames — CHANGES_REQUESTED** [review]
Hi there. instead of `See the docs`. Could you please use `See the documentation`? We are preferring using this pattern now.

**Comment by vellames** [comment]
Also, pipeline is failing

**Comment by GTFalcao** [comment]
Thanks for the heads up @vellames , updated the "see the docs" descriptions.

As for the check that's failing, it's erroring out on a file that was removed, there's no content to be fixed there - I think we can ignore this

**Comment by vellames** [comment]
Ok :)

**Review by vellames — APPROVED** [review]

**Comment by vunguyenhung** [comment]
Hi @GTFalcao, as this file has a lot of conflicts around. Would you mind resolving them before I test? Thanks

**Comment by GTFalcao** [comment]
@vunguyenhung I'll sort them out right now, but they are just version numbers which we had to update earlier today on the live components, so no code will be changed.

**Review by vellames — DISMISSED** [review]
lgtm

**Comment by vellames** [comment]
We just need to check pipelines problems

**Review by vellames — APPROVED** [review]

**Review by vellames — CHANGES_REQUESTED** [review]
Failing in pipeline :(

**Review by vellames — APPROVED** [review]

**Pull request merged**
