### PR TITLE
Fix zoho crm source bug fixes renaming for readability

### PR DESCRIPTION
**Pull request by jcortes**
This PR was created in order to close #1911 authored by @celestebancos

### CODE REVIEW

**Comment by vellames-turing** [comment]
@jcortes There is no file changed here

**Comment by jcortes** [comment]
> @jcortes There is no file changed here

Hi @vellames-turing this PR was created only to fix conflict issues since I'm not the owner of #1911

**Review by vellames-turing — APPROVED** [review]
Ok, tks!

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by dannyroosevelt** [comment]
> This is ready for release!

@jcortes can you please merge?

**Pull request merged**
