### PR TITLE
[New Component] Gistly YouTube Transcript API

### PR DESCRIPTION
**Pull request by rafalzawadzki**
## WHY

Just adding a useful API for fetching YouTube transcripts.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Gistly API for fetching transcripts from YouTube videos.
	- Added functionality to specify video details and desired transcript formats.
	- Enhanced support for bulk requests and time-stamped transcripts.

- **Documentation**
	- Added a comprehensive README file detailing API usage and parameters.

- **Version Updates**
	- Updated package version from 0.0.1 to 0.1.0 and added new dependencies.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by rafalzawadzki** [comment]
@jcortes sure, should be good now!

**Comment by rafalzawadzki** [comment]
@vunguyenhung thanks for reviewing it! Looks like indeed there was a duplicated method (merge error, perhaps?). I fix the dupe.

**Comment by malexanderlim** [comment]
Hi @rafalzawadzki , thank you for contributing here. New apps actually must be added by the Pipedream team; @sergio-eliot-rodriguez will integrate the base app and then you can submit the components that you built afterwards.

**Comment by sergio-eliot-rodriguez** [comment]
Gistly now integrated https://pipedream.com/apps/gistly

**Comment by malexanderlim** [comment]
@rafalzawadzki can you add your components on top of the base code that is currently in master for the app? @sergio-eliot-rodriguez from our team added the base integration, and you can now contribute your component now that the base integration has been shipped.

**Comment by rafalzawadzki** [comment]
@malexanderlim wasn't sure if you meant a rebase or a merge or something else, but I merged master to get my branch up to date :) hopefully got it right!

**Pull request merged**
