### PR TITLE
[ACTIONS/SOURCES] Zoho Projects new actions and sources

### PR DESCRIPTION
**Pull request by jcortes**
# Actions
- [x] Create Bug | Creates a bug. [See the docs here](https://www.zoho.com/projects/help/rest-api/bugs-api.html#alink3)
- [x] Create Milestone | Creates a milestone. [See the docs here](https://www.zoho.com/projects/help/rest-api/milestones-api.html#alink3)
- [x] Create Project | Creates a project. [See the docs here](https://www.zoho.com/projects/help/rest-api/projects-api.html#alink5)
- [x] Create Task | Creates a task. [See the docs here](https://www.zoho.com/projects/help/rest-api/tasks-api.html#alink4)
- [x] Create Task List | Creates a task list. [See the docs here](https://www.zoho.com/projects/help/rest-api/tasklists-api.html#alink2)
- [x] Update Project | Updates a project. [See the docs here](https://www.zoho.com/projects/help/rest-api/projects-api.html#alink6) (There is an API limitation when I tried to update the status to `archived` of the project returning `{"code":6403,"message":"License does not allow further operations"}`)
- [x] Find Project | Lists the modules across the portal based on the search term. The API returns both active and archived projects for the users having admin privileges. [See the docs here](https://www.zoho.com/projects/help/rest-api/search-api.html#alink1)
- [x] ~Add Log Time | Add Time for a General Log. Adds the time log to other tasks. [See the docs here](https://www.zoho.com/projects/help/rest-api/log-time.html#alink11)~ (It returns this error in the response `You cannot access Timelogs in your current plan. Upgrade to Premium to unlock Timelogs.`)
- [x] Upload File | Uploads a document to the project. [See the docs here](https://www.zoho.com/projects/help/rest-api/documents-api.html#alink4)

# Sources
- [x] New Bug | Emit new event when a new bug is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/bugs-api.html#alink1)
- [x] New Milestone | Emit new event when a new milestone is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/milestones-api.html#alink1)
- [x] New Project | Emit new event when a new project is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/projects-api.html#alink1)
- [x] New Task | Emit new event when a new task is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/tasks-api.html#alink1)
- [x] New Task List | Emit new event when a task list is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/tasklists-api.html#alink1)
- [x] ~New Log Time | Emit new event when a log time is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/log-time.html#alink1)~ (It returns this error in the response `You cannot access Timelogs in your current plan. Upgrade to Premium to unlock Timelogs.`)
- [ ] ~New File | Emit new event when a new file is created. [See the docs here](https://www.zoho.com/projects/help/rest-api/documents-api.html#alink1)~ According to last email sent by support team, there is no Zoho Projects endpoint to get a list of files created in this platform but in Zoho WorkDrive. So my suggestion is to create another source component in Zoho WorkDrive app where we can listen for these new files being created

# Email 1
```
Hello Jorge,

Thank you for your patience.

Upon checking with our development team, you are availing WorkDrive and the following v3 API's were suggested:

Create/Upload a Folder and Upload file(s):

URL - https://projectsapi.zoho.{com/eu/in}/api/v3/portal/{portal_id}/documents/thirdparty/files/{thirdpartyfolder_id}
Method - POST
Scope: ZohoProjects.documents.CREATE, WorkDrive.workspace.ALL, WorkDrive.files.ALL
Params:
service - workdrive
folder_name - (optional)
folder_include_files - (optional) (boolean - true/false) --If true, the new folder will become the parent folder for the files instead of the one in the URL--
upload_file - can upload 10 files in a request.

Get Associated Team Folder(s):

URL - https://projectsapi.zoho.{com/eu/in}/api/v3/portal/{portal_id}/projects/{project_id}/folders
Method - GET
Scope: ZohoProjects.documents.READ, WorkDrive.team.ALL, WorkDrive.workspace.ALL, WorkDrive.files.ALL

Kindly check by using the API's provided above and check if there is a response for the API call used.

Please reach us back if there are any concerns, so that we can check and assist you further.

Regards,
Fredrick.
```

# Email 2
```
Hello Jorge,

Thank you for your patience.

Our developers have suggested the following documentations, with regards to your request for sample responses to the previously provided v3 API's:

To upload a file: 
https://workdrive.zoho.com/apidocs/v1/filesfolders/uploadfile

For creating a folder:
https://workdrive.zoho.com/apidocs/v1/folders/createfolder

To Get Team Folder info:
https://workdrive.zoho.com/apidocs/v1/teamfolder/getteamfoldersinfo 

Hope this helps. Email us if you have any queries in future, we will be glad to help you.

Regards,
Fredrick.
```

# Email 3
```
Hello Jorge,

My sincere apologies for the very delayed response.

To know more about API endpoint to get the file/ folder info, access the help link provided below:

https://workdrive.zoho.com/apidocs/v1/filesfolders/fileinfo

To get all the files and folders from a team folder, access the help link provided below:

https://workdrive.zoho.com/apidocs/v1/teamfolder/getteamfolderfiles

Hope this helps.

Regards,
Fredrick.
```

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4098"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by michelle0927 — CHANGES_REQUESTED** [review]
Looks great. Just a couple tiny things - a stray console.log, and can we add a package.json file?

**Review by michelle0927 — APPROVED** [review]
LGTM! Ready for QA.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Zoho_Projects_4098.pdf](https://github.com/PipedreamHQ/pipedream/files/9566531/Zoho_Projects_4098.pdf)

**Pull request merged**
