### PR TITLE
Source - Bitbucket - Multiple Pipeline events

### LINKED ISSUE #5114: [TRIGGER] - BitBucket Pipeline Event (multiple repositories)
The availability to select multiple repositories within the New **Pipeline Event (Instant)** so that the user does not have to create multiple triggers for when they want to get notifications from pipelines that are used by multiple repositories.

### PR DESCRIPTION
**Pull request by vellames**
Closes #5114

### CODE REVIEW

**Review by andrewjschuang — COMMENTED** [review]
LGTM! Though you'll have to fix the errors in the checks.

**Comment by vellames** [comment]
I have no idea why this is not passing. The branch is up to date with main

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Bitbucket_5353_2112.pdf](https://github.com/PipedreamHQ/pipedream/files/10557825/Bitbucket_5353_2112.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Bitbucket_5353_2100.pdf](https://github.com/PipedreamHQ/pipedream/files/10579506/Bitbucket_5353_2100.pdf)

**Review by andrewjschuang — APPROVED** [review]

**Pull request merged**
