### PR TITLE
Fix some users in Slack User & Channel props listed as "Undefined" in async options

### LINKED ISSUE #2378: [BUG] Some users in Slack User prop listed as "Undefined" in async options
image

### PR DESCRIPTION
**Pull request by js07**
**Changes**
- Fixes undefined user names in some options for the **User** (`user`) prop and **Channel** (`conversations`) prop
- Fixes the `conversation` prop in Slack **Send Group Message** action. The prop incorrectly inherited the `user` prop definition instead of  `group` prop definition from the app file.
- Refactors & removes unused code from async options for props: `publicChannel`, `privateChannel`, `user`, `group`, `conversation`
- Bumps the patch version of all Slack components

**Affected components**
- by fix to `user` prop:
`create-reminder`, `invite-user-to-channel`, `kick-user`, `list-files`, `send-direct-message`
- by fix to `conversations` prop:
`add-star`, `archive-channel`, `delete-message`, `delete-file`, `delete_reminder`, `get-channel`, `invite-user-to-channel`, `join-channel`, `kick-user`, `leave-channel`, `list-files`, `list-members-in-channel`, `list-replies`, `remove-star`, `send-block-kit-message`, `send-custom-message`, `send-direct-message`, `set-channel-topic`, `set-purpose-of-channel`, `unarchive-channel`, `update-message`, `upload-file`, `new-message-in-channels`
- by refactor of `publicChannel`, `privateChannel`, and `group` props:
`send-group-message`, `send-message-private-channel`, `send-message-public-channel`

**Context**
Only the first page of users was being fetched in async options methods for the Slack `user` and `conversations` props. The fetched users are used to determine the user name that corresponds to a direct message. So only direct messages to -users in the first page of users- were labeled with the correct user name.

This commit changes the async options methods to create a mapping (<user ID> -> <user name>) for _all_ users in the workspace.

Fixes #2378

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by andrewjschuang — APPROVED** [review]
Thanks @js07 for these fixes! Looks good to me!
Good job in refactoring and removing unused code too

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, in order for me to verify this PR could you resolve all conflicts?

**Comment by js07** [comment]
Thanks for testing the PR @vunguyenhung. I fixed the Slack **Add Star** action, which was using the wrong name for the `channel` argument.

For the **Send Group Message** action, this PR changes the group prop. The group prop's options dropdown is correctly displaying groups for me, so I don't think you need to check that the action runs successfully.

**Comment by vunguyenhung** [comment]
Thanks @js07, I've skipped the **Send Group Message** and all test cases are passed! Ready for release! 

Test report
[Slack_2378_2015.pdf](https://github.com/PipedreamHQ/pipedream/files/8754804/Slack_2378_2015.pdf)

**Review by vellames-turing — APPROVED** [review]

**Pull request merged**
