### PR TITLE
Airtable Create & Update Record actions - Column names as distinct props

### PR DESCRIPTION
**Pull request by js07**
- Updates Airtable **Create Single Record** & **Update Record** actions to use a table's column names as distinct prop fields
- Converts Airtable components to ESM and fixes linter errors
- Adds $summary to Airtable actions
- Replaces deprecated `$.airtable` prop types with string props with async options, using special airtable app prop methods (`.table`, `.tables`, `.bases`)

To add a column names as props, the actions use the airtable app prop's `.table()` method in the `additionalProps`. `.table`'s return value is an Airtable table schema, which includes an array of fields (i.e., columns).

Part of #2536

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by dannyroosevelt** [comment]
@js07 What is the value we're shwoing here? Is this the JSON of the table itself? Is there any slightly more user-friendly value we could display here? Not a big deal if not, just looks confusing IMO.
image

**Comment by dannyroosevelt** [comment]
@js07 can you add a `$summary` message similar to the GSheets Add Single Row action? 
image

**Comment by dannyroosevelt** [comment]
@js07 is the `create-single-record` action the only one that got updated w/ the new `$.airtable.table` prop? Can we also refactor some of the other actions (especially the `create-multiple-records` action)?

**Comment by js07** [comment]
> @js07 What is the value we're shwoing here? Is this the JSON of the table itself? Is there any slightly more user-friendly value we could display here? Not a big deal if not, just looks confusing IMO.

Yes, this is the JSON of the table schema. We could do something like base64 encode it in the API and decode it in the component, so it appears as a base64 string (e.g. `YXdwb2VmdWkgYXdlanFpb2pvaWZqYXdmaXEyamYwYW8gc2RqZmFsO2tzZGogZmFqZW93aWpmIGE5O3dqIDRhdyA4OTNqMnE4OWFqIGZhOTgyaiBmOTg0cTJqIGE5OGozZjRqOThhajI5YWogOThqZmE5ODJqNDkyYTkzODI0amE5OGY=`)

**Comment by js07** [comment]
> @js07 is the `create-single-record` action the only one that got updated w/ the new `$.airtable.table` prop? Can we also refactor some of the other actions (especially the `create-multiple-records` action)?

The `create-single-record` and `update-record` actions got updated with the new `$.airtable.table` prop.

Refactor the `create-multiple-records` action to add column name props in `additionalProps`?

**Comment by dannyroosevelt** [comment]
> > @js07 What is the value we're shwoing here? Is this the JSON of the table itself? Is there any slightly more user-friendly value we could display here? Not a big deal if not, just looks confusing IMO.
> 
> Yes, this is the JSON of the table schema. We could do something like base64 encode it in the API and decode it in the component, so it appears as a base64 string (e.g. `YXdwb2VmdWkgYXdlanFpb2pvaWZqYXdmaXEyamYwYW8gc2RqZmFsO2tzZGogZmFqZW93aWpmIGE5O3dqIDRhdyA4OTNqMnE4OWFqIGZhOTgyaiBmOTg0cTJqIGE5OGozZjRqOThhajI5YWogOThqZmE5ODJqNDkyYTkzODI0amE5OGY=`)

No need, we just typically show an ID or something similar as the value, so the JSON was surprising, but that's fine.

**Review by vellames-turing — APPROVED** [review]

**Comment by vellames-turing** [comment]
@js07 We have one conflict here

**Review by andrewjschuang — APPROVED** [review]
@js07 thanks for the submission! LGTM for QA!

Would it be better to create auxiliary methods and/or separate into smaller blocks to make the summary exports more readable?

**Comment by vunguyenhung** [comment]
Hi everyone, I have tested the changes in this PR and they're all good! The actions having columns as prop fields are:
- Create Single Record
- Update Record

Test report
[AirTable_PR_2600.pdf](https://github.com/PipedreamHQ/pipedream/files/8740516/AirTable_PR_2600.pdf)

Though @dannyroosevelt, could you confirm if those 2 actions are enough for closing the related issue? I see there's another action Create Multiple Records that doesn't have columns as prop fields improvement, but I suspect that Pipedream Action UI could support it. What do you think?

**Comment by dannyroosevelt** [comment]
These are great changes! Nice job @js07!

The only request I'd ask for is that we `throw new ConfigurationError` when we cannot fetch either a manually referenced Base ID or Table ID ([links to docs)](https://pipedream.com/docs/code/nodejs/#configuration-error).

@js07 do you want to implement, or should we hand that off to another dev?

**Comment by js07** [comment]
@dannyroosevelt Should we `throw new ConfigurationError` when we cannot fetch a Base ID or Table ID when configuring _and_ when running the action? I.e., in the `additionalProps` and `run` methods?

**Comment by js07** [comment]
@dannyroosevelt Thanks for the feedback. I made a couple changes and have a few questions.
- Updated the `async options` methods for the **Table**, **View**, and **Sort: Field** props to throw a `ConfigurationError` when tables, views, or fields are not found using the specified **Base** ID or **Table** ID.
- Updated the `additionalProps` methods for **Create Single Record** and **Update Record** to throw a `ConfigurationError` when a table (schema) is not found for the specified **Table** ID.

#### ConfigurationError in `async options`
delete-record-options-error

Would we prefer to show an empty list of options here instead of an error here (image above)? In the case where a user references an exported value from a previous step, we also show an error here:

delete-record-export-config-error

---

#### ConfigurationError in `additionalProps`

create-single-record-config-error-2

---

If we make an Airtable API request in the `run` method using a **Base** ID or **Table** ID that's not found, we currently display the error from Airtable in this format:

list-records-not-found

Would we prefer to show a ConfigurationError with a "not found" message instead?

**Comment by js07** [comment]
If the **Base** ID and **Table** ID inputs are specified using an expression (e.g., `{{steps.code.$return_value.baseId}}`, additional props aren't generated (because the action doesn't know what the values will be at runtime).

airtable-create-single-record-config-error

Do we want to support dynamic **Base** ID and **Table** ID inputs (i.e., referenced step exports) in the **Create Single Record** action–like the prod actions do–using an **Record** `object` prop?

airtable-create-single-record-old

**Comment by dannyroosevelt** [comment]
@js07 I just threw some time on our calendars to chat about these open questions tomorrow so we can hopefully nail down answers asap.

**Comment by js07** [comment]
@dannyroosevelt I made these changes:
- Updated the descriptions of the **Table**, **View**, and **Sort: Field** props to suggest entering a custom expression if the prior prop references dynamic data from a previous step (https://github.com/PipedreamHQ/pipedream/pull/2600/commits/2b037da6745d41ccc818c53ff5cfd074971776ea, https://github.com/PipedreamHQ/pipedream/pull/2600/commits/21adaddb54505ff733371277a3347e94d3e439c7).
- Changed **Create Single Record** and **Update Single Record** actions to add a **Record** field instead of column name fields when a table is not found in `additionalProps` *and* the **Table** prop is set manually (i.e., could be dynamic) (https://github.com/PipedreamHQ/pipedream/pull/2600/commits/b13ef2557f3e559be2b0d76692fff783eb69c0d0)

Do the descriptions for **Table**, **View**, and **Sort: Field** need any changes?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt I made these changes:
> 
> * Updated the descriptions of the **Table**, **View**, and **Sort: Field** props to suggest entering a custom expression if the previous prop input references dynamic data from a previous step ([2b037da](https://github.com/PipedreamHQ/pipedream/commit/2b037da6745d41ccc818c53ff5cfd074971776ea), [21adadd](https://github.com/PipedreamHQ/pipedream/commit/21adaddb54505ff733371277a3347e94d3e439c7))
> * Changed **Create Single Record** and **Update Record** actions to add a **Record** field instead of column name fields when a table is not found in `additionalProps` _and_ the **Table** prop is set manually (i.e., could be dynamic) ([b13ef25](https://github.com/PipedreamHQ/pipedream/commit/b13ef2557f3e559be2b0d76692fff783eb69c0d0))
> 
> Do the descriptions for **Table**, **View**, and **Sort: Field** need any changes?

The last suggestion I'd make is to include an example in the description for the `record` prop. Then let's ship it! Since it's gone through PR review and QA I'm good to publish straightaway if you are.

**Pull request merged**
