### PR TITLE
[BUG] pCloud Watch Folder trigger does not pick up events

### LINKED ISSUE #4136: [BUG] pCloud Watch Folder trigger does not pick up events
From a user report:
> - Folder list sometimes populates, sometimes doesn't (stuck with spinner)
> - Even if I manage to pick a folder, the "Try now" button doesn't work, the "Waiting for events" spinner spins ad infinitum...

2 potential issues to verify:
1. Folder prop potentially not working consistently
2. The Watch Folder source not picking up events

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #4136

The `created` and `modified` file dates from pCloud do not represent dates that the file was uploaded or modified within pCloud, but the original creation/modification dates of the file being uploaded.

I updated the component to dedupe on `fileid` to find newly created files, and `hash` [(64 bit integer representing hash of the contents of the file can be used to determine if two files are the same or to monitor file contents for changes)](https://docs.pcloud.com/structures/metadata.html) to find modified files.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4167"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by jcortes — APPROVED** [review]
HI @michelle0927 LGTM! Ready for QA!

**Comment by DilanAthukorala** [comment]
@michelle0927 

1. After I synced the created files, I changed the settings to receive "Modified" files. Then the files which were not modified synced again. (Those file were already received as create events)

2. And when I change file names in pCloud they were not synced to Pipedream as modified file events.

**Comment by michelle0927** [comment]
> @michelle0927
> 
> 1. After I synced the created files, I changed the settings to receive "Modified" files. Then the files which were not modified synced again. (Those file were already received as create events)

This happens because the component is deduping by `fileid` for new files, but by `hash` for modified files. Sources/triggers use various ways of determining what is a new event, so changing the configuration of any Pipedream source is likely to produce unexpected results. For sources, you'll want to deploy them with the configuration you want. To try different configurations, it's best to deploy multiple sources.

> 2. And when I change file names in pCloud they were not synced to Pipedream as modified file events.

That's correct. Events will be emitted when there is a change to the file contents.

**Comment by DilanAthukorala** [comment]
> > @michelle0927
> > 
> > 1. After I synced the created files, I changed the settings to receive "Modified" files. Then the files which were not modified synced again. (Those file were already received as create events)
> 
> This happens because the component is deduping by `fileid` for new files, but by `hash` for modified files. Sources/triggers use various ways of determining what is a new event, so changing the configuration of any Pipedream source is likely to produce unexpected results. For sources, you'll want to deploy them with the configuration you want. To try different configurations, it's best to deploy multiple sources.
> 
> > 2. And when I change file names in pCloud they were not synced to Pipedream as modified file events.
> 
> That's correct. Events will be emitted when there is a change to the file contents.

@michelle0927 Ok Noted. Thanks for the explanation.

**Comment by DilanAthukorala** [comment]
Verification completed and ready for release.

**Pull request merged**
