### PR TITLE
Provide reply_to property to $.send.email() (#2158)

### PR DESCRIPTION
**Pull request by eric-brechemier**

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by dylburger** [comment]
@eric-brechemier This is awesome! But a custom `Reply-To` header isn't yet supported in our `$.send.email` service. Were you implementing a mock PR to show us the API you'd like to see for this feature?

**Comment by eric-brechemier** [comment]
@dylburger Let's say it's a first step in the right direction ;) I did look for the source of `$.send.email()` but have not found it yet… Is this part of your private implementation of the platform?

I went as far as the [platform project](https://github.com/PipedreamHQ/platform/pull/29) but only found type definitions there.

**Comment by dylburger** [comment]
Great thanks. Yes, `$.send.email` is part of our private, production platform. We're in the middle of some work to improve it, which covers sending email to any address (within some basic limits), setting a custom `Reply-To`, etc. We'll update that issue when we make this available.

Since the implementation of that may not use `$.send.email`, are you OK if I close this PR for now? We use this list as a part of our backlog, and since there isn't any action for us to take on this PR, I'd like to move it into a different state. If we end up making more of the code for `$.send.email` public, etc., we can always re-open in the future.

**Comment by eric-brechemier** [comment]
@dylburger Thank you for the clarification. I am looking forward to seeing these improvements to the email_me task. With regards to allowing more destination email addresses, here is my feedback: I used a specific email address when I created my pipedream account and I did not expect to be restricted to that particular email address for notifications to myself. I would rather use a different email address (I have my own domain) for separate workflows to allow filtering in my email client. I would currently need to create a separate account for each of these destinations, which I was planning to do, part of a common organization. In short, the current behavior is not blocking for my use case, but would need to be clarified at sign-up: the email address that you are using is the one where you will receive email notifications.

> Since the implementation of that may not use `$.send.email`, are you OK if I close this PR for now?

Sure, as long as you keep the original issue open, feel free to close my PRs.

**Comment by dylburger** [comment]
Great thanks! All of that makes sense and ideally would be clarified / covered under the new model.

**Pull request closed without merging**
