### PR TITLE
[BUG] Dropbox sources are not working as expected

### LINKED ISSUE #4383: [BUG] Dropbox sources are not working as expected
**Describe the bug**

Existing Dropbox sources and not functioning properly as described below;

1. "New File" & "New Folder"  sources not emitting events to the Events tab. However the logs shows the new files/folders that has been created / uplodaed
image
Logs are recorded for events
image

2. "New or Modified File or Folder" source doesn't show the id/description of emitted events 
image

**To Reproduce**

1. Access Pipedream UI > Sources
2. Create a new Dropbox: New file source
3. Connect with your Dropbox account, connect to a Folder, set Recursive = false; Include Media Info = false; Include Link = false. Then enable the Source

**Expected behavior**
All events should be emitted for each file/folder with correct Id/description

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [Version 105.0.5195.127 (Official Build) (64-bit)]

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #4383 

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4400"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by feyzullah — APPROVED** [review]
LGTM

**Comment by DilanAthukorala** [comment]
Hi @michelle0927, I'm observing an issue in "New or Modified File/Folder" source where if we emit a New Folder event then Update folder events are not emitted. Before emitting the new folder event update folder events are emitted successfully.  I have replicated this couple of times with following steps: 

1. Create "New or Modified File/Folder" source
2. Emit Update events for existing folders
3. Create New Folder
4. Again try to emit update folder events - No events are emitted.

**Comment by michelle0927** [comment]
> Hi @michelle0927, I'm observing an issue in "New or Modified File/Folder" source where if we emit a New Folder event then Update folder events are not emitted. Before emitting the new folder event update folder events are emitted successfully. I have replicated this couple of times with following steps:
> 
> 1. Create "New or Modified File/Folder" source
> 2. Emit Update events for existing folders
> 3. Create New Folder
> 4. Again try to emit update folder events - No events are emitted.

@DilanAthukorala Good catch. This was due to deduping on `file.rev` which only exists for files, but not folders. I made an update, and I believe it should be working properly now.

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release.

**Review by feyzullah — APPROVED** [review]

**Pull request merged**
