### PR TITLE
[Source] SavvyCal - New Webhook Event

### LINKED ISSUE #5744: [APP][TRIGGER] SavvyCal integration, New SavvyCal triggers
**Name of app / service**
SavvyCal

**Link to developer documentation**
https://savvycal.com/docs/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Have a workaround - SavvyCal posts to a webhook just fine. 

But the problem is it posts to a webhook for EVERY event type. So for example, I might have event.requested then event.confirmed then event.created then workflow.triggered.action all posting to the same webhook - this uses 4 invocations, but the first step I would do would be to filter to only use some event types. My workflow might only do something for one of those event types, so that's 4x as many invocations as I would like to actually use.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I want a trigger to be a new thing happening in SavvyCal. There are 8 event types so I'd like the trigger to filter by event type: 

- [event.created](https://savvycal.com/docs/api/webhooks/payloads/#event.created)
- [event.requested](https://savvycal.com/docs/api/webhooks/payloads/#event.requested)
- [event.approved](https://savvycal.com/docs/api/webhooks/payloads/#event.approved)
- [event.declined](https://savvycal.com/docs/api/webhooks/payloads/#event.declined)
- [event.rescheduled](https://savvycal.com/docs/api/webhooks/payloads/#event.rescheduled)
- [event.canceled](https://savvycal.com/docs/api/webhooks/payloads/#event.canceled)
- [poll.response.created](https://savvycal.com/docs/api/webhooks/payloads/#poll.response.created)
- [workflow.action.triggered](https://savvycal.com/docs/api/webhooks/payloads/#workflow.action.triggered)

And ideally by linkID.

So ideally:

1. What SavvyCal account?
2. What type(s) of event?
3. What link(s), or any link?

### PR DESCRIPTION
**Pull request by vellames**
Closes #5744

### CODE REVIEW

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[SavvyCal_5744_2312.pdf](https://github.com/PipedreamHQ/pipedream/files/11042195/SavvyCal_5744_2312.pdf)

**Comment by acreconsulting** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information [SavvyCal_5744_2319.pdf](https://github.com/PipedreamHQ/pipedream/files/11053209/SavvyCal_5744_2319.pdf)

Hey as a SavvyCal user and the one who originally requested, I thought I'd chime in. So in the test report, none of the "Webhook event types" (i.e. event.created, event.requested, etc.) were actually triggered in your test run, so I would not expect them to trigger. So it doesn't look like a fail to me.

Here's my instructions:
1. First set up a scheduling link. [DONE] For example, "Meeting with Hung"
2. Then, use the URL that was created for that scheduling link. Schedule a meeting. **This triggers the event.created webhook event type**
3. Cancel the meeting. **This triggers the event.cancelled webhook event type**
4. Create a second scheduling link. Change the Settings for this link to "Require approval from the organizer" (under Post-Booking Behavior).
5. Then, use the URL for that second scheduling link, and schedule a meeting. **This triggers the event.requested webhook event type**
6. The organizer needs to approve the meeting request. **This triggers the event.approved and also event.created webhook event types**
7. Repeat step 4. Then, the organizer needs to decline the meeting request. **This triggers the event.declined webhook event type**
8. Create a meeting poll. [DONE] For example, "Pipedream 2259."
9. Then, use the URL that was created for the meeting poll. Fill out the poll. **This triggers the poll.response.created webhook event type**

**Comment by acreconsulting** [comment]
The final webhook event type is **workflow.action.triggered**. This is a bit harder to trigger, but here's the easiest way:

1. Set up a scheduling link. 
2. Under Settings for that link, under Workflows, click on Attach a Workflow then Create a Workflow. 
3. On the next screen, select "Start from scratch"
4. At the top of the next screen, select "Add an action..." and in the popup,
5. "What action should we perform" is "Send a webhook"
6. "When should we perform this" is "After event scheduled"
7. "How long after" is 0 minutes
8. Add action
9. In the top left, it probably says "Paused" - let's make this Workflow live
10. Go back to the URL for the scheduling link you created in step 1. Schedule an event using this link. **This should trigger both event.created and workflow.action.triggered.**

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[SavvyCal_5744_1732.pdf](https://github.com/PipedreamHQ/pipedream/files/11077536/SavvyCal_5744_1732.pdf)

**Pull request merged**
