### PR TITLE
Shopify - Shopify - add metafields prop to actions

### LINKED ISSUE #5521: [IMPROVEMENT] Shopify - add metafields prop to Update Product & Update Customer actions
Add the ability to update a product's, product variant's, or customer's metafields.
Product - https://shopify.dev/docs/api/admin-rest/2023-01/resources/product#put-products-product-id
Customer - https://shopify.dev/docs/api/admin-rest/2023-01/resources/customer#put-customers-customer-id
Product Variant - https://shopify.dev/docs/api/admin-rest/2023-01/resources/product-variant#put-variants-variant-id

See [Slack conversation](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1676761636892709) and [previous PR](https://github.com/PipedreamHQ/pipedream/pull/5475) for reference.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #5521

### CODE REVIEW

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Shopify_5531_1023.pdf](https://github.com/PipedreamHQ/pipedream/files/10799749/Shopify_5531_1023.pdf)

**Comment by vunguyenhung** [comment]
Hello @michelle0927, I have also created another ticket to improve the Get metafields action: https://github.com/PipedreamHQ/pipedream/issues/5543. Please check it also if you can. 

Thank you!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Shopify_5531_2338.pdf](https://github.com/PipedreamHQ/pipedream/files/10806271/Shopify_5531_2338.pdf)

**Review by lcaresia — APPROVED** [review]

**Comment by zecul** [comment]
I think I found a small bug here. I'm not sure if its a real bug or if its just bad practise on my part.

I have 2 metafields named
product.metafields.labels.name
product.metafields.artists.name

The update metafields action is getting confused between the 2 (because they have the same key I assume) even though they have a different namespace.

when I write the update input as:

{{ [{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Label), "type":"list.single_line_text_field", "namespace": "labels" },
{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Artist), "type":"list.single_line_text_field", "namespace": "artists" }] }}

the product.metafields.labels.name field will *sometimes* be filled with the product.metafields.artists.name data

If I do the reverse and write {{ [{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Artist), "type":"list.single_line_text_field", "namespace": "artists" },{"key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Label), "type":"list.single_line_text_field", "namespace": "labels" }] }}
then the product.metafields.artists.name field will *sometimes* be filled with the product.metafields.labels.name data.

image

I find it hard to replicate this error everytime so I dont know if its somewhat luck based/random. I'm only 80% sure its not somre sort of typo/error in my coding but I've checked and reworked it quite a few times and it works fine almost all of the time except every now and again throws up the error mentioned. I should probably just rename them, but I thought it was worth mentioning in case either I'm doing something wrong or the code isn't checking the namespace properly (or early enough).

**Pull request merged**
