### PR TITLE
Leap - New Components

### LINKED ISSUE #6124: [Components] Leap
### App
Leap
https://www.tryleap.ai/

Triggers:
1. Form Submitted: Triggered when a new form response is received.
2. Task Completed: Activated when a task is marked as done.

Actions:
1. Create Task: Generates a new task in the Leap platform.
2. Update Task: Modifies an existing task's information.
3. Add Collaborator: Invites a team member to collaborate on a project or task.

_This list of suggested components was generated using ChatGPT_

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #6124 

**Triggers**

- New Model Created
- New Image Sample Created
- New Model Version Created

**Actions**

- Create Model
- Create Image Samples
- Create Image Generation Job

### CODE REVIEW

**Review by alysonturing — APPROVED** [review]
LGTM! Thank you for your valuable contribution!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Leap_6124_1436.pdf](https://github.com/PipedreamHQ/pipedream/files/11411787/Leap_6124_1436.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Leap_6124_1025.pdf](https://github.com/PipedreamHQ/pipedream/files/11426928/Leap_6124_1025.pdf)

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
