### PR TITLE
Include package.json version on PR check

### LINKED ISSUE #4103: [BUG] @pipedream/rss package isn't on latest
[See details here](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1661503642166259?thread_ts=1661462665.751409&cid=CPTJYRY5A).

Open questions:

- Was this a blip with the `rss` package, or is it affecting other apps?
- Is it an issue with TypeScript components?

### PR DESCRIPTION
**Pull request by andrewjschuang**
**Context:**

Apps components are published to `@pipedream`'s NPM registry so they can be reused in any code and workflows, e.g. [`@pipedream/rss`](https://www.npmjs.com/package/@pipedream/rss).
Whenever a change is deployed, the user should also modify the app's `package.json` version [as stated in the docs](https://pipedream.com/docs/components/guidelines/#package-json). However, it wasn't clear (_at least to me_) why this was required. And in my experience, most PRs did not contain modification to `package.json` versions.

**Changes:**

This PR modifies the GH Check and ensures that whenever a dependency file is modified, the respective `package.json` version should also be.

**Note:**

Probably a lot of components versions are not updated in the NPM registry.
The script below can be used to bump all minor versions and guarantee they are updated in the NPM registry (save and run the script in `components/script.js`):

```js
let fs = require("fs");

const apps = fs.readdirSync("./");
apps.forEach((appName) => {
  const packagePath = `${appName}/package.json`;
  if (fs.existsSync(packagePath)) {
    let contents = JSON.parse(fs.readFileSync(packagePath));
    let minor = Number.parseInt(contents.version.split(".").splice(-1));
    minor++;
    const version = contents.version.split(".").splice(0, 2);
    version.push(minor.toString());
    contents.version = version.join(".");
    const newPackage = JSON.stringify(contents, null, 2) + "\n";
    fs.writeFileSync(packagePath, newPackage);
  }
});
```

The reason I didn't do it yet is that while this PR is not merged, other PRs might change the versions and cause a conflict here. **But it should be run and the changes committed to this PR right before merging so they are published to NPM**.

Resolves #4103.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4168"></a>

### CODE REVIEW

**Review by jcortes — DISMISSED** [review]
Hi @andrewjschuang  Looks great to me! Ready for QA!

**Comment by andrewjschuang** [comment]
Oh, I forgot in another branch that some packages had errors, pushed them here

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, could you advice the expected behavior your code should have so I can design a test case for this? 🙏

**Comment by andrewjschuang** [comment]
Hi @vunguyenhung, currently the GH Check will run only for PRs that try to merge to **master**.
You can change [this line](https://github.com/PipedreamHQ/pipedream/blob/master/.github/workflows/publish-packages.yaml#L4) to `on: push` so that when you push a commit to any branch it will run the check.

For the tests, if any dependency for a action or source component is modified (app, trigger, action, base, common, etc.), if the `package.json` version for the app is not modified, along with the component version, the check should fail.

**Comment by andrewjschuang** [comment]
@vunguyenhung thanks for the tests and report.
I'll run the script to update all `package.json` versions to publish the latest changes to the NPM registry

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
