### PR TITLE
Updates to support new auth implementation for WhatsApp Business

### PR DESCRIPTION
**Pull request by dannyroosevelt**

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by vellames — APPROVED** [review]
lgtm

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!

**Comment by dannyroosevelt** [comment]
> Verification completed, ready for release!

Nice! So @DilanAthukorala you were able to connect your account and get everything working?

**Comment by DilanAthukorala** [comment]
> > Verification completed, ready for release!
> 
> Nice! So @DilanAthukorala you were able to connect your account and get everything working?

@dannyroosevelt Yes I was able to connect and perform the actions successfully.

**Comment by dannyroosevelt** [comment]
Great! Any feedback, etc? What were your thoughts on all the actions?

**Comment by DilanAthukorala** [comment]
> Great! Any feedback, etc? What were your thoughts on all the actions?

@dannyroosevelt The description of steps to connect to the app is very clear and easy to understand and the actions were user friendly so no confusions for me this time.

**Pull request merged**
