### PR TITLE
Linear action - Get Issue by ID

### LINKED ISSUE #3108: [ACTION]
**Is there a specific app this action is for?**
Linear - Get Issue by ID

**Please provide a link to the relevant API docs for the specific service / operation.**
Linear GraphQL Query: https://github.com/linear/linear/blob/master/packages/sdk/src/_generated_documents.graphql#L6361-L6368
I would like to have built in action that using the GraphQL query similar to the below custom code
image
```js
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    linear: {
      type: "app",
      app: "linear",
    }
  },
  async run({steps, $}) {
    const data = {
      "query": `
        query issue($id: String!) {
          issue(id: $id) {
            id
            url
          }
        }
      `,
      variables: {
        id: steps.create_issue.$return_value._issue.id
      }
    }
    return await axios($, {
      method: "post",
      url: `https://api.linear.app/graphql`,
      headers: {
        Authorization: `Bearer ${this.linear.$auth.oauth_access_token}`,
        "Content-Type": `application/json`,
      },
      data,
    })
  },
})
```

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3108 

**Get Issue** | Get an issue by ID

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by jcortes — COMMENTED** [review]
HI @michelle0927 LGTM! Ready for QA!

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
