### PR TITLE
Refactor MySQL actions to use additionalProps

### LINKED ISSUE #3114: Refactor MySQL actions to use additionalProps to support dynamic columns
App: `mysql`

Instead of users having to select columns and separately entering an array of values to map to those columns via a separate prop, we should render columns dynamically using additionalProps.

### Actions to update
- Create Row
- Update Row
- Any other actions that pull in columns, but I think that's all of them

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3114

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[MySQL_3122_2103.pdf](https://github.com/PipedreamHQ/pipedream/files/8900448/MySQL_3122_2103.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, I have tested using a free MySQL hosting, all test cases are passed! Ready for release! 

Test report
[MySQL_3122_1848.pdf](https://github.com/PipedreamHQ/pipedream/files/8927154/MySQL_3122_1848.pdf)

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
