### PR TITLE
[ACTION][GITHUB] Get Repository Content

### PR DESCRIPTION
**Pull request by jverce**
* Add new action to fetch a repository's content
* Add new method in the Github app module to fetch a repository's
  content
* Add `toSingleLineString` utility function to a `utils.mjs` module

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4371"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by vellames — DISMISSED** [review]
lgtm

**Comment by DilanAthukorala** [comment]
@jverce According to the description path field is optional and can be left unspecified 
image

**Comment by jverce** [comment]
> @jverce According to the description path field is optional and can be left unspecified, please make this param optional and if unspecified it should retrieve the contents of the repository's root directory image

@DilanAthukorala done!

**Comment by DilanAthukorala** [comment]
@jverce Thank you! 

This is verified and ready for release.

**Comment by jverce** [comment]
Thanks @DilanAthukorala!
Can you approve again, so that I can merge? 🙏🏻

**Comment by DilanAthukorala** [comment]
@andrewjschuang @vellames please help approve & merge this.

**Review by vellames — APPROVED** [review]

**Pull request merged**
