### PR TITLE
Update fraudlabs_pro component.

### PR DESCRIPTION
**Pull request by fraudlabspro**
Update fraudlabs_pro component following the introduction of Fraudlabs Pro v2 API and update of Fraudlabs Pro NodeJS SDK.

## WHAT

Update the dependency of FraudLabs Pro NodeJS to the latest which is 3.0.0.

## WHY

FraudLabs Pro introduced v2 of their API. Prior to that, FraudLabs Pro NodeJS SDK had been updated to the new version. Hence the fraudlabs_pro component in Pipedream also required an update.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by lcaresia — DISMISSED** [review]

**Comment by fraudlabspro** [comment]
Hi vunguyenhung,

I have modified the actions to display the error message if error occured, can you please see if this meet your requirements?

**Review by michelle0927 — DISMISSED** [review]

**Comment by fraudlabspro** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Update-fraudlabs_pro-component-10201-614c337876c94bc58618ba136c160e51

Hi vunguyenhung,

- We are checking for the issue of the Send Sms Verification action.
- For your comment on the second item, if it is for testing purpose, you can always login to you FraudLabs Pro account dashboard, go to SMS verification area, and look for the OTP on the table.
flp-dashboard-sms-1

**Comment by fraudlabspro** [comment]
Hi @vunguyenhung 

After thoroughly investigating the matter, we are currently unable to reproduce the issue on our end. Hence, 

1. Can we know exactly how did you make the testing? For example, did you click the test button simultaneously or did you click the button with a fixed time interval?
2. Can we have the access to the workflow? We would like to see the workflow in details to make sure we are re-creating the workflow correctly.

**Comment by fraudlabspro** [comment]
Hi @vunguyenhung ,

We hope this message finds you well. I wanted to follow up on the issue you faced during your testing for our last commit. It's been two weeks since we reached out, and we understand you may have been busy.

We want to check if you have done the testing again from your side, and can you provide us the information we want in the previous comment? We're hoping to address this issue soon, so if possible, we would appreciate a response at your earliest convenience.

**Review by michelle0927 — APPROVED** [review]

**Pull request merged**
