### PR TITLE
Removing Calendar API related source and references from Hubspot component

### PR DESCRIPTION
**Pull request by malexanderlim**
## WHAT
I am removing references to the Calendar API and deleting the source component (New Task) that utilizes this. 
After this, I will unpublish the component from the registry.

### <samp>🤖 Generated by Copilot at 4f9797f</samp>

Removed unused code related to calendar tasks from the hubspot component. Deleted `new-task` source and `CALENDAR` constant, and removed `getCalendarTasks` method from `hubspot.app.mjs`.

### <samp>🤖 Generated by Copilot at a507855</samp>

> _`Version` numbers rise_
> _Cleaning up unused code bits_
> _Spring cleaning for `HubSpot`_

## WHY
The Calendar API will be sunset on July 28, 2023, after which the API will be shut down, and marketing calendar data will no longer be available through the API.

See Hubspot's [changelog](https://developers.hubspot.com/changelog/upcoming-sunset-calendar-api?utm_campaign=App%20Partner%20Program%20Updates%202023&utm_medium=email&utm_content=256525853&utm_source=hs_email) for more info.

### <samp>🤖 Generated by Copilot at 4f9797f</samp>

*  Remove unused calendar-related code and dependencies ([link](https://github.com/PipedreamHQ/pipedream/pull/6213/files?diff=unified&w=0#diff-666cfa522539f9f9e80228e304f66be7cea214ced59cfef89017fbaec14c1988L11), [link](https://github.com/PipedreamHQ/pipedream/pull/6213/files?diff=unified&w=0#diff-4a128799f58cfa4618d7363237ef52755555a0e4f8e4baeec48ffd18453ca0b7L334-L343))
*  Delete source file for triggering on new calendar tasks, since it is no longer supported by the component ([link](https://github.com/PipedreamHQ/pipedream/pull/6213/files?diff=unified&w=0#diff-19e19defc8ce5aae168bdf98389ccace42e11971a546cab6bcbd2de2a069233a))

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by alysonturing** [comment]
You have to bump the version of the package.json, and also, the version of all sources/actions related with the file `hubspot.app.mjs`
Please see the output [here](https://github.com/PipedreamHQ/pipedream/actions/runs/4855259915/jobs/8653618612?pr=6213) and https://pipedream.com/docs/components/guidelines/#versioning for more information.

**Review by alysonturing — APPROVED** [review]
LGTM! Thank you for your valuable contribution!

**Pull request merged**
