### PR TITLE
WOXO #3833

### PR DESCRIPTION
**Pull request by lcaresia**
I don't find a way to do videos pagination or async options to list projects.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4011"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by vellames — DISMISSED** [review]

**Comment by DilanAthukorala** [comment]
@lcaresia Observing following error when creating the source with auth values 

API Key - EUoACH3tBcGHDv8C7-wCDuL4IBEJpDkh
TEAM - 62fa6bb6fb0f765dbc724962

```
[debug] err.response {
  "status": 502,
  "statusText": "Bad Gateway",
  "headers": {
    "date": "Mon, 15 Aug 2022 17:04:01 GMT",
    "content-type": "application/json",
    "content-length": "36",
    "connection": "close",
    "x-amzn-requestid": "5dc76c14-3b7b-446e-a995-aa8816e5d581",
    "x-amzn-errortype": "InternalServerErrorException",
    "x-amz-apigw-id": "W6hkMGZjIAMFsMA=",
    "cf-cache-status": "BYPASS",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=CfXNtvxmymOBND2G%2FWEhEQi3nO2XpwXPu7JazE%2FqnCXOYNrMX%2BO5YBCI5VgvtsMGVzNlitl2%2BpG6k13cJCUCdSmTVGDtN7gLHxpKM%2FkWFyczzQPBlfGp9iFe1h1Jpr0%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "73b381c679348015-IAD",
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
  },
  "config": {
    "url": "https://api.woxo.tech/video/project/fvAPLZCyGK",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "team": "EUoACH3tBcGHDv8C7-wCDuL4IBEJpDkh",
      "token": "EUoACH3tBcGHDv8C7-wCDuL4IBEJpDkh",
      "User-Agent": "axios/0.21.4"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "method": "get"
  },
  "data": {
    "message": "Internal server error"
  }
}
2022-08-15T19:04:02
error
Error: Request failed with status code 502
at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:269:11)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1333:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```








2. Unable to select project ID - User should be able to list the project ID and if that's not possible there should be description of how to obtain it. 
image

**Comment by lcaresia** [comment]
> 2\. Unable to select project ID - User should be able to list the project ID and if that's not possible there should be description of how to obtain it.

@DilanAthukorala I push an update about this, can you check?

> Observing following error when creating the source with auth values

I can't reproduce this! Can you share more details on Slack?

**Comment by lcaresia** [comment]
@DilanAthukorala Can you test again?

**Comment by DilanAthukorala** [comment]
Verification completed, This is ready for release.

**Review by vellames — APPROVED** [review]

**Review by vellames — APPROVED** [review]

**Pull request merged**
