### PR TITLE
Dock Certs - New Components

### LINKED ISSUE #6041: [Components] Dock Certs
### App
Dock Certs
https://www.dock.io/certs

Triggers:
1. Certificate Issued: A new certificate has been issued to a user.
2. Certificate Revoked: An existing certificate has been revoked from a user.

Actions:
1. Issue Certificate: Issue a new certificate to a specified user.
2. Revoke Certificate: Revoke an existing certificate from a specified user.
3. Verify Certificate: Check the validity of a user's certificate.

_This list of suggested components was generated using ChatGPT_

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #6041 

**Trigger**

- New Credential Issued

**Actions**

- List Credentials
- Issue Credential
- Revoke Credential

Note to QA: To be able to revoke a credential, make sure to enter a Revocation Registry, Issuer, and Expiration Date when issuing the credential.

### CODE REVIEW

**Review by lcaresia — APPROVED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Dock_Certs_6166_1511.pdf](https://github.com/PipedreamHQ/pipedream/files/11351410/Dock_Certs_6166_1511.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Dock_Certs_6166_1052.pdf](https://github.com/PipedreamHQ/pipedream/files/11417503/Dock_Certs_6166_1052.pdf)

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
