### PR TITLE
Shopify: Update to remove unresponsive event types

### PR DESCRIPTION
**Pull request by michelle0927**

### CODE REVIEW

**Comment by jverce** [comment]
@michelle0927 what's the motivation behind the removal of these event types?

**Comment by michelle0927** [comment]
> @michelle0927 what's the motivation behind the removal of these event types?

Simply put, they don't work. Apparently, this has been an existing Shopify issue for at least a couple of years. Here's one thread about it:
https://community.shopify.com/c/Shopify-APIs-SDKs/Event-API-not-firing-cancelled-orders-events/td-p/470264

**Comment by jverce** [comment]
> > @michelle0927 what's the motivation behind the removal of these event types?
> 
> Simply put, they don't work. Apparently, this has been an existing Shopify issue for at least a couple of years. Here's one thread about it:
> https://community.shopify.com/c/Shopify-APIs-SDKs/Event-API-not-firing-cancelled-orders-events/td-p/470264

That's a shame 😞 
Yeah, Shopify's API has those WTF's every now and then 😂

**Review by jverce — APPROVED** [review]

**Review by jverce — CHANGES_REQUESTED** [review]
Sorry, just forgot you'll need to bump the sources versions.

**Review by jverce — APPROVED** [review]

**Pull request merged**
