### PR TITLE
Update links from /limits to /docs/limits

### PR DESCRIPTION
**Pull request by chipach**
## WHAT

Fix documentation links from /limits to /docs/limits

## WHY

Because I kept clicking the wrong link in the Pricing page on the website.

## HOW

Mass change of /limits to /docs/limits

### CODE REVIEW

**Comment by dylburger** [comment]
@chipach `/docs` is actually assumed because it's set as the base path in the VuePress / Vercel app that serves docs. If you visit the preview links above and visit e.g. the Bash page where you made the change, you'll note that your link now direct to `/docs/docs/limits/#disk`, which has an extra `/docs`. 

Did a specific link not work for you before?

**Review by dylburger — CHANGES_REQUESTED** [review]
See my comment in the main PR. These links are all now broken.

**Comment by chipach** [comment]
https://pipedream.com/docs/pricing has at least 1 broken link.  Feel free to close this PR; I have no way of really testing this through however you serve your website, but the links from an HTML point of view relative to the directory structure seem wrong.

```
<p>But Free account have a <a href="/limits#daily-credits-limit">daily limit of free credits</a> that cannot be exceed. Standard <a href="/docs/limits/" class="">Pipedream platform limits</a> apply to Free Accounts as well.</p>
But Free account have a 
<a href="/limits#daily-credits-limit">daily limit of free credits</a>
 that cannot be exceed. Standard 
<a href="/docs/limits/" class="">Pipedream platform limits</a>
 apply to Free Accounts as well.
```

**Comment by dylburger** [comment]
You can test locally using the instructions [here](https://github.com/PipedreamHQ/pipedream/tree/master/docs). I know this setup might seem odd, but it's the way we have to manage given the way we serve the site. Thanks for the PR regardless! If you see anything else awry please let us know.

**Pull request closed without merging**
