### PR TITLE
Delete components/padlet

### PR DESCRIPTION
**Pull request by twjiang1**
Padlet no longer needs Pipedream for API.

## WHAT

Delete Padlet components.

You can find my profile on our about us page. https://padlet.com/about/about-us-3n0xnxd514ce. My name is Thomas Jiang

## WHY

No longer need/ in use

### <samp>🤖 Generated by Copilot at 52f9d5b</samp>

* Remove Padlet app and source ([link](https://github.com/PipedreamHQ/pipedream/pull/7623/files?diff=unified&w=0#diff-b3b723b6fac5f98f35a8e554d30d648fd92347870ebfd0417597d8670c2c30c8), [link](https://github.com/PipedreamHQ/pipedream/pull/7623/files?diff=unified&w=0#diff-9c9a7fcc8915d483d8dd30077409130a2c22969f790a760d8df52082ca482c53))
* Delete Padlet README file ([link](https://github.com/PipedreamHQ/pipedream/pull/7623/files?diff=unified&w=0#diff-9c9a7fcc8915d483d8dd30077409130a2c22969f790a760d8df52082ca482c53))

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by dannyroosevelt** [comment]
@twjiang1 can you share more context here?

**Comment by twjiang1** [comment]
We no longer need this for two reasons.

1) It's old and we no longer use it
2) We've built our own API found here: https://docs.padlet.dev/reference/introduction

Currently when our users search for Padlet API on google, they are redirected to your webpage which is inaccurate. We want to remove this webpage from showing https://pipedream.com/apps/padlet.

**Comment by dannyroosevelt** [comment]
> We no longer need this for two reasons.
> 
> 1. It's old and we no longer use it
> 2. We've built our own API found here: https://docs.padlet.dev/reference/introduction
> 
> Currently when our users search for Padlet API on google, they are redirected to your webpage which is inaccurate. We want to remove this webpage from showing https://pipedream.com/apps/padlet.
> 
> We will re-request an updated version of our API to pipedream when necessary but for now we want to remove this component. Thanks!

Got it. We're happy to update the integration based on your latest docs, and can also publish pre-built triggers and actions to actually make the integration useful for your users if that'd be helpful.

**Comment by twjiang1** [comment]
Thanks for the quick response.

We will mull over that. For the time being we just want it fully removed since it presents inaccurate information. Would you be able to do that for us? Thanks.

**Comment by dannyroosevelt** [comment]
Done. FYI Google caches their results, so even though your app's page is removed from our sitemap, it'll take some amount of time for Google to not return the page in its results.

**Comment by twjiang1** [comment]
Very much appreciate how quick this process was. I'll pass along your message to our CEO to see if continue integrating with Pipedream is a possibility. :)

**Pull request merged**
