### PR TITLE
Smiirl new actions

### PR DESCRIPTION
**Pull request by jcortes**

### CODE REVIEW

**Review by vellames-turing — DISMISSED** [review]
lgtm

**Comment by vunguyenhung** [comment]
Hello @ctrlaltdylan @dylburger I've checked this PR and there's an improvement needed on the link on the info box for the connecting account popup. 
image
Tapping to the link above, the browser opens another tab to https://my.smirrl.com/ (Notice the double r, instead of double i in smiirl). Then the site https://my.smirrl.com/ redirected me to a random phishing site
image
Expected Behavior: On the Connecting Account info box, change the link from https://my.smirrl.com/ to https://my.smiirl.com/, which will open a new browser tab with to the correct site
image
---

Hello @dannyroosevelt, I couldn't test the implemented actions here since Smiirl requires a physical counter in order to work with the API. I suggest that we proceed to merge this PR for user to use first and monitor for error. What do you think?

**Comment by ctrlaltdylan** [comment]
Good catch @vellames-turing

I have fixed the typo in the connection instructions.

I own a Smiirl counter myself, so I can test after we merge.

**Review by feyzullah — APPROVED** [review]

**Pull request merged**
