### PR TITLE
MongoDB - "search-documents" action's filter prop formatting issue

### LINKED ISSUE #2935: [BUG] Mongo "Search Documents" action's filter prop formatting issue
**Describe the bug**
The Mongo search action does not parse the passed prop string back into a JSON object.

Mongo's Query Language works with objects, but the serialization of the `filter` prop is causing the query to pass as a string.

Conditions to test with:

`{ key: { $exists: true } }`

`{ key: null }`

They should be passed to the `mongodb` client as objects in order to function properly.

### LINKED ISSUE #2936: [BUG] MongoDb "search-documents" action misspelled
The `search_documents.mjs` action is misspelled as `search_ducuments.mjs`:

https://github.com/PipedreamHQ/pipedream/blob/master/components/mongodb/actions/search-documents/search-ducuments.mjs

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #2935 
Resolves #2936

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by ctrlaltdylan** [comment]
Hi @michelle0927 

Thanks for working on this!

Just a quick question, I'm trying to understand how this action handles objects, because MongoDB queries are all ...well objects.

When I attempt to pass a normal filter using the `$exists` expression, I get this error about string conversion which another user reported as well:

CleanShot 2022-05-25 at 10 55 40@2x

Was the action designed to handle just simple string values passed?

**Comment by ctrlaltdylan** [comment]
Separately @michelle0927 , can we just use `JSON.parse` instead of the custom logic for parsing values? 

I definitely commend you for all of that work writing all of that logic, but it looks like we're serializing JSON.

Just another example, I tried using the object builder instead of manually creating the object, the value is serialized to a string, so the current formatting doesn't attempt to unserialize it into an object.

**Review by vellames-turing — DISMISSED** [review]
Tks

**Comment by michelle0927** [comment]
@ctrlaltdylan I made an update that should fix the TypeError above. 
I think the issue in your second screenshot is that the filter value needs to be a valid JSON object to be parsed by JSON.parse(). `dst_airport: { "$exists" : true }`

**Comment by vunguyenhung** [comment]
Hello @michelle0927, I have tested this PR and all test cases passed, but I have a question as listed below:

---
When executing the action, I faced the warning: 
```
Code was still running when the step ended. Make sure to await all Promises, or promisify callback functions. May be a false positive
```

I have tried to execute the action multiple times as well as creating a new action but the warning is still there. The description says this maybe a false positive, could you confirm if this is a false positive?

screencapture-pipedream-vunguyenhung-mongodb-search-documents-p-rvCoAgo-build-2022-05-26-22_19_26

Test report
[MongoDB_2941.pdf](https://github.com/PipedreamHQ/pipedream/files/8780057/MongoDB_2941.pdf)

**Comment by michelle0927** [comment]
> Hello @michelle0927, I have tested this PR and all test cases passed, but I have a question as listed below:
> 
> When executing the action, I faced the warning:
> 
> ```
> Code was still running when the step ended. Make sure to await all Promises, or promisify callback functions. May be a false positive
> ```
> 
> I have tried to execute the action multiple times as well as creating a new action but the warning is still there. The description says this maybe a false positive, could you confirm if this is a false positive?
> 
> 
> Test report [MongoDB_2941.pdf](https://github.com/PipedreamHQ/pipedream/files/8780057/MongoDB_2941.pdf)

@vunguyenhung Yes, this is a false positive. It's coming from the `mongoose` package (https://mongoosejs.com/docs/). I'm currently working on an issue (https://github.com/PipedreamHQ/pipedream/issues/2965) that includes updating the actions to use the MongoDB client (https://github.com/mongodb/node-mongodb-native) instead of mongoose.

**Pull request merged**
