### PR TITLE
Fix error creating or updating files & folders in shared Google drives

### LINKED ISSUE #2381: [BUG] Google Drive - Create Folder fails to create folder in shared drive
**Describe the bug**
The Google Drive **Create Folder** action shows the error: `File not found: 1C2fyNFZByZrIea3Fwmvgv0WbqVAAWVIr.` when trying to create a folder in a shared drive.

**To Reproduce**

1. Go to https://pipedream.com/new?v=2
2. Add a step to the workflow
3. Choose the "Google Drive" app and "Create Folder" action
4. Select a Google Drive Account, shared Drive and Folder
5. Click on 'Test'
6. See error, no folder appears in the Google Drive UI for the shared drive

**Expected behavior**
The workflow step runs successfully and a folder is created in the shared drive.

**Screenshots**
file-not-found

**Additional context**
The Google Drive "[Files: create](https://developers.google.com/drive/api/v3/reference/files/create)" endpoint requires the `supportsAllDrives` query parameter be `true` to create a file or folder in a shared drive. This parameter is [not set](https://github.com/PipedreamHQ/pipedream/blob/7e443e4267d1d18e1df449be93fc11d7e3b75b3a/components/google_drive/google_drive.app.mjs#L1004) in the [**Create Folder**](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/create-folder/create-folder.mjs) action, and defaults to `false`.

Slack thread: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1646409791784149?thread_ts=1646080449.712359&cid=CPTJYRY5A

### PR DESCRIPTION
**Pull request by js07**
Adds [`supportsAllDrives: true`](https://developers.google.com/drive/api/v3/reference/files/create) query param to Google Drive requests that create or update files in `google_drive.app.mjs`
Affects Google Drive actions:
- Add File Sharing Preference
- Create a New File
- Create New File From Text
- Create Folder
- Delete File
- Move File
- Move File to Trash
- Replace File
- Update File
- Upload File

Fixes missing files in options for the `fileId` prop in the Google Drive **Add File Sharing Preference** action

Revs version of all components that depend on `google_drive.app.mjs` (i.e., components in `/google_drive/`, `/google_sheets/`, and `/google_docs/`)

Fixes #2381

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by jcortes — DISMISSED** [review]
Hi @js07 It looks great to me! It's Ready for QA!

**Comment by QB3L** [comment]
I was just looking into doing this because I found the same issue while trying to upload files... this is probably not the right place to ask but does these changes map to the action `upload_file_to_folder_by_file_path` that is found on the current UI (see below)?  I ask because I started browsing the code and it looks significantly different than what gets appended to the action when selecting it.


google_drive

@jcortes

**Comment by js07** [comment]
@QB3L Thanks for the question. I think it'll help others with the same question.

Context:
The code in this pull request is for Google Drive [component actions](https://pipedream.com/docs/components/#what-are-components), which work in Pipedream's v1 workflow builder _and_ [new (v2) builder](https://pipedream.com/docs/migrate-from-v1/#new-builder-overview). The action in your screenshot is a [legacy action](https://pipedream.com/docs/components/migrating/#migrating-from-legacy-actions-to-component-actions), which works only in the v1 workflow builder.

Fix:
 To upload a file to the shared drive using the legacy **Upload File to Folder by File Path** action, you can edit the action's code in the code step in your workfow:
- Add the [`supportsAllDrives: true` query parameter](https://developers.google.com/drive/api/v3/reference/files/create#parameters) to the options for the `drives.files.create` call.
The code should look like this:
```js
const fs = require("fs")
const {google} = require('googleapis')

const driveAuth = new google.auth.OAuth2()
driveAuth.setCredentials({ access_token: auths.google_drive.oauth_access_token })
const drive = await google.drive({ version: 'v3', auth: driveAuth });

this.uploadResponse = (await drive.files.create({
  resource: {
    name: params.filename,
    originalFilename: params.filename,
    parents: params.parents,
  },
  media: {
    mimeType: params.filetype,
    uploadType: "media",
    body: fs.createReadStream(params.pathToFile)
  },
  fields: '*',
  supportsAllDrives: true,
})).data
```

**Comment by js07** [comment]
Fixed merge conflicts in https://github.com/PipedreamHQ/pipedream/pull/2383/commits/8b2a7687250dbf6ecfc4e65436f976216ab83bde and revved versions of affected actions in https://github.com/PipedreamHQ/pipedream/pull/2383/commits/127b501d7f7c1426207e199d05c6ba580df5d735.

**Pull request merged**
