### PR TITLE
5659 pushover sound

### PR DESCRIPTION
**Pull request by alysonturing**
resolves: #5659

### CODE REVIEW

**Review by GTFalcao — COMMENTED** [review]
Hi @alysonturing , thanks for the contribution!

I left a code suggestion and notes about the versions.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Pushover_5659_2056.pdf](https://github.com/PipedreamHQ/pipedream/files/10951022/Pushover_5659_2056.pdf)

**Comment by alysonturing** [comment]
Hey @vunguyenhung can you please check it again? I just merged a suggestion from the reviewer

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Pushover_5659_2113.pdf](https://github.com/PipedreamHQ/pipedream/files/10951080/Pushover_5659_2113.pdf)

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
