### PR TITLE
3037 bug hubspot new engagement source fails with maximum execution time reached error

### PR DESCRIPTION
**Pull request by luancazarine**
Source - new engagement: added a limit to the loop

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by lcaresia — DISMISSED** [review]
Thanks for you contribution!

**Comment by vunguyenhung** [comment]
Hello @luancazarine, I have checked your code and it seems to be running ok for my case
screencapture-pipedream-sources-dc-kjugmJg-2022-06-07-20_45_31

Though reading @js07 [investigation here](https://github.com/PipedreamHQ/pipedream/issues/3037#issue-1258382131), he stated that the `db.after` is never set, so the [createdAfter](https://github.com/PipedreamHQ/pipedream/blob/215c5e621025d7919a385b226af11285c8fc5e41/components/hubspot/sources/new-engagement/new-engagement.mjs#L32) is always the timestamp for [one month ago](https://github.com/PipedreamHQ/pipedream/blob/215c5e621025d7919a385b226af11285c8fc5e41/components/hubspot/sources/common.mjs#L25). I have checked your new code and the `db.after` is still `null` every time the source runs. 
screencapture-pipedream-sources-dc-kjugmJg-logs-2022-06-07-20_51_47

Could you check if this is a expected behavior relative to what @js07 has described?

**Review by lcaresia — APPROVED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[HubSpot_3037.pdf](https://github.com/PipedreamHQ/pipedream/files/8880055/HubSpot_3037.pdf)

**Pull request merged**
