### PR TITLE
Actions - Papyris

### LINKED ISSUE #3715: Papyrs
### App
Papyrs

### Triggers
* New Page by This API User
* New Page
* New People

### Actions
* Post Comment on Feed (Activity Stream)
* Create New Heading
* Post Comment on Page
* Create New Textbox (Text)
* Create New Textbox (HTML)
* Update TextBox (HTML)
* Update TextBox (Text)

### PR DESCRIPTION
**Pull request by vellames**
Closes #3715 

4 actions implemented:

- Create Paragraph (Textbox)
- Create Heading
- Update Paragaph
- Update Heading

### CODE REVIEW

**Review by GTFalcao — DISMISSED** [review]
Hi @vellames , thanks for your contribution, looks good to me! 👏

**Comment by DilanAthukorala** [comment]
@vellames For Update Heading & Update Paragraph actions, the style class get reset after updating, Is it possible provide the style class as an update param or to keep it without getting changed / reset?

**Comment by vellames** [comment]
> @vellames For Update Heading & Update Paragraph actions, the style class get reset after updating, Is it possible provide the style class as an update param or to keep it without getting changed / reset?

Humm, the api doesnt provide the `styleclass` in the update, I can add it and we can check if makes some difference. I will let you know when I update it

**Comment by vellames** [comment]
@DilanAthukorala I update those actions. Please let me know if the new params make some difference in your tests

**Comment by DilanAthukorala** [comment]
@vellames Yes it's working now, Verification competed.

**Comment by GTFalcao** [comment]
@vellames you need to add a package.json file before we can merge - one of the automated checks is failing because the app lacks one

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
