### PR TITLE
[Components] Habitify #6035

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖 Generated by Copilot at f64a63c</samp>

This pull request adds a new component for Habitify integration, which consists of an app and a source. The app `habitify.app.mjs` handles the authentication and API requests for Habitify, and the source `new-habit-created.mjs` emits events for new habits created in Habitify. The pull request also updates the component package and the pnpm-lock file, and removes some unused files.

### <samp>🤖 Generated by Copilot at f64a63c</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _The habitify app, a wondrous tool that connects_
> _With the divine API of the habit-forming gods_
> _And emits events like thunderbolts when habits are born._

### <samp>🤖 Generated by Copilot at f64a63c</samp>

*  Add the habitify app component, which integrates with the Habitify API and provides methods for making requests and getting habits ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-0436c02ed0f6bd1a02dfc7fb7a53657089a424d96009f99bf10fe3fc67a08b25R1-R32))
*  Add the new-habit-created source component, which emits an event for each habit created in Habitify ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-2229330d3000e6590a6c5cfc80767cf349b3ceaef46c4ed118e132f973d0e8dcR1-R35))
*  Update the version of the habitify component package to 0.0.2 ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-1ea06aedfa5bf25c623d0d2750b849bfea212c8a43f54a8e1c8e8bc50780f8f7L3-R3))
*  Remove the files field from the habitify component package.json, which is not needed for publishing to the Pipedream registry ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-1ea06aedfa5bf25c623d0d2750b849bfea212c8a43f54a8e1c8e8bc50780f8f7L10))
*  Add a newline at the end of the habitify component package.json ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-1ea06aedfa5bf25c623d0d2750b849bfea212c8a43f54a8e1c8e8bc50780f8f7L17-R16))
*  Remove the budgets_ai, formstack_documents, and holded components from the pnpm-lock.yaml file, which indicates that they were removed or updated in another pull request or commit ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL521-L523), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1376-L1378), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1818-L1820))
*  Add the eodhd_apis and selectpdf components to the pnpm-lock.yaml file, which indicates that they were added or updated in another pull request or commit ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR1180-R1182), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3530-R3532))
*  Update the version of the @types/node dependency for several packages from 18.15.11 to 17.0.45 in the pnpm-lock.yaml file, which indicates that the packages were updated in another pull request or commit and that the @types/node dependency was downgraded to match the node engine version of the Pipedream platform ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8743-R8740), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8752-R8749), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8838-R8835), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8948-R8945), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8987-R8984), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9067-R9064), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11460-R11457), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11485-R11482), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11492-R11489), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11498-R11495), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11546-R11543), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11671-R11668), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11688-R11685), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11709-R11706), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11726-R11723), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11762-R11759), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17213-R17210), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17501-R17498), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17542-R17539), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17659-R17656), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17790-R17787), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17851-R17848), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17956-R17953), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL18006-R18003), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL18027-R18024), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL21206-R21203), [link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL21226-R21223))
*  Update the version of the ieee754 dependency for the buffer package from 1.1.13 to 1.2.1 in the pnpm-lock.yaml file, which indicates that the buffer package was updated in another pull request or commit and that the ieee754 dependency was upgraded to fix some bugs or improve performance ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL12870-R12867))
*  Update the version of the string-width dependency for the wrap-ansi package from 1.0.2 to 4.2.3 in the pnpm-lock.yaml file, which indicates that the wrap-ansi package was updated in another pull request or commit and that the string-width dependency was upgraded to support newer versions of node and fix some bugs ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL24804-R24801))
*  Delete the `components/habitify/.gitignore` file, which is not needed for the habitify component ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-e7acd0da71942732330214bdeacdc1084d360ba9f0144a28019518960edcd7a6))
*  Delete the `components/habitify/app/habitify.app.ts` file, which is replaced by the `components/habitify/app/habitify.app.mjs` file ([link](https://github.com/PipedreamHQ/pipedream/pull/6073/files?diff=unified&w=0#diff-cc95eb745bfabd82b01065e1e32ce508970f04d74a957ad0651050ce95bbf933))

### CODE REVIEW

**Review by feyzullah — APPROVED** [review]

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Habitify_6035_1006.pdf](https://github.com/PipedreamHQ/pipedream/files/11279440/Habitify_6035_1006.pdf)

**Review by feyzullah — DISMISSED** [review]

**Review by feyzullah — APPROVED** [review]

**Pull request merged**
