### PR TITLE
[Components] usersketch #9109

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fb3613f</samp>

This pull request adds two new actions and new app methods for the UserSketch component, which is a tool for creating and managing user feedback. The actions allow users to create events and users in UserSketch using the `create-event` and `create-user` files. The app methods use the `axios` function and the UserSketch API to make the requests. The pull request also updates the component package and the `@pipedream/platform` dependency.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fb3613f</samp>

> _We're building new components for the platform_
> _We're adding actions and methods to the app_
> _We're updating dependencies and the lock file_
> _We're heaving away on the count of three_

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fb3613f</samp>

*  Add two new actions for creating events and users in UserSketch ([link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-a8b7f5efca253e1db305cc07b412c92adc7a7444f138d7ea8b0b726d208ff99bR1-R28), [link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-699550579860581a2d53395295d7b0b1b60eb2e537472c9c101706c8ba3cf203R1-R67), [link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-79563f57f7adba590965d854902a4d7d7a4eb678fa4d01ca8a70e27ef13a0130R1-R51))
* Update the `usersketch.app.mjs` file to import the `axios` function and implement the API methods ([link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-d4197cf0d37e21d4d909b5bdeb8a9f76b957392a078fec4f2f2538792737d213R1-R2), [link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-d4197cf0d37e21d4d909b5bdeb8a9f76b957392a078fec4f2f2538792737d213L6-R40))
* Update the `package.json` file to increment the version and add the `@pipedream/platform` dependency ([link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-8d48eaa974c6463de35914b7b2763e45a878b647e5c19db80ae7170f85288fbaL3-R3), [link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-8d48eaa974c6463de35914b7b2763e45a878b647e5c19db80ae7170f85288fbaL14-R18))
* Update the `pnpm-lock.yaml` file to reflect the changes in the `package.json` file and add a new entry for the `decision_journal` package ([link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL6820-R6826), [link](https://github.com/PipedreamHQ/pipedream/pull/9210/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR1434-R1436))

### CODE REVIEW

**Review by GTFalcao — DISMISSED** [review]
LGTM!

**Comment by lcaresia** [comment]
@vunguyenhung

**Review by michelle0927 — APPROVED** [review]

**Pull request merged**
