### PR TITLE
Ticktick - List Projects new action

### LINKED ISSUE #3238: [ACTION] Ticktick search for Projects
**Is there a specific app this action is for?**
This request is for the TickTick app
Currently, with the V1 API, in order to update or complete tasks you need the Project ID. But the V1 API provides no methods to search for Projects (or Tasks for that matter...)

**Please provide a link to the relevant API docs for the specific service / operation.**
There is a V2 API but it is undocumented. For example the following link lists all projects
https://api.ticktick.com/api/v2/projects
There are other wrappers which manage to circumvent this, but I don't know how. For example
Docs for an unofficial python wrapper are here: https://lazeroffmichael.github.io/ticktick-py/

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3238 

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/3479"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by lcaresia — APPROVED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
@michelle0927 I am not able to create projects in TickTick to test the List Projects action, could you please show me the steps? 
image

**Comment by DilanAthukorala** [comment]
Verification completed, this is ready for release.

**Pull request merged**
