### PR TITLE
Mautic Legacy Refactor and New Triggers

### LINKED ISSUE #2903: [TRIGGER] Mautic
App: `mautic`
https://developer.mautic.org/

### Triggers
- New Contact: Triggers when a new contact is created
- Updated Contact: Triggers when an existing contact is updated
- New Form Entry: Triggers when a form is submitted

### PR DESCRIPTION
**Pull request by andrewjschuang**
_Observation: Mautic webhooks take about 10 minutes to make the request._

**New Triggers:**

- [X] new-contact
- [X] updated-contact
- [X] new-form-submission

**Updated legacy actions:**

- [X] add-contact-to-campaign
- [X] clone-campaign
- [X] create-contact
- [X] delete-company
- [X] get-campaign
- [X] get-contact
- [X] list-available-contact-fields
- [X] search-campaigns
- [X] search-companies
- [X] search-contacts
- [X] update-contact 

**Deleted legacy action:**

- [X] make-api-call

Resolves #2903.
Closes #3010.

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by andrewjschuang** [comment]
@lcaresia can you please approve this one for the PR Review?
I merged the other two PRs into this one.

**Review by lcaresia — DISMISSED** [review]
Approved!

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Mautic_3073.pdf](https://github.com/PipedreamHQ/pipedream/files/8863310/Mautic_3073.pdf)

**Comment by andrewjschuang** [comment]
@vunguyenhung should be fixed now.

Actions affected after modification:
1. Create Contact
2. Delete Company

**Comment by vunguyenhung** [comment]
Hi @andrewjschuang, I had re-tested create-contact and delete-company and all test cases are passed! Ready for release! 

Test report
[Mautic_3073_0909.pdf](https://github.com/PipedreamHQ/pipedream/files/8866194/Mautic_3073_0909.pdf)

**Review by lcaresia — APPROVED** [review]
LGTM!

**Pull request merged**
