### PR TITLE
Data store add create record if not found

### LINKED ISSUE #2963: [Updates] Add create record if not found in Has Key to Data Store Action
Extend [this functionality](https://github.com/PipedreamHQ/pipedream/blob/master/components/data_stores/actions/get-record/get-record.mjs#L27) to [has-key](https://github.com/PipedreamHQ/pipedream/blob/master/components/data_stores/actions/has-key/has-key.mjs) action.

We should also probably update the name/key of that action to be more descriptive: "Check if key exists"

### PR DESCRIPTION
**Pull request by andrewjschuang**
Resolves #2963.

### CODE REVIEW

**Review by vellames-turing — CHANGES_REQUESTED** [review]
Could you rename the actions, please?
Something like `get-record-or-create` and `check-key-or-create`
I am not very good with names haha
cc @dannyroosevelt

**Review by vellames-turing — DISMISSED** [review]
tks

**Comment by DilanAthukorala** [comment]
@andrewjschuang If the key does not exist the newly created value is created as String type even the if I passed an Object or an Array value. 
image

**Comment by andrewjschuang** [comment]
> @andrewjschuang If the key does not exist the newly created value is created as String type even the if I passed an Object or an Array value.

@DilanAthukorala should be fixed now!

**Comment by DilanAthukorala** [comment]
Verification completed.

**Review by feyzullah — APPROVED** [review]
approved

**Pull request merged**
