### PR TITLE
Fixing folder structure and imports (fixes #3966)

### LINKED ISSUE #3966: SMTP2Go: send email action
**Is there a specific app this action is for?**
SMTP2GO

**Please provide a link to the relevant API docs for the specific service / operation.**
https://apidoc.smtp2go.com/documentation/#/POST%20/email/send

### PR DESCRIPTION
**Pull request by bsommardahl**
There were some compile issues brought up by @vunguyenhung that I have fixed.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4178"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by jcortes — COMMENTED** [review]
HI @bsommardahl just as a suggestion I think you can improve even more this app by helping us to fix the following:

1. Since this app works with Typescript the first thing you need to do is to include a `tsconfig.json` file into the app's dir just like [in rss app](https://github.com/PipedreamHQ/pipedream/blob/master/components/rss/tsconfig.json).

2. Fix all these eslint errors in `smtp2go.app.ts`file like
image and similar eslint errors in `components/smtp2go/actions/send-single-email/send-single-email.ts`, `components/smtp2go/actions/send-single-email-with-template/send-single-email-with-template.ts` and `components/smtp2go/actions/common.ts`

The rest of modifications looks good to me. So I will leave it to you if you want to make these changes. Just let me know! Thanks for this contribution!

**Comment by andrewjschuang** [comment]
Closing since this was done in #4226.

**Pull request closed without merging**
