### PR TITLE
[Filter] Refactor Action

### LINKED ISSUE #4427: [ACTION] Refactor Filter Action
We've gotten consistent feedback from users that the Filter actions are confusing to use. I think they're probably overly complex, and can likely be simplified by flattening the "condition" configurations we currently present and updating some of the names, descriptions, etc.

Here is a **non-working** prototype of what I have in mind:
https://pipedream.com/new?h=tch_wlXfNP

Notes:
- The only reason the `condition` prop is set to have the default it does, is because I want to **remove** the `secondValue` prop in the case of the `singleValueConditions` (binary conditions), but we don't support that logic in `additionalProps()` today.
- Open to feedback or other suggestions on how to improve the usability

### PR DESCRIPTION
**Pull request by andrewjschuang**
New Actions:

- end-on-condition
- continue-on-condition

To unpublish:

- continue-workflow-condition
- end-workflow-condition
- end-workflow-custom-condition

Resolves #4427.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4440"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by dannyroosevelt** [comment]
Should this work?

Screenshot by Dropbox Capture
Screenshot by Dropbox Capture

**Comment by dannyroosevelt** [comment]
Given "success" is arbitrary since you can decide to continue or end execution, I think we should not display `$summary` at all for this action.

**Comment by dannyroosevelt** [comment]
I tried 2 combinations without success

Screenshot by Dropbox Capture

Screenshot by Dropbox Capture

**Comment by andrewjschuang** [comment]
> Given "success" is arbitrary since you can decide to continue or end execution, I think we should not display `$summary` at all for this action.

So for `messageOnContinue` we should just `console.log()` it?

**Comment by andrewjschuang** [comment]
Fixed the array (and object) issues, can you try again?
Was parsing even if it already was an array or object

**Comment by dannyroosevelt** [comment]
> array (and object) issues, can

If execution ends because we call `$.flow.exit()`, we should pass the `messageOnEnd`. If execution continues, we should `return messageOnContinue`. But because we give special UX treatment for `$.summary`, it's confusing if we should show the end message vs continue message there specifically. Do you get what I mean?

**Comment by andrewjschuang** [comment]
> If execution ends because we call `$.flow.exit()`, we should pass the `messageOnEnd`. If execution continues, we should `return messageOnContinue`. But because we give special UX treatment for `$.summary`, it's confusing if we should show the end message vs continue message there specifically. Do you get what I mean?

Ok, now it's returning the message. Can you test it and see if it's according to what you were thinking?

**Review by lcaresia — APPROVED** [review]
LGTM!

**Review by alysonturing — DISMISSED** [review]
LGTM!

**Review by alysonturing — APPROVED** [review]
LGTM!

**Review by alysonturing — APPROVED** [review]

**Pull request merged**
