### PR TITLE
add component seven

### PR DESCRIPTION
**Pull request by matthiez**
### <samp>🤖 Generated by Copilot at ae044be</samp>

This pull request adds a new component for seven, a cloud communication platform, to the Pipedream repository. The component consists of seven actions that enable users to perform various tasks with phone numbers, such as looking up information, sending SMS, and making text-to-speech calls. The component also includes a `.gitignore` file, a `package.json` file, a `README.md` file, and a `utils.mjs` file that provide common functionality and documentation for the seven actions.

### <samp>🤖 Generated by Copilot at ae044be</samp>

> _`seven` component_
> _adds actions for phone data_
> _`.gitignore` too_

### <samp>🤖 Generated by Copilot at ae044be</samp>

*  Add seven component for phone number lookup and SMS/TTS services (`components/seven`)

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by alysonturing** [comment]
@dannyroosevelt @malexanderlim 
This is an user submitted PR but there's no app file, how to proceed here?

**Comment by malexanderlim** [comment]
Hi @matthiez, I'm in the process of setting up the app file for the Seven integration. I just emailed support@ to inquire about how to set up an OAuth integration; as that is generally preferred on our side. 

I noticed that you set this up for users to input their API Keys, is there any preference for a key-based integration vs. OAuth on your side?

**Comment by matthiez** [comment]
> Hi @matthiez, I'm in the process of setting up the app file for the Seven integration. I just emailed support@ to inquire about how to set up an OAuth integration; as that is generally preferred on our side. 
> 
> I noticed that you set this up for users to input their API Keys, is there any preference for a key-based integration vs. OAuth on your side?

Hi, thanks for the effort. I will make sure this gets changed to oauth ASAP and get back to you.

**Comment by alysonturing** [comment]
@matthiez also, some checks were not successful from github actions, please see: https://github.com/PipedreamHQ/pipedream/actions/runs/6085046066/job/16547439891?pr=7882

**Review by alysonturing — CHANGES_REQUESTED** [review]
@matthiez looks like there's github actions failing, see here: https://github.com/PipedreamHQ/pipedream/actions/runs/6085046066/job/16547439891?pr=7882

**Comment by malexanderlim** [comment]
@matthiez, confirming that the app scaffolding has been set up for an OAuth integration on our side.

**Comment by malexanderlim** [comment]
Hi @matthiez , once this is refactored to change from API Key to OAuth, can you please ensure that you also remove api key as a prop here?

**Comment by matthiez** [comment]
> @matthiez, confirming that the app scaffolding has been set up for an OAuth integration on our side.

Hi, thanks for the help.
I am having troubles getting all to work though, as the scope "lookup" is somehow missing. Is there a particular reason for that?

**Pull request closed without merging**
