### PR TITLE
IFTTT New Actions

### LINKED ISSUE #1505: [ACTION] IFTTT new action
**Is there a specific app this action is for?**
IFTTT

**Please provide a link to the relevant API docs for the specific service / operation.**
https://platform.ifttt.com/docs/api_reference

**Send Data** | Sends data to an applet. It can execute a specific applet

### PR DESCRIPTION
**Pull request by andrewjschuang**
IFTTT New Actions

Separated into two actions:

- [X] Trigger Event With JSON
- [X] Trigger Event with 3 Values

Resolves #1505

### CODE REVIEW

**Review by jcortes — APPROVED** [review]
@andrewjschuang Nothing to add. LGTM! Ready for QA!

**Comment by DilanAthukorala** [comment]
@andrewjschuang **GET** HTTP Method is not working. (For both actions)
image

**Comment by andrewjschuang** [comment]
> @andrewjschuang **GET** HTTP Method is not working. (For both actions)

@DilanAthukorala thanks for reporting. I actually don't see any need for GET requests, so I'm going to remove it :)

**Comment by DilanAthukorala** [comment]
Verification completed successfully. 

cc - @dannyroosevelt

**Review by dannyroosevelt — APPROVED** [review]

**Pull request merged**
