### PR TITLE
GitHub, GitLab, Bitbucket - Optional Branch

### LINKED ISSUE #508: [SOURCE] Make "branch ID/name" argument optional for Gitlab, Github and BitBucket.
As per PR review: 
_Originally posted by @tjk in https://github.com/PipedreamHQ/pipedream/pull/487#discussion_r497283362_

There is no reason why we cannot make this argument optional (in fact, from the [Github component's description](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/new-commit.js#L13) it seems like this was the original idea).

This will require refactoring the following components:
* BitBucket
* Github
* Gitlab

### PR DESCRIPTION
**Pull request by andrewjschuang**
- [X] Makes `branch` optional for `new-commit` sources in **Bitbucket** and **GitLab**.
- [X] Created `new-commit-instant` source with optional `branch` for **GitHub**.

**GitHub** - `new-commit` polling-based source - if no `branch` is supplied it defaults to the default branch.

The other actions/sources either require `branch` or is already optional.

Resolves #508.

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by andrewjschuang** [comment]
> Hi @andrewjschuang I just added totally optional comments. If you think these are not important and you don't want to apply, please let me know and approve.

Hi @feyzullah, I've implemented your comments, thanks!

**Review by feyzullah — APPROVED** [review]
Thank you, approved

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[BitBucket__GitHub_2993.pdf](https://github.com/PipedreamHQ/pipedream/files/8825207/BitBucket__GitHub_2993.pdf)

**Pull request merged**
