### PR TITLE
5369 pagerduty update the new or updated incident trigger

### PR DESCRIPTION
**Pull request by luancazarine**
- Add optional prop events
  - Fix props pagination
  - Update all webhook integration to V3

### CODE REVIEW

**Review by vellames — APPROVED** [review]
lgtm

**Comment by DilanAthukorala** [comment]
@luancazarine Unable to create source without filter, following issue observed.
image

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!

**Review by vellames — APPROVED** [review]

**Pull request merged**
