### PR TITLE
Twitter Upload Media Action

### LINKED ISSUE #5036: [ACTION] Twitter Upload Media
**Is there a specific app this action is for?**
Twitter

**Please provide a link to the relevant API docs for the specific service / operation.**
[Upload Media](https://developer.twitter.com/en/docs/tutorials/uploading-media)

**Context**
First requested by a customer here: https://pipedream.com/community/t/advice-for-uploading-media-to-twitter-in-v2/2866/14

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #5036 

Note: Uploading large files may require increasing the Workflow's timeout setting. 
Settings -> Execution Controls -> Timeout

### CODE REVIEW

**Review by alysonturing — APPROVED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
Verification success, ready for release.

**Comment by gabriel-kaam** [comment]
Hello @michelle0927  ; thanks for the feature !

I'm having issue with it , I got this error: "SegmentIndex must be between 0 and 999." ;

Should I open an issue on GH ; or give you more infos here ?

**Comment by michelle0927** [comment]
> Hello @michelle0927 ; thanks for the feature !
> 
> I'm having issue with it , I got this error: "**SegmentIndex must be between 0 and 999.**" ;
> 
> Should I open an issue on GH ; or give you more infos here ?
> 
> (my file size if 4mb)

@gabriel-kaam I was able to reproduce the error you were seeing. I created a PR that should fix the issue here: https://github.com/PipedreamHQ/pipedream/pull/5308

**Comment by gabriel-kaam** [comment]
> > Hello @michelle0927 ; thanks for the feature !
> > I'm having issue with it , I got this error: "**SegmentIndex must be between 0 and 999.**" ;
> > Should I open an issue on GH ; or give you more infos here ?
> > (my file size if 4mb)
> 
> @gabriel-kaam I was able to reproduce the error you were seeing. I created a PR that should fix the issue here: #5308

Hello @michelle0927 ;

Thanks for creating the PR so fast !

I tried to run my script with another video (1.8mo) ; but ran into another error (see below)

Capture d’écran

As a context, I'm trying to uplod a video from Instagram to Twitter ;

I saw this thread https://twittercommunity.com/t/uploading-video-chunked-error-on-finalize-command/67035/21 , so I thought that maybe my video was not in the right format ; but I checked on VLC and the format looks good (**MPEG-4 Part 10 with AAC audio**)

Capture d’écran

Here's the source video that I'm trying to upload ([source video](https://video-lax3-2.cdninstagram.com/o1/v/t16/f1/m82/0A498806072CA481B9796BF488E3ED80_video_dashinit.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5jbGlwcyJ9&_nc_ht=video-lax3-2.cdninstagram.com&_nc_cat=111&vs=671324034734219_4185120934&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC8wQTQ5ODgwNjA3MkNBNDgxQjk3OTZCRjQ4OEUzRUQ4MF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVABgkR0U3UVdCTUhHX0RhcHdnQ0FQU2RmaXBEbGg5N2JxX0VBQUFGFQICyAEAKAAYABsBiAd1c2Vfb2lsATEVAAAmkIatvvnM%2FT8VAigCQzMsF0AuAAAAAAAAGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHUAAA%3D%3D&ccb=9-4&oh=00_AfDSOnJWdFmBHs29V9hYRQZsaExLEA09dXVjRQXoqOBKWQ&oe=63D86A87&_nc_sid=ea0b6e&_nc_rid=fa42e317a5))  ;
I think the url will stop working at some point ; but here's original IG post: https://www.instagram.com/reel/Cn9vcS1ImNJ/

Maybe I'm doing a mistake in my workflow ; here's the JS code i'm using to download the video and store it to the **/tmp** folder .

Capture d’écran

Can you Let me know if you see a mistake somewhere ?

Thanks

**Comment by michelle0927** [comment]
@gabriel-kaam I discovered that uploading video requires a `media_category` prop. I made some updates to [this PR](https://github.com/PipedreamHQ/pipedream/pull/5308) that allowed me to upload videos successfully.

However, I'm still not able to upload the source video you linked to above. I wasn't able to post it through the Twitter UI either, which makes me wonder if something about it doesn't meet Twitter's [media requirements](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)?

[This is a video](https://thecannabin.com/wp-content/themes/cbd-theme/images/file_example.mp4) I was able to successfully upload and tweet.

**Comment by gabriel-kaam** [comment]
> @gabriel-kaam I discovered that uploading video requires a `media_category` prop. I made some updates to [this PR](https://github.com/PipedreamHQ/pipedream/pull/5308) that allowed me to upload videos successfully.
> 
> However, I'm still not able to upload the source video you linked to above. I wasn't able to post it through the Twitter UI either, which makes me wonder if something about it doesn't meet Twitter's [media requirements](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)?
> 
> [This is a video](https://thecannabin.com/wp-content/themes/cbd-theme/images/file_example.mp4) I was able to successfully upload and tweet.



> @gabriel-kaam I discovered that uploading video requires a `media_category` prop. I made some updates to [this PR](https://github.com/PipedreamHQ/pipedream/pull/5308) that allowed me to upload videos successfully.
> 
> However, I'm still not able to upload the source video you linked to above. I wasn't able to post it through the Twitter UI either, which makes me wonder if something about it doesn't meet Twitter's [media requirements](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)?
> 
> [This is a video](https://thecannabin.com/wp-content/themes/cbd-theme/images/file_example.mp4) I was able to successfully upload and tweet.

Thanks for the feedback .

You're right , I can't upload m video using the Twitter UI ; I got the **InvalidMedia** error , but I don't know exactly why .

I will look more into it !

Thank

**Comment by gabriel-kaam** [comment]
Ok found the issue ! it was with the audio track of the video ; it was encoded using a SBR technology which does not seem to be supported by Twitter (don't ask me what SBR is either)

input

I re-ncoded the audio track using ffmpeg and the default AAC codec ; and the video successfully uploaded to Twitter !

`ffmpeg -i input.mp4 -c:v copy -c:a aac -movflags +faststart output.mp4`
[source](https://stackoverflow.com/a/59059816/1465029)

Now I got this (I'm still using VLC to get codec details)

output_aac

And it worked !

Capture d’écran

Now I have a find a way to do the same thing in Pipedream :) 

I think MediaConvert is available ? I'll go play with it !

Thanks

**Pull request merged**
