### PR TITLE
Amazon SES Actions

### LINKED ISSUE #1506: [ACTION] Amazon SES new actions
**Is there a specific app this action is for?**
Amazon SES

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.aws.amazon.com/ses/index.html

**Send a Message** \| Sends an email message
**List Email Templates** \| Retrieves a list of email templates
**Create an Email Template** \| Creates a new email template
**Get an Email Template** \| Retrieves a specified email template
**Update an Email Template** \| Updates an existing email template
**Delete an Email Template** \| Deletes an email template
**List Contact Lists** \| Retrieves a list of contact lists
**Create a Contact List** \| Creates a new contact list
**Get a Contact List** \| Retrieves a specified contact list
**Update a Contact List** \| Updates an existing contact list
**Delete a Contact List** \| Deletes a contact list
**List Contacts** \| Retrieves a list of contacts in a specified contact list
**Create a Contact** \| Creates a new contact
**Get a Contact** \| Retrieves a specified contact
**Update a Contact** \| Updates an existing contact
**Delete a Contact** \| Deletes a contact
**List Configuration Sets** \| Retrieves a list of configuration sets
**Get a Configuration Set** \| Retrieves a specified configuration set
**Create a Configuration Set** \| Creates a new configuration set
**Create a Configuration Set Event Destination** \| Creates a new configuration set event destination
**Delete a Configuration Set** \| Deletes a configuration set

### PR DESCRIPTION
**Pull request by andrewjschuang**
Updated action:

- [X] Send Email

New actions:

- [X] Create Email Template
- [X] Get Email Template
- [X] Update Email Template
- [X] Send Templated Email

Resolves #1506.

### CODE REVIEW

**Review by vellames-turing — DISMISSED** [review]
Looks pretty good, tks!

**Comment by andrewjschuang** [comment]
@DilanAthukorala thanks for noting, fixed!

(Sorry for accidentally editing your comment)

**Comment by DilanAthukorala** [comment]
@andrewjschuang Can you please check this error for send_email  - I'm setting the correct region (ap-south-1) but this error comes for different region 
image]]




And this error comes when text is already supplied

image

**Comment by DilanAthukorala** [comment]
@andrewjschuang I'm getting this error for send_templated_email action

image

**Comment by andrewjschuang** [comment]
@DilanAthukorala I've pushed some updates, can you please test them again?

> @andrewjschuang I'm getting this error for send_templated_email action

What are the inputs here?

**Comment by DilanAthukorala** [comment]
@andrewjschuang Thanks!

Verification completed.

**Review by vellames-turing — APPROVED** [review]

**Pull request merged**
