### PR TITLE
Intellexer API - New Components

### LINKED ISSUE #6152: [Components] Intellexer API
### App
Intellexer API 
https://www.intellexer.com/intellexer_api.html

Triggers:
1. Document Summarized: A document has been summarized using the API.
2. Named Entities Extracted: Named entities have been extracted from a document.

Actions:
1. Summarize Document: Summarize a document using Intellexer API.
2. Extract Named Entities: Extract named entities from a document using Intellexer API.
3. Detect Language: Detect the language of a document using Intellexer API.

_This list of suggested components was generated using ChatGPT_

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #6152 

**Actions**

- Summarize Document
- Extract Named Entities
- Detect Language

### CODE REVIEW

**Review by lcaresia — APPROVED** [review]
LGTM!

**Review by andrewjschuang — COMMENTED** [review]
`detect-language` action passed:

image

**Review by andrewjschuang — COMMENTED** [review]
`summarize-document` action needs improvement:
I'm not sure what kind of URL do I need to pass into the prop. I tried a Wikipedia Article and a PDF, both unsuccessful. I see there is also a `summarizeText` endpoint in the API, would that be a better choice for this action?

image
image

**Review by andrewjschuang — COMMENTED** [review]
`extract-named-entities` needs improvement:
Same issue as the `summarize-document`. I don't know what kind of URL do I need to input to the prop. Adding a more informative description will help.

image
image

**Comment by andrewjschuang** [comment]
Hi @michelle0927, some tests have failed or need improvement!
Please check out the comments above

**Comment by michelle0927** [comment]
> `summarize-document` action needs improvement: I'm not sure what kind of URL do I need to pass into the prop. I tried a Wikipedia Article and a PDF, both unsuccessful. I see there is also a `summarizeText` endpoint in the API, would that be a better choice for this action?
> 

> `extract-named-entities` needs improvement: Same issue as the `summarize-document`. I don't know what kind of URL do I need to input to the prop. Adding a more informative description will help.
> 

I'm not sure it matters what kind of URL is entered. What's returned depends on which props are set to `true`, so I updated several of the props to default to `true` instead of `false`. I also created a new `summarize-text` action to utilize the summarizeText endpoint.

**Review by andrewjschuang — COMMENTED** [review]
`extract-named-entities` passed:
Question: does loading relations tree and sentences reflect on more usage on the API for the user? If so I think these two can be defaulted to `false`.

image
image

**Review by andrewjschuang — COMMENTED** [review]
`summarize-document` action passed:
Obs: I changed the `structure` prop options to CamelCase

Required props passed:
image
image

All props:
image
image
image

**Review by andrewjschuang — COMMENTED** [review]
`summarize-text` action needs improvement: Test cases passed but I see no `items` in the response?

image
image
image

**Comment by michelle0927** [comment]
> Hi @michelle0927 thanks for the updates!
> 
> Improvement needed: For the `summarize` actions, I see no `items` in the response. Not sure if I am passing something wrong in the action

Looks like `summaryRestriction` has to be set for `items` to be included in the response. Also, I had a typo. :)

**Review by andrewjschuang — COMMENTED** [review]
`summarize-text` action passed:

image

**Review by andrewjschuang — COMMENTED** [review]
`summarize-document` action passed:

image

**Review by andrewjschuang — APPROVED** [review]
@michelle0927 thanks for the updates and moving the propDefinitions to the app file!

All test cases passed, ready for release!

**Pull request merged**
