### PR TITLE
fix exclude replies and retweets (#2391)

### LINKED ISSUE #2391: [BUG] Twitter User Tweets trigger's exclude replies option broken
**Describe the bug**
As a pipedream workflow builder, when I use the **User Tweets** trigger and enable the exclude replies option, I expect the trigger to exclude the replies.

1. Start a new workflow
2. Create a **User tweets** trigger
3. Enable the exclusion of replies as events in the source
4. Reply to a user tweet that triggers the workflow
5. The reply tweet should **not** emit an event in the source or workflow

**Expected behavior**
Replies on user tweets should not trigger the workflow.

https://pipedream.com/community/t/does-the-exclude-replies-option-for-a-twitter-user-tweets-trigger-not-work-or-am-i-missing-something/1956

**Screenshots**
77ec4214cf05a5963e038faf132f257ffa81da71_2_1380x662

### PR DESCRIPTION
**Pull request by Jordon-L**
The variable names being passed to the function getUserTimeline were incorrect. I have fixed the variable names in user-tweets.mjs and my-tweets.mjs. The function wanted excludeReplies and includeRts, but exclude_replies and include_rts were given.

https://github.com/PipedreamHQ/pipedream/blob/d03056aec44e2e9f981c5aaed3d458b1b1b8a041/components/twitter/twitter.app.mjs#L684-L692

fixes #2391

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by dylburger** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Review by vellames-turing — DISMISSED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
Verification completed.

**Comment by dannyroosevelt** [comment]
@vellames-turing looks like there are a couple build errors -- can you address then merge?

**Comment by vellames-turing** [comment]
Looks like this just need to be merged with master.

**Comment by vellames-turing** [comment]
> @vellames-turing looks like there are a couple build errors -- can you address then merge?



>

**Comment by vellames-turing** [comment]
> @vellames-turing looks like there are a couple build errors -- can you address then merge?

Looks like this just need to be merged with master.

**Comment by vellames-turing** [comment]
@Jordon-L Can you update these versions please? https://github.com/PipedreamHQ/pipedream/runs/6630985647?check_suite_focus=true

**Comment by Jordon-L** [comment]
Hi, I have updated the version number.

**Review by lcaresia — APPROVED** [review]

**Comment by dylburger** [comment]
@Jordon-L I just merged this change. Thanks again for the contribution!

**Pull request merged**
