### PR TITLE
[BUG] Discord Bot, Add a Role prebuilt step

### LINKED ISSUE #4530: [BUG] Discord Bot, Add a Role prebuilt step
**Describe the bug**

Hi I’m having trouble with the ‘discord bot’, ‘add a role’ prebuilt step.
The props for Discord Bot ‘Account’ and ‘Guild’ correctly prepopulate with the correct options.
But, the ‘User’ prop won’t list all the members of the guild.
Only 1 member shows up and It’s not clear to me why that one user would be any different.
I’ve turned on all the permissions for the bot.
Other prebuilt steps can list all members.
When I manually enter the ID of the member then the (add a) “Role”: prop functions correctly.
When I try to pass the prop the path to the same ID of the member it won’t work.
IE {{steps.Get_DiscordID_Matching_Registration.foundID}}
The error comes back “Request failed with status code 400”

**To Reproduce**
see "add a role" step here: 
https://pipedream.com/@garretttstark/discord-registration-p_MOCy55M/
Node steps to try and pass the User ID may not be necessary if the "user" prop is debugged.

**Expected behavior**
See above.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #4530 

Some of the Discord_bot props require the values of other props in order to retrieve options. If the user enters a custom expression, the values aren't yet known, so the options cannot be retrieved. In that case, the user can enter custom expressions for subsequent props as well. Instead of throwing a 400 error, these props will now display a Configuration Error noting that the required prop value is needed in order to retrieve options.

For the Role prop in **Add a Role**, the UserId is only needed to filter out roles that the member already has. This has been updated so that if the User is entered as a custom expression, it will display all guild roles instead of displaying an error.

The User prop in the **Add a Role** action filters the users to exclude bots, but other than that I wasn't able to reproduce the issue with Users not all showing up.

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4550"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by jcortes — COMMENTED** [review]
Hi @michelle0927 everything looks great to me. Thanks for fixing these issues! Ready for QA!

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
