### PR TITLE
[ACTION] OpenAI #4926

### PR DESCRIPTION
**Pull request by lcaresia**

### CODE REVIEW

**Review by feyzullah — COMMENTED** [review]
Hi @lcaresia this looks good to me. I am fixing the `package.json` only

**Review by feyzullah — DISMISSED** [review]

**Comment by DilanAthukorala** [comment]
@lcaresia Observing following issues;

1. for send prompt action - invalid description for `suffix` field
image

2. for send prompt action - unable to pass `max tokens` value
image

3. for send prompt action - unable to pass `temperature` value
image

4. for send prompt action - unable to pass `Top P` value
image

5. for send prompt action - unable to pass `N` value
image

6. for send prompt action - unable to pass `presence_penalty` value
image

7. for send prompt action - unable to pass `frequency_penalty` value
image

image

**Comment by lcaresia** [comment]
@feyzullah Thanks for fix this for me!

**Comment by lcaresia** [comment]
@DilanAthukorala Can you test again? Thanks!

**Comment by DilanAthukorala** [comment]
Testing Completed, Ready for release!

**Review by feyzullah — APPROVED** [review]

**Pull request merged**
