### PR TITLE
#7206 - Migrate Outlook Calendar components

### LINKED ISSUE #7206: [Components] Microsoft Outlook - migration request
Hi Component Dev team,

The ask here is to migrate a few triggers and actions from **Microsoft Outlook** to **Microsoft Outlook Calendar**.

**Triggers:**
- New Calendar Event
- New Upcoming Event
- Updated Calendar Event

**Actions:**
- Create Calendar Event

These actions currently exist today under **Microsoft Outlook**, but we'd like to migrate these over to the standalone **Microsoft Outlook Calendar** app to limit the number of scopes being requested, and separate the apps by function (email vs. calendar).

Thanks!

### PR DESCRIPTION
**Pull request by GTFalcao**
### <samp>🤖 Generated by Copilot at bee2b0b</samp>

This pull request splits the Microsoft Outlook app into two separate apps: Microsoft Outlook and Microsoft Outlook Calendar. The former handles the email functionality and the latter handles the calendar and scheduling functionality of the Microsoft Outlook API. The pull request also adds new components and dependencies for the new apps, and updates the references, descriptions, and documentation accordingly. The pull request also renames and moves some files to reflect the new app structure.

### <samp>🤖 Generated by Copilot at bee2b0b</samp>

> _Sing, O Muse, of the mighty pull request_
> _That split the Outlook app in twain_
> _And gave birth to a new calendar component_
> _With its own props, methods, and domain_

## WHY

Closes #7206 

### <samp>🤖 Generated by Copilot at bee2b0b</samp>

*  Extract calendar and scheduling functionality from Microsoft Outlook app to a new Microsoft Outlook Calendar app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-ff73bff5dc13caf87ad7a8c2529a5b704942ceb6dab739910f327335228e0c50L6), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L44-L55), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L68-L77), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L102-L118), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L211-L230), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L296-L305), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-41acf024f14ee264cf3594b860d00abc6f46c83fc3660bc51448008b7b749cdeL3-R3), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-26ffa1fb511327e26c7759c91f9d3111e1b32193d9d613b9249a08da12009b37R1-R5), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-2010c469f3597f7c8e14ac2e8001fd12930bfeb3f19f26d28690195594e08afaR1-R153), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-999f93f2a12e1a67a15e29abae3ab67e480f65f3ed0a2f3d6313a5f1d40d07e2R1-R20), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-681e4cf5f992d138f09ac279cee5786ca72bc73bc5e154f80a216037658421d8R1-R10), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-c85857efeb135f11a274a08f433835efd9b6d9a7362033198e8bac30f44d9ebf), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-f10cdb30d194cefec8e7ed92c840928f0d08b500a83d6a2bb5728cc480a48089), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-873d3ee0164a08dfc8cd89032178330806b30339abb2ea6eb66302fde6535cb5), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR2820-R2825))
  * Create new `microsoft_outlook_calendar.app.mjs` file to define propDefinitions and methods for the calendar app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-2010c469f3597f7c8e14ac2e8001fd12930bfeb3f19f26d28690195594e08afaR1-R153))
  * Create new `package.json` file to define metadata and dependencies for the calendar app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-999f93f2a12e1a67a15e29abae3ab67e480f65f3ed0a2f3d6313a5f1d40d07e2R1-R20))
  * Create new `README.md` file to provide an overview of the calendar app and its features ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-26ffa1fb511327e26c7759c91f9d3111e1b32193d9d613b9249a08da12009b37R1-R5))
  * Create new `common.mjs` file to import the calendar app and the common props and methods from the Microsoft Outlook app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-681e4cf5f992d138f09ac279cee5786ca72bc73bc5e154f80a216037658421d8R1-R10))
  * Rename and update the sources for the calendar app: `new-calendar-event`, `new-upcoming-event`, and `updated-calendar-event` ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-c85857efeb135f11a274a08f433835efd9b6d9a7362033198e8bac30f44d9ebf), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-f10cdb30d194cefec8e7ed92c840928f0d08b500a83d6a2bb5728cc480a48089), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-873d3ee0164a08dfc8cd89032178330806b30339abb2ea6eb66302fde6535cb5))
  * Update the import statement, the key, the version, and the description of the `create-calendar-event` action ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L1-R10))
  * Update the propDefinitions and the method call of the `create-calendar-event` action to refer to the calendar app instead of the Microsoft Outlook app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L18-R18), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L24-R24), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L31-R31), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L37-R37), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L43-R43), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L49-R49), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L55-R55), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L61-R61), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L67-R67), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-19d82d99dd4b72810d24fd29b3db38e6d961c7874b509365c4a780366169e4f6L104-R104))
  * Remove the propDefinitions and methods for the calendar functionality from the Microsoft Outlook app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L44-L55), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L68-L77), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L102-L118), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L211-L230), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-4452f3b43a1fa133452ae4b6ec63fc6ca6e71a68d3b2898cf9ab821774e39715L296-L305))
  * Update the version number of the Microsoft Outlook app to reflect the major update ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-41acf024f14ee264cf3594b860d00abc6f46c83fc3660bc51448008b7b749cdeL3-R3))
  * Remove the redundant line from the overview section of the README.md file of the Microsoft Outlook app ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-ff73bff5dc13caf87ad7a8c2529a5b704942ceb6dab739910f327335228e0c50L6))
  * Add a new entry for the calendar app in the `pnpm-lock.yaml` file ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR2820-R2825))
* Add new entries for the `azure_openai_service`, `mysql_ssl`, and `jest-config` packages in the `pnpm-lock.yaml` file ([link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR434-R435), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR2951-R2952), [link](https://github.com/PipedreamHQ/pipedream/pull/7460/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR18338-R18376))

### CODE REVIEW

**Review by luancazarine — DISMISSED** [review]
Hello @GTFalcao, thanks for your contribution! LGTM!

**Review by vellames — DISMISSED** [review]

**Review by vellames — CHANGES_REQUESTED** [review]
Conflicts

**Comment by GTFalcao** [comment]
I'm not sure why these pnpm conflicts keep happening. Resolved, but likely to happen again if another push to master occurs before this is merged

**Review by vellames — APPROVED** [review]

**Review by andrewjschuang — APPROVED** [review]

**Pull request merged**
