### PR TITLE
Reply.io new sources and actions

### LINKED ISSUE #3760: Reply
### App
Reply

### Triggers
* Inbox Category Set for Reply
* New Person Bounce
* New Link Clicked
* New Emails Sent
* New Email Opened
* New Person Opt Out
* New Email Replied
* Prospect Finished
* Add or Update Contact
* Zapier Step Launched

### Actions
* Create\Update Person and Push to Campaign
* Create\Update Person
* Mark as Finished
* Mark as Replied
* Move to the Next Step
* Remove Person From Campaign

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3760 

**Triggers**
- New Reply Categorized
- New Link Clicked
- New Email Sent
- New Email Opened
- New Contact Opt Out
- New Email Replied
- New Prospect Finished
- New Contact Added

**Actions**
- Create or Update Contact and Push to Campaign
- Create or Update Contact
- Mark Contact as Finished
- Mark Contact as Replied
- Remove Contact from Campaign

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
Hello @michelle0927. Thank you for your contribution. LGTM!

**Comment by DilanAthukorala** [comment]
@michelle0927 Please check the following;

1. Create/Update Contact and Push to Campaign Action - Observing following error but the contact gets updated correctly.
image


2. New Contact Opted Out Source - Event name should be corrected with space between words
image


3. NEW PROSPECT FINISHED (INSTANT) - Events not emitted, but in logs can see the events

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!

**Review by luancazarine — APPROVED** [review]
LGTM!

**Pull request merged**
