### PR TITLE
Typeform: fix the month in formatted dates

### PR DESCRIPTION
**Pull request by pedropedruzzi**
Fixes the date format strings used in Typeform sources.

The previous format strings used `mm` for months instead of `MM` and this caused incorrect formated dates like `2023-50-14 06:50:07 AM`.

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Comment by pedropedruzzi** [comment]
Sorry there is a bug in this fix. Hold it please.

**Comment by pedropedruzzi** [comment]
Now it's correct. Testing (timezone UTC-3):

```
> dt.toFormat("yyyy-MM-dd")
'2023-02-17'
> dt.toFormat('yyyy-MM-dd hh:mm:ss a')
'2023-02-17 01:49:25 PM'
```

**Review by feyzullah — APPROVED** [review]
Hi @pedropedruzzi thank you very much for your contribution. I made some small changes which are needed for our workflows to be run. There will be a QA check before this one is merged.

**Comment by vunguyenhung** [comment]
Hello @pedropedruzzi,

I have added a commit to your branch to fix unresolved module error that prevented me to publish this new source.

I've also tested the new code and verified that the new format is correct. Ready for release!
image

**Review by feyzullah — APPROVED** [review]

**Comment by vunguyenhung** [comment]
I've merged this on behave of the user

**Pull request merged**
