### PR TITLE
Product Hunt new sources

### LINKED ISSUE #3743: Product Hunt
### App
Product Hunt

### Triggers
* New Hot Product
* New Notification
* New Product
* New Upvote

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3743

**Sources**
- New Product Trending
- New Product Added
- New Product Upvoted

New Notification source was skipped because it requires Product Hunt's V1 API which has been deprecated.

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
Hello @michelle0927. Thank you for your contribution! LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Product_Hunt_3743_1348.pdf](https://github.com/PipedreamHQ/pipedream/files/10432097/Product_Hunt_3743_1348.pdf)

**Comment by michelle0927** [comment]
Note: I had to update some of the `enedis` files to get past the linter.

**Pull request merged**
