### PR TITLE
[ACTIONS/SOURCES] Added new actions and sources

### PR DESCRIPTION
**Pull request by jcortes**
# Actions
- [x] Send Message | Send an email message. [See the docs here](https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send)
- [x] List Contacts | Retrieve details for all contact lists - name, subscriber count, creation timestamp, deletion status. [See the docs here](https://dev.mailjet.com/email/reference/contacts/contact-list/#v3_get_contactslist)
- [x] Create Contact | Add a new unique contact to your global contact list and select its exclusion status. [See the docs here](https://dev.mailjet.com/email/reference/contacts/contact/#v3_post_contact)
- [x] Update Contact | Update the user-given name and exclusion status of a specific contact. [See the docs here](https://dev.mailjet.com/email/reference/contacts/contact/#v3_put_contact_contact_ID)

# Sources
- [x] Contact Created | Emit new event when a contact is created. [See the docs here](https://dev.mailjet.com/email/reference/contacts/contact-list/#v3_get_contactslist)

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by michelle0927 — DISMISSED** [review]
LGTM! :)

**Comment by DilanAthukorala** [comment]
@jcortes For send_message action the text part and the HTML part is not being sent to the receiver. Could you please check.

**Comment by vunguyenhung** [comment]
@DilanAthukorala I will handle this for you

**Comment by vunguyenhung** [comment]
Hello @jcortes, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Mailjet_2722.pdf](https://github.com/PipedreamHQ/pipedream/files/8815589/Mailjet_2722.pdf)

**Review by feyzullah — APPROVED** [review]
LGTM

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Mailjet_2722_2300.pdf](https://github.com/PipedreamHQ/pipedream/files/8845761/Mailjet_2722_2300.pdf)

**Review by lcaresia — APPROVED** [review]

**Pull request merged**
