### PR TITLE
[Components] Hootsuite #6613

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖 Generated by Copilot at de429a3</samp>

The Hootsuite component was refactored to use a separate file for the app definition and to declare its dependencies explicitly. The `hootsuite.app.ts` file was deleted and the `package.json` and `pnpm-lock.yaml` files were updated accordingly.

### <samp>🤖 Generated by Copilot at de429a3</samp>

> _`main` field updated_
> _Hootsuite component needs_
> _some `dependencies`_

### <samp>🤖 Generated by Copilot at de429a3</samp>

*  Update Hootsuite component to use correct file path and dependencies ([link](https://github.com/PipedreamHQ/pipedream/pull/6685/files?diff=unified&w=0#diff-0eb9d9519abba321208e157bbc8dc7c309f4c5d873da00f34085c49954f68c75L5-R22), [link](https://github.com/PipedreamHQ/pipedream/pull/6685/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1965-R1970))
* Delete unused Hootsuite app file ([link](https://github.com/PipedreamHQ/pipedream/pull/6685/files?diff=unified&w=0#diff-3b448d2842d761f77c171a209cdc0e9e99dce0d2fa61337053db7faaa8e20a9a))

### CODE REVIEW

**Review by michelle0927 — COMMENTED** [review]
It looks like there may be some files that didn't get committed?

**Review by michelle0927 — DISMISSED** [review]
Ready for QA!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Hootsuite_6613_2110.pdf](https://github.com/PipedreamHQ/pipedream/files/11615048/Hootsuite_6613_2110.pdf)

**Pull request merged**
