### PR TITLE
Google Cloud Pub/Sub - listen for events from existing topics

### LINKED ISSUE #2249: [SOURCE FEATURE] Google Cloud Pub/Sub Source should let me listen for events from an existing source
[See code here](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_cloud/sources/new-pubsub-messages/new-pubsub-messages.mjs). This source currently creates a Pub/Sub topic with the given name, but it should ideally give me the option to choose from an existing source or create a new one. We should talk about the best UX for that, but perhaps we could use conditional props:

1. Do you have an existing Pub/Sub topic, or would you like to create a new one?
2. (If existing) Show async options of existing topics
3. (If new) Show current prop - let me create a topic of a given name

### PR DESCRIPTION
**Pull request by michelle0927**
Gives user the option to select a `topicType` of "new" or "existing". If "existing" is selected, the user may select from a list of their existing topics.

Resolves #2249

### CODE REVIEW

**Review by vellames-turing — DISMISSED** [review]

**Comment by michelle0927** [comment]
> Observing following error when running the source 

@DilanAthukorala I think this is because `additionalProps` are not yet supported in the CLI. https://pipedream-users.slack.com/archives/CPTJYRY5A/p1648742555474089

**Comment by dannyroosevelt** [comment]
@DilanAthukorala what's the status of this one?

**Comment by DilanAthukorala** [comment]
> @DilanAthukorala what's the status of this one?

@dannyroosevelt I am not able to deploy the source with this mentioned issue

https://github.com/PipedreamHQ/pipedream/pull/2525#issuecomment-1105310541

**Comment by michelle0927** [comment]
@DilanAthukorala I apologize, I should have explained further. Since this component uses `additionalProps` and they are not yet supported in the CLI, you won't be able to deploy it using `pd dev`. You'll need to publish it using `pd publish`. Then you can deploy it from the UI. Go to https://pipedream.com/sources and click "New" to create a new source. Then click "My Sources", and your most recently published source will be at the top of the list. Click on the source you want to create/deploy, and you can enter the props from there.

**Comment by DilanAthukorala** [comment]
> @DilanAthukorala I apologize, I should have explained further. Since this component uses `additionalProps` and they are not yet supported in the CLI, you won't be able to deploy it using `pd dev`. You'll need to publish it using `pd publish`. Then you can deploy it from the UI. Go to https://pipedream.com/sources and click "New" to create a new source. Then click "My Sources", and your most recently published source will be at the top of the list. Click on the source you want to create/deploy, and you can enter the props from there.

@michelle0927 I have published the source as you mentioned, but I'm not seeing "My Sources" after Clicking "New" in https://pipedream.com/sources, Please advise. 
image

**Comment by DilanAthukorala** [comment]
@michelle0927 I am getting the following error when switching between **new** and **existing** options (after saving settings as new or existing and then switch)

image

**Comment by michelle0927** [comment]
@DilanAthukorala Thanks for catching that. There was an error preventing the subscriptions from being deleted in the `deactivate` hook. I made an update that should fix it.

**Comment by DilanAthukorala** [comment]
@michelle0927 Thanks, This is verified successfully. 

cc - @dannyroosevelt

**Pull request merged**
