### PR TITLE
[NetHunt] New Components

### LINKED ISSUE #3697: NetHunt CRM
### App
NetHunt CRM

### Triggers
* Deleted Record
* New Call Log
* New Comment
* New File
* New Record
* New or Updated Record (Advanced)
* New, Updated, or Deleted Record
* New or Updated Record in Filter

### Actions
* Create Comment
* Create Record
* Delete Record
* Add Gmail Thread to Record
* Create or Update Record
* Update Record
* Find Record
* Find or Create Record

### PR DESCRIPTION
**Pull request by andrewjschuang**
**Triggers:**

- comment-created
- new-record-created
- record-updated

**Actions:**

- add-gmail-thread-to-record
- create-comment
- create-record
- find-record
- get-record
- update-record

Resolves #3697.

### CODE REVIEW

**Review by luancazarine — APPROVED** [review]
Hi @andrewjschuang. Thanks for your contribution! LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[NetHunt_5707_1259.pdf](https://github.com/PipedreamHQ/pipedream/files/10964606/NetHunt_5707_1259.pdf)

**Comment by andrewjschuang** [comment]
Hi @vunguyenhung, thanks for flagging.
It should be fixed now!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[NetHunt_5707_0005.pdf](https://github.com/PipedreamHQ/pipedream/files/10971682/NetHunt_5707_0005.pdf)

**Review by luancazarine — APPROVED** [review]

**Pull request merged**
