### PR TITLE
New Components - chatbot_builder

### LINKED ISSUE #10446: [Components] chatbot_builder
# chatbot_builder
## URLs
- https://app.chatgptbuilder.io/api/swagger/#/
- https://app.chatgptbuilder.io/api/swagger/#/Accounts/createTag
- https://app.chatgptbuilder.io/api/swagger/#/Accounts/getPageTags
- https://app.chatgptbuilder.io/api/swagger/#/Accounts/deleteTag

#### Prompt
Create a new tag. https://app.chatgptbuilder.io/api/swagger/#/Accounts/createTag
#### Prompt
Get all tags from a page. https://app.chatgptbuilder.io/api/swagger/#/Accounts/getPageTags
#### Prompt
Delete a tag. https://app.chatgptbuilder.io/api/swagger/#/Accounts/deleteTag

### PR DESCRIPTION
**Pull request by lcaresia**
Resolves #10446.

### CODE REVIEW

**Review by GTFalcao — APPROVED** [review]
LGTM!

**Comment by lcaresia** [comment]
@malexanderlim Hey, action `Vercel – pipedream-docs-redirect-do-not-edit` never finish, how I proceed?

**Comment by malexanderlim** [comment]
> @malexanderlim Hey, action `Vercel – pipedream-docs-redirect-do-not-edit` never finish, how I proceed?
I think you can ignore it, but can you double check with the team in #component-development?

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
