### PR TITLE
[Components] MaintainX #5863

### PR DESCRIPTION
**Pull request by lcaresia**

### CODE REVIEW

**Review by michelle0927 — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[MaintainX_5863_1005.pdf](https://github.com/PipedreamHQ/pipedream/files/11107344/MaintainX_5863_1005.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[MaintainX_5863_0038.pdf](https://github.com/PipedreamHQ/pipedream/files/11114357/MaintainX_5863_0038.pdf)

**Review by michelle0927 — APPROVED** [review]

**Pull request merged**
