### PR TITLE
Zoom - Add GET request to certain Instant Webhook-Based Sources

### LINKED ISSUE #3342: [TRIGGER] zoom
Part of #3332

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3342 

Historical events will be emitted in the deploy hooks of the following sources/triggers:
**Meeting Created
Meeting Ended
Meeting Started
Meeting Updated
Recording Completed
Webinar Created
Webinar Ended
Webinar Started
Webinar Updated**

The following events require a paid subscription, and have not been tested.
**Recording Completed
Webinar Created
Webinar Ended
Webinar Started
Webinar Updated**

The following sources don't yet emit historical events because the Zoom API doesn't yet offer a way to retrieve generic events or deleted resources.
**Custom Event
Phone Event
Meeting Deleted
Webinar Deleted**

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/3464"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by DilanAthukorala** [comment]
@michelle0927 **For "Recording Completed" source, there are no events emitted after the recordings are completed.** 
image
image
image

**Comment by michelle0927** [comment]
@DilanAthukorala The "Recording Competed" source emits events for new cloud recordings (https://marketplace.zoom.us/docs/api-reference/zoom-api/events#/paths/recording.completed/post). The screenshot above shows a recording under Local Recordings. Do you have recordings under Cloud Recording that are not showing up? I don't have a Pro account, so I haven't been able to test that component.

**Comment by DilanAthukorala** [comment]
@michelle0927 Thank you, I was only able to test the components from my free account. 

I was not able to test the following sources that requires paid subscription. 

- Recording Completed
- Webinar Created
- Webinar Ended
- Webinar Started
- Webinar Updated
- Phone Events

Verification completed for the following sources and no issues observed. 

- Meeting Created
- Meeting Ended
- Meeting Started
- Meeting Updated
- Meeting Deleted
- Custom Events

@dannyroosevelt There were only 50% of sources that could be tested with free account, can we sign off with the above test results considering these were updates to already existing sources?

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
