### PR TITLE
Twitter Simple Search in List

### PR DESCRIPTION
**Pull request by feyzullah**

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by michelle0927 — APPROVED** [review]
LGTM!

The [issue](https://github.com/PipedreamHQ/pipedream/issues/3042) also asks for a source that emits an event when a list posts a new tweet. Will that be done in a separate PR?

**Comment by feyzullah** [comment]
> LGTM!
> 
> The [issue](https://github.com/PipedreamHQ/pipedream/issues/3042) also asks for a source that emits an event when a list posts a new tweet. Will that be done in a separate PR?

@michelle0927 thank you, you are right. Let me do it in this PR. I am moving the issue to the To Do column

**Comment by feyzullah** [comment]
@michelle0927 I skipped the source emits tweet in a list, because it is already there as `new-tweet-in-list`. I forgot to note it, sorry for all the mess. Moving the issue to Ready for QA again

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Twitter_3922.pdf](https://github.com/PipedreamHQ/pipedream/files/9260505/Twitter_3922.pdf)

**Pull request merged**
