### PR TITLE
OpenAI - Add audio functionality to Chat action

### LINKED ISSUE #14327: OpenAI - Add audio functionality to Chat action
### App
OpenAI
https://openai.com/index/introducing-the-realtime-api/

### Actions
This is a request to update chat completion workflow to accept audio input, as that is now supported

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #14327 

## Release Notes

- **New Features**
	- Added support for audio file input in the Chat component, allowing users to provide audio files for processing.

- **Version Updates**
	- Incremented version numbers across multiple components to reflect recent changes:
		- Chat: 0.2.0 → 0.2.1
		- Classify Items: 0.1.0 → 0.1.1
		- Create Embeddings: 0.0.12 → 0.0.13
		- Create Transcription: 0.1.12 → 0.1.13
		- Send Prompt: 0.1.11 → 0.1.12
		- Summarize: 0.1.0 → 0.1.1
		- Translate Text: 0.1.0 → 0.1.1
		- Package: 0.6.0 → 0.6.1

These updates enhance functionality and improve user experience across components.

### CODE REVIEW

**Review by GTFalcao — APPROVED** [review]
LGTM!

**Comment by michelle0927** [comment]
@vunguyenhung I haven't been able to reproduce the error: "The data provided for 'input_audio' is not of valid mp3 format". Is there a URL to the audio file you're using that I could test with? Would you mind testing with a different audio file? Here's one that I've tested with: https://audio-samples.github.io/samples/mp3/blizzard_tts_unbiased/sample-0/real.mp3

**Comment by michelle0927** [comment]
> Hi @michelle0927, please find the audio file I used here [iso8601.mp3.zip](https://github.com/user-attachments/files/17499558/iso8601.mp3.zip)

@vunguyenhung I think there's something off about that audio file. For me, it plays in a browser or with QuickTime, but won't open with Apple's Music Player. Using the package `music-metadata` to extract the file's metadata, I see some warnings that I don't see with other audio files.
```
quality: {
    warnings: [
      { message: 'Parse error: Cannot determine bit-rate' },
      { message: 'Parse error: Cannot determine bit-rate' },
      { message: 'Parse error: Cannot determine bit-rate' },
      ...
```

**Review by GTFalcao — APPROVED** [review]

**Pull request merged**
