### PR TITLE
Scrapingbot - New Components

### LINKED ISSUE #6043: [Components] ScrapingBot
### App
ScrapingBot
https://www.scraping-bot.io/

Triggers:
1. Data Scraped: Trigger when data is successfully scraped from a webpage.
2. Scraper Failed: Trigger when a scraping task fails, with details on the error.

Actions:
1. Scrape Webpage: Use ScrapingBot API to extract specific data from a webpage.
2. Retrieve Results: Retrieve and decode scraped results from a past scraping task.
3. Schedule Scraper: Schedule a new scraping task using ScrapingBot API for routine data extraction.

_This list of suggested components was generated using ChatGPT_

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #6043 

**Actions**

- Scrape Website
- Scrape Search Engine
- Scrape Social Media

### CODE REVIEW

**Review by feyzullah — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[ScrapingBot_6083_1027.pdf](https://github.com/PipedreamHQ/pipedream/files/11291987/ScrapingBot_6083_1027.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[ScrapingBot_6083_1222.pdf](https://github.com/PipedreamHQ/pipedream/files/11329241/ScrapingBot_6083_1222.pdf)

**Review by lcaresia — APPROVED** [review]

**Pull request merged**
