### PR TITLE
[Source] Snowflake - Add regex to getFailedTasksInDatabase

### PR DESCRIPTION
**Pull request by vellames**
### <samp>🤖 Generated by Copilot at f3c7be6</samp>

This pull request updates the snowflake package to version 0.9.1, which includes minor changes and bug fixes for several actions and sources related to snowflake. It also adds a new prop to the failed-task-in-schema source to filter failed tasks by name using regex, and refactors the common module of the snowflake sources to use helper methods for getting and setting the last max timestamp from the database. Additionally, it improves the performance and accuracy of the getFailedTasksInDatabase method of the snowflake app by using the INFORMATION_SCHEMA.TASK_HISTORY table function with some additional parameters.

### <samp>🤖 Generated by Copilot at f3c7be6</samp>

> _We're the snowflake crew and we're here to say_
> _We've fixed some bugs and added some features today_
> _We've bumped up the versions of our actions and sources_
> _So pull the latest code and join us in our courses_

### <samp>🤖 Generated by Copilot at f3c7be6</samp>

*  Incremented the version of the snowflake package and all the actions and sources related to snowflake to indicate minor changes or bug fixes ([link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-5dcb6e07b872e06c94ec09b23afa2f80f797df2ce61ae0140f2fdd62051dca9aL9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-0d457a538cafb0b75c2d2fb213cd68e2db88fcbae164393b487e00cf1d348cabL8-R8), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-9f1a179ed7be32b74e2e4b5d5b1158fc619865e5629751bc262062e95ca7760bL3-R3), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-ac245c12a952fbef3c8c416bbdfb2d521b99721145a089cbde3fe4efb825da2fL20-R20), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-910501cfc3cf214f00dbefc38dda8f41eb9851a2dfdc011c73bcc0bd980f2458L9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-af028735241aa73474fff8bc62bcd5e49f8cd2301fbe982ed954f893084380fcL9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-46d7a50b0508048458f0aead203cdcf1107b097999cb8e0d063faccd2e98ac3bL35-R46), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-3ddbe7bea9e4ecab5889cbe3f40d2d7337e0dee42a0b7dbdf8a734299f4a73f5L10-R10), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-2fa82442093eb4863a18b6984ae1c52f0d4a24d67326fa15d002d18816d9f31cL9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-2b0d9292f31caec05d5fba5f5586a3bb616076afadf2af619c878b869bd4a6d4L9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-a547f7581b5437077f6235a72c6b018f42ffed1019ca24e3951b173755a2ff87L10-R10), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-f738b23c10442b3b965f2377fcc88fd18d679aea39da15b3bf6c611e0196d2bbL10-R10), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-7ab25cafd22b71d453819949e30d615a936540e62e2dc463a329417fc2f06767L9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-728a871fc8a509ef8491ed6aea54840f9e65bcd808b011766eeeda90e4aa35f4L11-R11), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-559283093fb2a6f03b9c20c814f5bc829bb1befd31bbb1ab26fedcd7bf8bdfd3L9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-31c2cdf4b1399af94fc85e08b735d52725b015d1e5aa2ddb9d99edda4bceaf15L9-R9), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-7cb99b1fd6e4b01cafa4abbbe73c67f12f16229c9768fd83dc43acd0fec72a30L9-R9))
*  Added the taskName prop to the `failed-task-in-schema` source to allow filtering the failed tasks by a regex pattern ([link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-46d7a50b0508048458f0aead203cdcf1107b097999cb8e0d063faccd2e98ac3bR29-R34))
*  Modified the getFailedTasksInDatabase method of the `snowflake.app.mjs` file to accept the taskName parameter and use the INFORMATION_SCHEMA.TASK_HISTORY table function with additional parameters for performance and accuracy ([link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-867dee6344b167ef75ef90969a4511ccfd1cdc2bbc9579d7bcb6e9fe2df75536L177-R204))
*  Added the _getLastMaxTimestamp and _setLastMaxTimestamp methods to the `common.mjs` module to abstract the logic of getting and setting the last max timestamp from the database ([link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-8463d90b1fce2b0a62c9996d446a3b269e680bc0598a76accdadd3ea59d268d2R18-R23))
*  Modified the watchObjectsAndEmitChanges and emitFailedTasks methods of the `common.mjs` module to use the _getLastMaxTimestamp and _setLastMaxTimestamp methods instead of directly accessing the database, and to pass the taskName parameter to the getFailedTasksInDatabase method ([link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-8463d90b1fce2b0a62c9996d446a3b269e680bc0598a76accdadd3ea59d268d2L104-R110), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-8463d90b1fce2b0a62c9996d446a3b269e680bc0598a76accdadd3ea59d268d2L117-R135), [link](https://github.com/PipedreamHQ/pipedream/pull/6736/files?diff=unified&w=0#diff-8463d90b1fce2b0a62c9996d446a3b269e680bc0598a76accdadd3ea59d268d2L188-R191))

### CODE REVIEW

**Review by michelle0927 — DISMISSED** [review]
Looks good! Ready for QA!

**Comment by vunguyenhung** [comment]
Hello everyone, I have re-tested this PR and there's still a test cases failed.

Please check the test report below for more information
[Snowflake_6736_1107.pdf](https://github.com/PipedreamHQ/pipedream/files/11631788/Snowflake_6736_1107.pdf)

**Comment by vellames** [comment]
Closes #5867

**Review by michelle0927 — APPROVED** [review]

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Snowflake_6736_0922.pdf](https://github.com/PipedreamHQ/pipedream/files/11659317/Snowflake_6736_0922.pdf)

**Pull request merged**
