### PR TITLE
Monday - add additional props to create-item action

### LINKED ISSUE #4128: [BUG] Monday.com - Create Item - not respecting Item Column Values
**Describe the bug**

Using the built-in create_item for [Monday.com](http://monday.com/) I am able to create the item, but the Item column values are not being set.

**To Reproduce**
1. Create a Monday.com - Create Item action in a workflow
2. Set custom Item Column Values
3. Test
4. See a success message from the action

**Expected behavior**
Expected Behavior: On Create Item action, when I select the board, I should be able to see additional props matching columns for the board, so that user can input respective value. For example, for the board below, I should see 5 additional props matching with the highlighted columns
FireShot Capture 513 - Pipedeam test - hungvturing monday com
Reference: [Monday.com Columns Doc](https://developer.monday.com/api-reference/docs/columns-queries-1)

**Screenshots**
4f76d55b65e82fa275d89507cdd64a35cc7f2bc0_2_1380x734

**Additional context**
Problem reported here: https://pipedream.com/community/t/unable-to-set-values-in-columns-for-a-new-item-in-monday-com-integration/3112/3

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #4128

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4137"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by lcaresia — APPROVED** [review]
LGTM!

**Review by lcaresia — APPROVED** [review]
LGTM!

**Pull request merged**
