### PR TITLE
Salesforce - Refactor sources to be resilient to timeouts

### LINKED ISSUE #3500: [TRIGGER] Refactor Salesforce sources to be resilient to timeouts
[This user](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1658433674281529) encountered a timeout attempting to fetch events. If the run fails before we set the latest timestamp [at the end of the code](https://github.com/PipedreamHQ/pipedream/blob/master/components/salesforce_rest_api/sources/new-object/new-object.mjs#L66), we'll keep trying to fetch the same events over and over, exacerbating the timeout.

Can we modify the source to record the latest timestamp after each event (or each batch of events) so that we'll still record the last processed timestamp when the source times out? That way we should be able to support partial runs and pick up where we left off the next time the source runs.

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #3500 

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/3971"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by andrewjschuang — COMMENTED** [review]
@michelle0927 thanks for the contribution!

Can we also check in `new-object.isItemRelevant()` if `item !== undefined`? That seems the cause of the user error.

image

**Review by andrewjschuang — APPROVED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Salesforce_3971.pdf](https://github.com/PipedreamHQ/pipedream/files/9316040/Salesforce_3971.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Salesforce_3971_1857.pdf](https://github.com/PipedreamHQ/pipedream/files/9316087/Salesforce_3971_1857.pdf)

**Pull request merged**
