### PR TITLE
Fix linear app sources only fetch 100 records

### PR DESCRIPTION
**Pull request by jcortes**

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a `summary` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)

**Review by vellames — COMMENTED** [review]
I am wondering why the `version` is a new line and in most case, the version is not `0.0.1`. Probably you have a good reason behind this, but I cant see it

**Comment by jcortes** [comment]
> I am wondering why the `version` is a new line and in most case, the version is not `0.0.1`. Probably you have a good reason behind this, but I cant see it

Hi @vellames that's because now the [Check git diff for version changes](https://github.com/PipedreamHQ/pipedream/actions/runs/3146831171/jobs/5115719298) is taking into account all those components that have dependencies with the root app file and if that is true we should now add a `version` property otherwise we'll get check errors in that github action step. The version is the same as the components in `linear_app` since they were imported straight from the other components, so my first guess was that those components were deployed with those versions. e.g. [version: 0.3.7](https://github.com/PipedreamHQ/pipedream/pull/4368/files#diff-f81433db4c0df4c0056cd20a42da2f605db3a3742ab5c707e475586c6ad27d11R13)

**Review by vellames — APPROVED** [review]
lgtm

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Notion_4368.pdf](https://github.com/PipedreamHQ/pipedream/files/9707131/Notion_4368.pdf)

**Pull request merged**
