### PR TITLE
PostgreSQL actions - add rejectUnauthorized prop

### LINKED ISSUE #2808: [FEATURE] PostgreSQL actions should support optional `rejectUnauthorized` parameter
I need to set this as a user, so it should be an optional prop. See https://node-postgres.com/features/ssl

### PR DESCRIPTION
**Pull request by michelle0927**
Resolves #2808

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by lcaresia — DISMISSED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Postgres_3092.pdf](https://github.com/PipedreamHQ/pipedream/files/8899904/Postgres_3092.pdf)

**Comment by michelle0927** [comment]
@vunguyenhung I was able to reproduce the error. I believe the issue was from adding the `ssl` prop to all client configurations, however some servers don't support SSL connections. I updated it to only add that if `rejectUnauthorized` is set to `false`. It will still get an error if `rejectUnauthorized` is set to `false`, and the server doesn't support SSL.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Postgres_3092_2210.pdf](https://github.com/PipedreamHQ/pipedream/files/8920114/Postgres_3092_2210.pdf)

**Review by jcortes — APPROVED** [review]
Approved!

**Pull request merged**
