### PR TITLE
[Drata] Add deviceId async options

### PR DESCRIPTION
**Pull request by andrewjschuang**
Adds `async options()` for `deviceId` prop.

Info from Drata is that to list devices we need to first list the personnel and then extract the devices included in the personnel object.
From the sandbox environment, there was no device property besides the `id` that could help identify it better. Looking at the API Reference, `model` seems to be a good candidate.
And for some reason, I kept getting an error when trying to make it an `integer prop`, so I had to make a `string`.

### <samp>🤖 Generated by Copilot at 9abf9d2</samp>

This pull request adds a new feature to the `drata` component that allows selecting and uploading compliance documents for a specific device. It also removes an unused component and updates a dependency in the `pnpm-lock.yaml` file.

### <samp>🤖 Generated by Copilot at 9abf9d2</samp>

> _To upload a document with ease_
> _We updated the `deviceId` prop, please_
> _We used a `propDefinition`_
> _From the `drata` app's collection_
> _And bumped up the action and package versions by degrees_

### <samp>🤖 Generated by Copilot at 9abf9d2</samp>

*  Add `deviceId` prop definition to `drata` app and use it in `upload-device-compliance-document` action ([link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-60b002040098c47c885a597dacd638b9ee7ca5bc763e353ae519b547e798da02L10-R18), [link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-a07058fe354e5714b5b288324099660f299a6c49cb5ec445a7251a3072c43db2R76-R90))
*  Add `listDevices` method to `drata` app to fetch and sort device options for `deviceId` prop ([link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-a07058fe354e5714b5b288324099660f299a6c49cb5ec445a7251a3072c43db2R222-R230))
*  Increment `drata` package version to reflect app and action changes ([link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-f308bcfbd8557663c1c9360bb4d8bc09ad1946ad1dfe5c5bc638abe738126f45L3-R3))
*  Remove unused `danny_test_app` component from `pnpm-lock.yaml` file ([link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL885-L887))
*  Update `string-width` dependency version in `pnpm-lock.yaml` file ([link](https://github.com/PipedreamHQ/pipedream/pull/6111/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL24833-R24830))

### CODE REVIEW

**Review by feyzullah — APPROVED** [review]
LGTM!

**Comment by vunguyenhung** [comment]
Hello @dylburger, I have talked with @andrewjschuang about this and he informed that you will take over to test this ticket. May I confirm this information?

**Comment by dylburger** [comment]
Confirmed @vunguyenhung ! Will review ASAP

**Comment by vunguyenhung** [comment]
Hi, as this ticket has been hanging for a while. I will mark this as ready for release. We can have another ticket if needed

**Comment by dylburger** [comment]
Thanks @vunguyenhung ! Agreed let’s ship and if we observe bugs, we can always fix later.

**Pull request merged**
