### PR TITLE
4287 clickup custom task

### PR DESCRIPTION
**Pull request by alysonturing**
### ClickUp
- Adding support to `custom task id` and `authorized team` props
- Fixing bugs that I found on the way

**Updated Actions**
- create-checklist
- create-checklist-item
- create-task-comment
- delete-checklist
- delete-checklist-item
- delete-comment
- delete-task
- get-task
- get-task-comments
- remove-task-custom-field
- update-checklist
- update-checklist-item
- update-comment
- update-task
- update-task-custom-field

<a href="https://gitpod.io/#https://github.com/PipedreamHQ/pipedream/pull/4446"></a>

### CODE REVIEW

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by feyzullah — COMMENTED** [review]
Hi @alysonturing, I wonder if you can move commonly used props to a common file or not. It seems that `useCustomTaskIds` and `authorizedTeamId` are used in many components. If possible can you please move common props to a common file while you are refactoring already? If something blocks you to do that please let me know and approve, because this one looks good to me except this.

**Comment by feyzullah** [comment]
> 

@alysonturing as you state that moving props to a common file will be very time consuming and risky in means of being prone to bugs, I am approving this PR. Thank you!

**Review by feyzullah — APPROVED** [review]

**Comment by alysonturing** [comment]
> Hi @alysonturing , I am observing some issues in **remove_task_custom_field** action where I'm unable to select task. And if all fields are entered "Test" button in action remains disabled. Also the "Authorized Team" field is disabled before entering values for other fields. image image
> 
> Also in all "**Update_**" actions "Task" field is stuck and unable to enter values image

Hello, I believe that your ClickUp settings for `Custom task id` are turned off on settings, please check it again after enabling it. I changed the component to detect this issue when trying to fetch the tasks using `custom task id`.

image

**Review by feyzullah — APPROVED** [review]

**Comment by DilanAthukorala** [comment]
Verification completed, this is ready for release.

**Pull request merged**
