### PR TITLE
Converting string props takerProfitPrice and stopLossPrice to float

### PR DESCRIPTION
**Pull request by lcaresia**
### <samp>🤖 Generated by Copilot at 1d9dc10</samp>

Fixed decimal number handling and bugs in `bingx/actions/trade-new-order/trade-new-order.mjs` and bumped the version of `bingx/package.json` to 0.1.1.

### <samp>🤖 Generated by Copilot at 1d9dc10</samp>

> _`BingX` is the package of doom_
> _It brings confusion and despair_
> _But we updated the version and the component_
> _To handle decimals and fix the bugs in there_

### <samp>🤖 Generated by Copilot at 1d9dc10</samp>

*  Update the version of the BingX package and the BingX Trade New Order component to 0.1.1 ([link](https://github.com/PipedreamHQ/pipedream/pull/6403/files?diff=unified&w=0#diff-e3ce12deae82dd360db064c144edcb44b0459f2bc6b57de7e0f4cfa5b35a0937L5-R5), [link](https://github.com/PipedreamHQ/pipedream/pull/6403/files?diff=unified&w=0#diff-37e6e279bc7d94ca0ed853df4c0467bb6a7c0cfcb8f17e156323f8f896cd1ae5L3-R3))
*  Fix the parsing of the takerProfitPrice and stopLossPrice parameters in the `trade-new-order.mjs` file to use floats with dots as separators ([link](https://github.com/PipedreamHQ/pipedream/pull/6403/files?diff=unified&w=0#diff-e3ce12deae82dd360db064c144edcb44b0459f2bc6b57de7e0f4cfa5b35a0937R63-R71))

### CODE REVIEW

**Comment by lcaresia** [comment]
Cc: @zaiden96

**Review by GTFalcao — APPROVED** [review]
Hi @lcaresia , thanks for the fix, looks good to me!

**Comment by zaiden96** [comment]
@lcaresia , @GTFalcao , and @dylburger - thank you all so much for the help on this! really appreciated.

**Pull request merged**
