### PR TITLE
[ACTION] Initial version of showpad custom crm hubspot component

### PR DESCRIPTION
**Pull request by woutersmet**

### CODE REVIEW

**Comment by dylburger** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by dylburger** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Comment by woutersmet** [comment]
Aha, note to self, seems indeed Hubspot API has a node client library: https://github.com/HubSpot/hubspot-api-nodejs so should probably use that as per the guidelines then.

**Comment by woutersmet** [comment]
Note that 'Showpad' is not in there as an app yet - started convo in the #contribute channel here on this https://pipedream-users.slack.com/archives/C01E5KCTR16/p1660376174630889 - this is a pretty experimental 'component', so any way to 'publish' it that doesn't make it part of the public repo yet is welcome.

**Review by vellames — CHANGES_REQUESTED** [review]
Hi there, I would suggest splitting the code into some files. 
You could move the helper functions to a different file.
The class `HubsportClient` also could be in a separate file.
I see you are doing other things based on `req.path`. Maybe we could have different actions? One for each `if`?

**Comment by vunguyenhung** [comment]
Greetings, @woutersmet just a quick check-in. Do you have time to reply to [the adjustments @vellames suggested here](https://github.com/PipedreamHQ/pipedream/pull/4004#pullrequestreview-1072864143)? 

Do you prefer our component developer to assist you when we have bandwidth?

**Comment by dannyroosevelt** [comment]
@vellames @lcaresia can one of you implement the suggested changes so we can finish this one up?

**Comment by lcaresia** [comment]
@dannyroosevelt Yes, I can!

**Comment by dannyroosevelt** [comment]
@lcaresia what's the deal with this? Can we close this one in favor of your PR?

**Comment by woutersmet** [comment]
Hi guys, sorry for the late replies - to be honest I'm not hoping/planning to have this one merged in just yet. (used to gitlab, where a 'WIP' PR is a nice way to keep an overview of your work, even if you don't expect to get merged just yet. So I think I best close this request and just keep working on my branch to avoid confusion or getting merged in prematurely?

**Comment by dannyroosevelt** [comment]
> Hi guys, sorry for the late replies - to be honest I'm not hoping/planning to have this one merged in just yet. (used to gitlab, where a 'WIP' PR is a nice way to keep an overview of your work, even if you don't expect to get merged just yet. So I think I best close this request and just keep working on my branch to avoid confusion or getting merged in prematurely?

@woutersmet no problem, noted!

**Pull request closed without merging**
