### PR TITLE
Included All Bookmarks, Unsorted and Trash in collections

### PR DESCRIPTION
**Pull request by EjDadivas**
## WHAT

I included getting all bookmarks, unsorted bookmarks, and trashed bookmarks. To get all bookmarks, I noticed in the endpoint that the collectionID used for this is 0. I inlcuded Unsorted bookmarks which is -1, and trash which is -99.
image
image
image

I also check the endpoint and with these ID's and works well. 

image

## WHY
I need to get all bookmarks that doesn't belong to a collection ID. Sometimes a new bookmark will be added without a specific collection and will directly go to All Bookmarks. I also need to retrieve it from All Bookmarks too.
image

### CODE REVIEW

**Comment by pipedream-component-development** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by pipedream-component-development** [comment]
Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:
- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component `key`s should follow the format `app_name_slug-slugified-component-name`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use `secret` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use `optional` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a `default` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible

**Review by michelle0927 — APPROVED** [review]
Thank you for this contribution! Looks good, Ready for QA.

**Review by lcaresia — APPROVED** [review]

**Comment by EjDadivas** [comment]
Hello, I have updated the version in package.json

**Comment by EjDadivas** [comment]
Thanks. May I know when will this be released?

**Comment by EjDadivas** [comment]
Thanks. May I know when will this be released?

**Review by michelle0927 — APPROVED** [review]

**Comment by michelle0927** [comment]
> Thanks. May I know when will this be released?

Hi, @EjDadivas , This has just been published!

**Pull request merged**
